### PR TITLE
Add the time to wait before reboot by 'pcmk_panic'

### PR DESCRIPTION
**Pull request by yuusuke**
HI, Ken
I was fixed patch.
If looks good I want you to merge.

But the patch which changed action in panic which I sent first was more useful for us in the meaning that I left information at the time of the trouble for .
Rather than the patch of this "delay", or not considered once again to merge it?

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi Yuusuke,

Which do you think is better for your needs -- this patch (panic delay) or the original one (crash dump instead of reboot)? The main advantage I see for the panic delay is that, if the trouble is due to the problems with the disk itself, it can't hang for longer than the delay.

**Comment by yuusuke** [comment]
Hi, Ken

We think that crash dump is better.
Because,
I think that the time when offline is detected by other nodes is earlier when I stop a system in crash.
Because both the log and the crash dump may remain neither when a disk has a problem, I think that there is not the difference there.
In this case it thinks that there is no help for it that information does not remain.

If the disk itself there is a problem, why can not hang?
I am not familiar regarding this situation, I want you to tell me.

**Comment by kgaillot** [comment]
If a disk fails, I/O operations to that disk may hang, but the host will continue to run processes that don't require I/O to that disk. If the cluster daemons are hung trying to write to that disk, that will delay the self-fencing, leaving other processes still active and potentially causing problems.

**Comment by yuusuke** [comment]
Hi, Ken

Thank you for comment.
Now of the pcmk_panic_local () sync () does not exist.
Therefore , I think that I/O from pacemakerd to a disk occurs by processing of pcmk_panic_local() and do not hang .
Therefore I think that it is not inhibited that I let do crash of system .
https://github.com/ClusterLabs/pacemaker/pull/874/commits/b639a9db8b894f0bba0159c8e1ac5b5b20941ff2
Is my recognition right ?

**Comment by kgaillot** [comment]
Hi Yuusuke,

I'm closing this in favor of #874. Try that, and if it's not sufficient for your needs, we can revisit this option.

We also have plans to add an option to change liqb's logging to non-threaded mode, which will flush all logs to disk immediately. That will have a severe performance impact in most cases, but can be useful when reproducing a known issue in a test cluster.

**Pull request closed without merging**
