### PR TITLE
Fix: cts-cli: Make output independent of test selection and order

### PR DESCRIPTION
**Pull request by nrwahl2**
Currently, two test functions enable `PCMK_stderr` and export certain values for `PCMK_trace_functions`. Since these environment variables affect all tests run after they're set, the `cts-cli` output depends on (a) which tests are run and (b) the order in which they're run.

Here, we export `PCMK_stderr=1` during initialization so that we log to stderr for all tests. We also save the initial value before setting `PCMK_trace_functions`, and then we restore the initial value when we're finished with a test group that changed it. Currently the initial value is always the empty string, but that could change.

Finally, we set trace function values for the upgrade test as well. It's been inheriting the validity test group's trace functions, but that's once again an ordering dependency that we want to eliminate.

We lose a bit of ACL tracing during one test: "Upgrade to latest CIB schema." It seems that tracing never should have been present, as it was only intended for the `test_acl_loop()` function. It's trivial to restore it if we ever want to.

Closes T548

### CODE REVIEW

**Review by kgaillot — APPROVED** [review]
Excellent

**Comment by kgaillot** [comment]
Validity tests changed output on some platforms, not sure why

**Comment by nrwahl2** [comment]
Tools too. Fedora36 s390x:
```
14:19:46 1 tests faiiled; see output in:
14:19:46     /tmp/cts-cli.tools.LfDa9XlcUy
14:19:46     /tmp/cts-cli.validity.0vsRomF072
```

**Comment by nrwahl2** [comment]
Looks similar to this: https://unix.stackexchange.com/questions/556386/bash-race-condition-with-pipeline-tee-and-process-substitution

**Comment by nrwahl2** [comment]
I think I got it. I should have used the classic approach instead of trying to be slick with process substitution. Apparently process substitution runs the command asynchronously, so it's prone to race conditions.

**Comment by nrwahl2** [comment]
> I should have used the classic approach

Referring to creating a temporary file descriptor.

Nope, there's still nondeterminism. I think that's gonna happen any way we slice it, unless we bind redirect stderr to fd 1 before pipe to `tee`.

The current update uses a named pipe for stderr and explicitly prints stderr and stdout. That **should** give us deterministic behavior. I also removed `outfile` altogether, capturing stdout to a variable instead.

**Pull request merged**
