### PR TITLE
collect info from /proc/drbd, if present

### PR DESCRIPTION
**Pull request by haySwim**
/proc/drbd contains detailed information about the version of DRBD and the status of DRBD resources, their devices, and their connections and is often invaluable in troubleshooting issues with DRBD.

### CODE REVIEW

**Comment by kgaillot** [comment]
I like the idea, but a couple of recommendations:

* DRBD doesn't really fit into the realm of "system statistics" like CPU usage. It probably deserves its own file (comparable to what dlm_dump does for DLM).
* /proc/drbd is deprecated ( https://www.drbd.org/en/doc/users-guide-90/s-check-status ) so maybe we should try one of the newer mechanisms if it is available, and use /proc/drbd as a fallback (or in addition).

**Comment by haySwim** [comment]
> DRBD doesn't really fit into the realm of "system statistics" like CPU usage. It probably deserves its own file (comparable to what dlm_dump does for DLM).

This is a fair point.

> /proc/drbd is deprecated ( https://www.drbd.org/en/doc/users-guide-90/s-check-status ) so maybe we should try one of the newer mechanisms if it is available, and use /proc/drbd as a fallback (or in addition).

/proc/drbd still contains build and version info so I think there's merit in including it. `drbdsetup events2`, `drbd-overview`, and `drbdadm show-gi` all work in DRBD8 and DRBD9. `drbdsetup status` is only available on DRBD9, but contains mostly the same info as `drbdsetup events2`, although the formatting is more human-friendly. 

If we do end up creating a separate file, I don't see a reason not to try and include the output from all of these.

**Comment by haySwim** [comment]
Ok, this now collects info into a separate file, similar to dlm_dump.  Here's an example of the output with DRBD9: http://pastebin.com/EnK64YSw

The commands are run roughly in order from least to most granular data output.

**Comment by kgaillot** [comment]
Looks great! Two minor requests: please resubmit this as a single commit, and redirect each drbd command's stderr to either null or stdout.

**Comment by haySwim** [comment]
> Looks great! Two minor requests: please resubmit this as a single commit, and redirect each drbd command's stderr to either null or stdout.

Thanks! stdeer redirected to stdout and everything squashed into one commit.

**Pull request merged**
