### PR TITLE
Build: Fix building when heartbeat support is disabled

### PR DESCRIPTION
**Pull request by gao-yan**

### CODE REVIEW

**Comment by beekhof** [comment]
Thanks yan! Baaaad @lge :)

**Comment by lge** [comment]
> Thanks yan! Baaaad @lge :)
> https://github.com/ClusterLabs/pacemaker/pull/649#issuecomment-75829783

Where build "error" was unused static function, I guess?

Right. Thanks.

Though, heartbeat stack support, and heartbeat style agents support
are actually different things. I'm not sure yet, but I may propose
a patch changing some of the #if SUPPORT_HEARTBEAT to #if SUPPORT_HB_AGENTS,
and would have that enabled by default...

**Comment by kgaillot** [comment]
On 02/25/2015 08:50 AM, Lars Ellenberg wrote:
>> Thanks yan! Baaaad @lge :)
>> https://github.com/ClusterLabs/pacemaker/pull/649#issuecomment-75829783
> 
> Where build "error" was unused static function, I guess?

Undefined constant HB_RA_DIR, hurts a little more ;-)

> Right. Thanks.
> 
> Though, heartbeat stack support, and heartbeat style agents support
> are actually different things. I'm not sure yet, but I may propose
> a patch changing some of the #if SUPPORT_HEARTBEAT to #if SUPPORT_HB_AGENTS,
> and would have that enabled by default...

That makes sense -- anything that doesn't require the extra libraries
could be outside SUPPORT_HEARTBEAT.

**Comment by gao-yan** [comment]
Support of heartbeat v1 style agents requires heartbeat anyway, no?

**Comment by lge** [comment]
On Wed, Feb 25, 2015 at 07:57:46AM -0800, Gao,Yan wrote:
> Support of heartbeat v1 style agents requires heartbeat anyway, no?

Not at all.

In "grown", old, existing systems, there are many homegrown heartbeat
style agents, mostly wrapping some not-so-lsb-standard init script of
some "application".

Also consider the scenario where you want to upgrade such a system,
maybe also change the cluster stack to corosync, but do not want to
rewrite all these agents into OCF ones at the same time.

heartbeat style agents are similar to LSB scripts, but
  * take positional arguments
  * ignore the exit code of the status action,
    but look on stdout for
      "NOT running", "stopped"
      resp.
      "running", "OK"
    where OK is matched case sensitive,
    all others are matched case insensitive,
    and if nothing matched it is assumed to be cleanly stopped.

Not ideal, but easy enough to be hacked up in a few minutes.
Which means there are a lot of these, most probably home grown.

Yes, they all could, and should, be rewritten as OCF.
But once the guy supposed to do that sees that he needs to do
"all this boilerplate", he shies away immediately.

**Comment by gao-yan** [comment]
Yeah, I can imagine. Glad to know, thanks.

**Pull request merged**
