### PR TITLE
More small fixups

### PR DESCRIPTION
**Pull request by clumens**

### CODE REVIEW

**Comment by kgaillot** [comment]
Fabio found this through CI, can you throw it in there so I don't have to do a separate PR?

diff --git a/rpm/pacemaker.spec.in b/rpm/pacemaker.spec.in
index c0c8a5baa..741e4231f 100644
--- a/rpm/pacemaker.spec.in
+++ b/rpm/pacemaker.spec.in
@@ -683,7 +683,7 @@ getent passwd %{uname} >/dev/null || useradd -r -g 
%{gname} -u %{hacluster_id} -
  exit 0

  %if %{defined ldconfig_scriptlets}
-%ldconfig_scriptlets libs
+%ldconfig_scriptlets -n %{pkgname_pcmk_libs}
  %ldconfig_scriptlets cluster-libs
  %else
  %post -n %{pkgname_pcmk_libs} -p /sbin/ldconfig

**Comment by clumens** [comment]
Sure, just trying to figure out what it does to leave a more useful commit message.  Also, does the second one need to be changed as well or just the first?

**Comment by kgaillot** [comment]
Sorry, a little late :) How about this:

Build: rpm: restore build on latest OpenSUSE

OpenSUSE tumbleweed has enabled the ldconfig_scriptlets macro, which has uncovered one package name that we forgot to update to a variable. Found and fixed by Fabio DiNitto <fdinitto@redhat.com>.

**Comment by clumens** [comment]
That is so much better than my dumb placeholder.  Re-pushed.

**Pull request merged**
