### PR TITLE
Backport memory cleanup to 2.1 branch

### PR DESCRIPTION
**Pull request by kgaillot**

### CODE REVIEW

**Comment by kgaillot** [comment]
@clumens , and here's the backport to 2.1 of the relevant cleanup. This required minor changes

**Review by clumens — APPROVED** [review]

**Comment by HideoYamauchi** [comment]
Hi @kgaillot

I have a question.

This leak is related to the error termination, but can it be detected by valgrind?
Or is there something else I can check besides valgrind?

Best Regrards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
@kgaillot 

All right!
Thanks for the detailed answer.

Many thanks,
Hideo Yamauchi.

**Comment by clumens** [comment]
The CI failures are just the same rpmlint failure from earlier.

**Pull request merged**
