### PR TITLE
Fix regression in crm_verify

### PR DESCRIPTION
**Pull request by kgaillot**

### CODE REVIEW

**Comment by kgaillot** [comment]
@waltdisgrace , I found this while getting ready for release. Can you review it when you get a chance? Thanks

**Comment by waltdisgrace** [comment]
> @waltdisgrace , I found this while getting ready for release. Can you review it when you get a chance? Thanks

Do you think we should add tests for --verbose and --quiet to cli-cli.in?

I added tests that contained these lines:

    cmd="crm_verify --xml-file '$CIB_file_invalid_1' --verbose --output-as=xml"
    test_assert_validate $CRM_EX_CONFIG 0
    
        cmd="crm_verify --xml-file '$CIB_file_invalid_1' --quiet --output-as=xml"
    test_assert_validate $CRM_EX_CONFIG 0

and the tests seemed to validate the changes you made in this PR.

(This PR removed one line, the error message, from the output of the quiet test. The output of the verbose test stayed the same.)

**Comment by kgaillot** [comment]
> Do you think we should add tests for --verbose and --quiet to cli-cli.in?

Yes, I was just lazy :) Added

**Comment by waltdisgrace** [comment]
> > Do you think we should add tests for --verbose and --quiet to cli-cli.in?
> 
> Yes, I was just lazy :) Added

The tests look great.

**Pull request merged**
