### PR TITLE
Feature: Allow regexp substitutions in location constraints

### PR DESCRIPTION
**Pull request by bubble75**
It was already possible to use regexp in a resource name location applies to.
Now it is also possible to use sed-like %0 - %9 references in both
score-attribute and rule expression to construct attribute names.
(% is used instead of \ to make crmsh almost happy).

Also, fix rsc_pattern is missing from constraints rng ecept constraints-next.

### CODE REVIEW

**Comment by kgaillot** [comment]
This is an interesting feature. What are some potential real-world uses?

I think the resolver is sufficiently generic that we could expose it in lib/common/utils.c as crm_expand_re_matches(), and call it directly in test_attr_expression() rather than use a nested structure to hide it. The structure definition itself could stay private in utils.c, if we provide an initialization function for it.

We aim for public ABI backward compatibility, where everything under include/crm without "internal" in its name is considered the public API. The customary approach would be to define new functions pe_test_{rule,expression}_re() with the additional argument, and make the original functions wrappers that simply call the new function with a NULL last argument.

Any publicly exposed symbols (such as public API structure/type names) should start with crm_ or pe_. Unfortunately, we have plenty of legacy names that don't follow that, but we try to follow it for new additions.

**Comment by beekhof** [comment]
Can you show us some examples?

**Comment by bubble75** [comment]
@kgaillot , @beekhof This is for cattle-style resources. (And this is already in testing for a big-data project, which manages lustre fs - hundreds of resources). For this project I need to:

* Prevent "forwarded IO", allocating lustre resource on nodes which have short path to a given disk.
* Allow admin to set a preferences so even if several nodes have same short path, some of them will be preferred.

Previously that was accomplished by adding two location constraints for every resource, which use score provided by a corresponding attribute (attributes for a given node are set by a custom RA, which queries hardware for a path length and configuration for admin preferences).

With this feature it is enough to have just two constraints in CIB.

I'll post a used CIB snippet a bit later, when I have access to a test HW.

**Comment by bubble75** [comment]
@kgaillot OK, I'll refactor this as soon as time permits.

**Comment by bubble75** [comment]
Here is what we had before this commit (in crmsh syntax). All possible CIB size optimizations I'm aware of are in place: resource templates, colocations, orders, tickets and even locations (that is undocumented btw):
<pre>
primitive ost0000-fs01 @lustre-fs01-ost \
        params device="/dev/ddn/fs01_ost0000" directory="/lustre/fs01/ost0000"
primitive ost0000-fs02 @lustre-fs02-ost \
        params device="/dev/ddn/fs02_ost0000" directory="/lustre/fs02/ost0000"
primitive ost0001-fs01 @lustre-fs01-ost \
        params device="/dev/ddn/fs01_ost0001" directory="/lustre/fs01/ost0001"
primitive ost0001-fs02 @lustre-fs02-ost \
        params device="/dev/ddn/fs02_ost0001" directory="/lustre/fs02/ost0001"
location ost0000-fs01-prefer-home-node ost0000-fs01 \
        rule ost0000-fs01-preference-auto: defined ost0000-fs01-preference-auto
location ost0000-fs01-prefer-master-node ost0000-fs01 \
        rule ost0000-fs01-preference-config: defined ost0000-fs01-preference-config
location ost0000-fs02-prefer-home-node ost0000-fs02 \
        rule ost0000-fs02-preference-auto: defined ost0000-fs02-preference-auto
location ost0000-fs02-prefer-master-node ost0000-fs02 \
        rule ost0000-fs02-preference-config: defined ost0000-fs02-preference-config
location ost0001-fs01-prefer-home-node ost0001-fs01 \
        rule ost0001-fs01-preference-auto: defined ost0001-fs01-preference-auto
location ost0001-fs01-prefer-master-node ost0001-fs01 \
        rule ost0001-fs01-preference-config: defined ost0001-fs01-preference-config
location ost0001-fs02-prefer-home-node ost0001-fs02 \
        rule ost0001-fs02-preference-auto: defined ost0001-fs02-preference-auto
location ost0001-fs02-prefer-master-node ost0001-fs02 \
        rule ost0001-fs02-preference-config: defined ost0001-fs02-preference-config
</pre>

That is for four OST resources in two filesystems (two per lustre filesystem).
With this patch we may collapse given configuration into:
<pre>
primitive ost0000-fs01 @lustre-fs01-ost \
        params device="/dev/ddn/fs01_ost0000" directory="/lustre/fs01/ost0000"
primitive ost0000-fs02 @lustre-fs02-ost \
        params device="/dev/ddn/fs02_ost0000" directory="/lustre/fs02/ost0000"
primitive ost0001-fs01 @lustre-fs01-ost \
        params device="/dev/ddn/fs01_ost0001" directory="/lustre/fs01/ost0001"
primitive ost0001-fs02 @lustre-fs02-ost \
        params device="/dev/ddn/fs02_ost0001" directory="/lustre/fs02/ost0001"
location ost-prefer-home-node /ost([[:digit:]]{4})-(.+)/ \
        rule ost%1-%2-preference-auto: defined ost%1-%2-preference-auto
location ost-prefer-master-node /ost([[:digit:]]{4})-(.+)/ \
        rule ost%1-%2-preference-config: defined ost%1-%2-preference-config
</pre>

Again, this is just for four resources, we plan to handle 400+.

**Comment by bubble75** [comment]
@kgaillot 

> I think the resolver is sufficiently generic that we could expose it in lib/common/utils.c as crm_expand_re_matches(), and call it directly in test_attr_expression() rather than use a nested structure to hide it. The structure definition itself could stay private in utils.c, if we provide an initialization function for it.

attrd cannot be built that way, so I moved resolver to lib/pengine/rules.c and called it pe_expand_re_matches(). That is more natural I think.
Also, structure cannot be made private because I need to initialize it in pengine. I do not want to introduce allocator/deallocator for it, preferring to keep it static there.

Will now build and test packages, then update commit.

**Comment by bubble75** [comment]
Well, I updated commit, it builds correctly with -Werror, but I do not have a chance to check today.

**Comment by kgaillot** [comment]
Looks great, thanks!

RNGs are updated differently -- existing versions are (supposed to be) fixed, and any changes must go into a new version. Copy constraints-2.3.rng to constraints-2.6.rng, make a separate commit adding the new file, then make the desired change to that file in another commit. The makefile will automatically build pacemaker-2.6.rng including the change. This ensures that configurations using a new feature can't be mistakenly used with versions that don't support it.

Note that existing cluster configurations must be updated with "cibadmin --upgrade" (or a higher-level equivalent) before the cluster can use the new feature.

FYI, having it only in "-next" wasn't an oversight -- experimental features often go there first, and we wait for feedback from users before making it official, so we can make changes without worrying about backward compatibility. In this case, it's been there a long while, with no complaints, and you're providing the feedback that it's useful :) so it's a good time to make it official.

**Comment by bubble75** [comment]
Btw 'cibadmin --upgrade --force' hangs if called more than once ;)

**Comment by bubble75** [comment]
Well, commit is tested and works:
<pre>
Node Attributes:
* Node nodeA:
    ...
    + ost0000-fs01-preference-config   : 100
    + ost0000-fs02-preference-config   : 100
    + ost0001-fs01-preference-config   : 100
    + ost0001-fs02-preference-config   : 99
    + ost0002-fs01-preference-config   : 99
    + ost0003-fs01-preference-config   : 99
    ...
* Node nodeB:
    ...
    + ost0000-fs01-preference-config   : 99
    + ost0000-fs02-preference-config   : 99
    + ost0001-fs01-preference-config   : 99
    + ost0001-fs02-preference-config   : 100
    + ost0002-fs01-preference-config   : 100
    + ost0003-fs01-preference-config   : 100
    ...
</pre>

<pre>
native_color: ost0000-fs01 allocation score on nodeA: 100
native_color: ost0000-fs01 allocation score on nodeB: 99
native_color: ost0000-fs02 allocation score on nodeA: 100
native_color: ost0000-fs02 allocation score on nodeB: 99
native_color: ost0001-fs01 allocation score on nodeA: 100
native_color: ost0001-fs01 allocation score on nodeB: 99
native_color: ost0001-fs02 allocation score on nodeA: 99
native_color: ost0001-fs02 allocation score on nodeB: 100
native_color: ost0002-fs01 allocation score on nodeA: 99
native_color: ost0002-fs01 allocation score on nodeB: 100
native_color: ost0003-fs01 allocation score on nodeA: 99
native_color: ost0003-fs01 allocation score on nodeB: 100
</pre>

**Comment by bubble75** [comment]
Commit is split to 3 as requested.

**Comment by beekhof** [comment]
That is pretty darn cool

**Pull request merged**
