### PR TITLE
Fix: pengine: Consider resource failed if any of the configured monitor operations failed

### PR DESCRIPTION
**Pull request by gao-yan**
Previously with d87de1b, if not all the configured monitor operations
failed, the resource could be considered running well.

This commit fixes it by conditionally "clear_past_failure".

### CODE REVIEW

**Comment by kgaillot** [comment]
The new "if" should be inside the existing CRMD_ACTION_STATUS block rather than combined with its condition, so we don't compare task against every other action when we know those won't match. That also means the new "if" should apply only to clear_past_failure, not set_active(), since we won't fall through to the last "else if" block.

(Aside: I'm not sure that last "else if" block should even be there; migrate_to and migrate_from are now handled before it. Maybe reload or notify could end up there?)

However, I'm not sure this fix is sufficient. Does this handle the situation d87de1b was meant for -- when the previous failure was from the same (interval) monitor? It seems that should be cleared, regardless of *on_fail. Somehow, we need to know whether the failure was from the same monitor or not. Or am I missing something ...

**Comment by gao-yan** [comment]
I think the last "else if" wants to make sure any other cases that end up there should be considered that the resource is active. But yes, we'd better handle all CRMD_ACTION_STATUS cases inside one block. A monitor that didn't return PCMK_OCF_NOT_RUNNING indicates the resource is active anyway.

For the situation d87de1b, if there's a previous failure, and now we are handling an still existing monitor, I think we can at least assume the previous failure is a monitor instead of a start/stop... Given the context of the code, it's not quite easy to check if the previous failure is from the same (interval) monitor. And at least for single monitor case, the *on_fail from the last failure is very likely (or 100%?) to be action_fail_block.  So d87de1b simply  "clear_past_failure".  

 -- I guess this's what Andrew was thinking ;)

But I think we can at least be more specific for the case of action_fail_block. For any other cases, the previous failure should not be just overridden unless we see an actual case.

Let's say this is a still compromised but improved solution, until we see the necessity and figure out a way to find out whether the previous failure is from the same monitor.

**Comment by gao-yan** [comment]
Thought it through. Let's just record and pass in the last failure.

**Comment by kgaillot** [comment]
If I'm following your idea correctly, I think one failure might not be enough -- what if both monitors had failed? I think we'd need to record the last failed result and last successful result of every monitor.

**Comment by gao-yan** [comment]
Practically, cib records only one last failure for a resource on each node, no matter if it's monitor or any other operation or how long the interval is ;)

**Comment by gao-yan** [comment]
Amended and pushed.

**Comment by kgaillot** [comment]
I like this approach, and I'm glad we have a regression test for this case now.

The only drawback I see is that if two monitors fail, the behavior is unpredictable; a successful monitor might or might not clear the previous failures, depending on what order they're in. But that's a smaller problem space than the existing code.

**Comment by gao-yan** [comment]
It especially depends on which monitor failure is recorded in the cib. A successful monitor shouldn't clear the "known" previous failure from a different monitor anyway.

**Pull request merged**
