### PR TITLE
Stonithd reconnect history 1.1

### PR DESCRIPTION
**Pull request by wenningerk**

### CODE REVIEW

**Comment by wenningerk** [comment]
Tests with CTS are looking fine.
One thing showed up but does as well without the patches:
Jul 09 14:55:18	BadNews: Jul 09 14:53:58 node3 pacemaker_remoted[28229]:    error: Listener socket creation failed: Address family not supported by protocol (97)

Running crmd and stonith-ng under valgrind showed a leak in crmd when reconnecting to stonithd.
But that was there as well before.
Hope I'll find time today to dig into that as it at least somehow fits to the topic of that PR.
Don't think I had seen it with the master-branch ... maybe a fix that didn't make it into 1.1 ... I'll check ...

**Comment by kgaillot** [comment]
> Tests with CTS are looking fine.
> One thing showed up but does as well without the patches:
> Jul 09 14:55:18 BadNews: Jul 09 14:53:58 node3 pacemaker_remoted[28229]: error: Listener socket creation failed: Address family not supported by protocol (97)

Odd, I haven't seen that one. That looks like EAFNOSUPPORT coming from socket(). Was this under valgrind? I always see bizarre errors under valgrind, and ignore them if they don't happen in normal use and don't show memory issues.

> Running crmd and stonith-ng under valgrind showed a leak in crmd when reconnecting to stonithd.
> But that was there as well before.
> Hope I'll find time today to dig into that as it at least somehow fits to the topic of that PR.
> Don't think I had seen it with the master-branch ... maybe a fix that didn't make it into 1.1 ... I'll check ...
> It is one block of 37 bytes per reconnection - so shouldn't be too hard to find ...

I don't recall seeing that one either, unless it's the token leak I thought was fixed.

**Comment by wenningerk** [comment]
> > Tests with CTS are looking fine.
> > One thing showed up but does as well without the patches:
> > Jul 09 14:55:18 BadNews: Jul 09 14:53:58 node3 pacemaker_remoted[28229]: error: Listener socket creation failed: Address family not supported by protocol (97)
> 
> Odd, I haven't seen that one. That looks like EAFNOSUPPORT coming from socket(). Was this under valgrind? I always see bizarre errors under valgrind, and ignore them if they don't happen in normal use and don't show memory issues.
> 
No, remember definitely to have installed valgrind just after the cts run.

> > Running crmd and stonith-ng under valgrind showed a leak in crmd when reconnecting to stonithd.
> > But that was there as well before.
> > Hope I'll find time today to dig into that as it at least somehow fits to the topic of that PR.
> > Don't think I had seen it with the master-branch ... maybe a fix that didn't make it into 1.1 ... I'll check ...
> > It is one block of 37 bytes per reconnection - so shouldn't be too hard to find ...
> 
> I don't recall seeing that one either, unless it's the token leak I thought was fixed.

It is the token-leak.

**Comment by wenningerk** [comment]
The last commit takes care of the token-leak.
Reason why it doesn't appear on master-branch is probably different order of callbacks called by the ipc or something. In any case adding that to master probably wouldn't be wrong (should be the other way round ...)

**Comment by kgaillot** [comment]
I do think it will be a good idea to add that last commit to master as a fail-safe

**Pull request merged**
