### PR TITLE
Test: scheduler: Promotable bundle colocations

### PR DESCRIPTION
**Pull request by nrwahl2**
Currently, bundle colocations aren't considered properly with respect to promotion, including in the determination of instance ordering. These tests set a baseline for the behavior of a promotable bundle in various colocations with a primitive IPaddr2 resource and with another bundle.

Here we add 12 tests covering all combinations of:
* Resource types:
  * Primary bundle promoted instance, dependent primitive
  * Dependent bundle promoted instance, primary primitive
  * Primary and dependent bundle promoted instances
* colocation or anti-colocation
* mandatory or optional

Currently only bundle-promoted-colocation-1 is correct.

### CODE REVIEW

**Comment by nrwahl2** [comment]
@kgaillot One of the barriers to T489 had been that I wanted to make sure the fix worked correctly with bundles. It worked with other resource types.

Currently my plan is to ignore the bundle testing for now, since promotable bundle colocations are even more screwed up than I thought. It's already going to take a bit of work to update the old commit that fixes the main clone shuffling issue, and evaluate and clean up the tests for it that I wrote back then.

See also https://github.com/ClusterLabs/pacemaker/pull/2313/commits/1a4f92a1f4b114b28bf31469270ef34f0aa4c60a#r619490580

**Comment by nrwahl2** [comment]
Your work on colocations -- specifically, on making it so that a negative total score doesn't prevent a resource from running -- makes it easier to reason about how things should behave, at least.

I'm not sure yet whether those changes apply to promotion scores -- for example, `-1` promotion score might still mean "ineligible for promotion."

**Comment by nrwahl2** [comment]
Updated to note that `bundle-promoted-colocation-2` is also wrong :)

**Review by kgaillot — APPROVED** [review]
Well isn't that special :-/

**Comment by nrwahl2** [comment]
@kgaillot Yeah, the basic issue is that the bundle replica's container (or remote, I forget which) is what gets considered when we apply colocations. However, the child is the promotable clone, and each instance runs on one of the container nodes.

So when we're considering promoted roles, we're looking at things that aren't promotable. There's some kind of special case that we hit for the `bundle-promoted-colocation-1` case (primary promoted bundle, dependent primitive, mandatory).

**Comment by nrwahl2** [comment]
Updated to fix failures... IDK how I had built against older source code but the outputs match CI after rebuilding. Still wrong though :)

**Comment by nrwahl2** [comment]
This is tough, huh... Since the container gets assigned before the child, we won't know the child's next role.

**Pull request merged**
