### PR TITLE
Doc: add documentation for new pcmk_delay_base

### PR DESCRIPTION
**Pull request by wenningerk**

### CODE REVIEW

**Comment by jnpkrn** [comment]
We should perhaps figure out if there are better ways of dealing
with the translation files going forward.  For a start, I've added
a suggestion (last point) to possible improvements at the release
checklist wiki page:
https://wiki.clusterlabs.org/wiki/Pacemaker_Release_Checklist#Possible_improvements

**Comment by wenningerk** [comment]
Having to add more or less the same description 3 times is definitely suboptimal - not just from the pot-perspective ;-)

**Comment by kgaillot** [comment]
It's actually not necessary to maintain the.pot files at all, because we don't have any active translators at the moment.

I don't think we'll have the user base in the foreseeable future to keep a translation maintained, especially considering that the translation only affects certain documentation, not any messages from the code itself, which would be more problematic to translate since log files need to be usable by various companies' support departments.

**Comment by wenningerk** [comment]
had a look at the recent changes - so it seemed to be maintained ;-)

**Comment by kgaillot** [comment]
Nope, coincidental :) I update them at the start of each release cycle, because "make pot" is easy enough

**Pull request merged**
