### PR TITLE
Bundle fixes

### PR DESCRIPTION
**Pull request by kgaillot**

### CODE REVIEW

**Comment by kgaillot** [comment]
@vvidic , I couldn't tell from the rkt run man page whether it will support the "Z" mount flag (see the 2nd commit here). Would you mind reviewing/testing this for rkt compatibility? The scenario here is when SELinux is enabled on the host, it prevents the container from writing to its /var/log mount.

**Comment by vvidic** [comment]
It does not seem like it will work with the new options:
```
Error: invalid argument "logs,kind=host,source=/var/log,rw,Z" for "--volume" flag: 
invalid value in --volume flag "logs,kind=host,source=/var/log,rw,Z": 
malformed string "name=logs,kind=host,source=/var/log,rw,Z" - has a label without a value: rw
```
So maybe skip this options if the container type is rkt?

**Comment by kgaillot** [comment]
@vvidic , thanks for the test. If I stick with this approach, I'll skip the new option for rkt.

However on further investigation, I'm going to see if this can be fixed in the selinux-policy project rather than here. It seems that with older versions of selinux-policy, containers could write to files labeled with var_log_t, but not with newer versions, so it may make more sense to adjust the labeling there.

The other commits here still make sense, and I'll continue with them once that issue is settled.

**Comment by kgaillot** [comment]
Updated PR:
- "Z" is not added for rkt
- "Z" is not added unless/until the DC supports the new code (avoids changing regression tests, and ensures crm_simulate etc. will work regardless of node)

**Comment by kgaillot** [comment]
After discussing with selinux-policy experts, I decided to keep the change in pacemaker rather than there. Their recommendation was for pacemaker to create a custom policy for this purpose, and supply it in a new pacemaker-selinux package. I felt the method here was less intrusive since we'd want the policy installed by default, but we can't depend on selinux-policy b/c not all users are on systems with SELinux. The method here is also more surgical, allowing each specific container to access only its own logs.

The only downside of doing it in pacemaker is that the implicit resource definition changes, thus all active bundles will be restarted once all nodes are upgraded to a version with this code.

**Comment by kgaillot** [comment]
I pulled out the commit with the SELinux change, as the rest are all ready to be merged now. I'll do a new PR with the SELinux commit.

**Pull request merged**
