### PR TITLE
[WIP] schema 3.0 work

### PR DESCRIPTION
**Pull request by jnpkrn**
First commit deals with newly discovered technical debt in form of
discrepancy between what parser expects and what can effectively
reach it due to forgotten propagation of new features into regular schema.
This should go also to the next 1.x version for which I'll send a separater
PR.

### CODE REVIEW

**Comment by kgaillot** [comment]
I've asked the mailing list for feedback on whether anyone has used or tested the feature, but we definitely don't want to back-propagate it to previous schemas. First, it was not an oversight -- it was left in -next until the requesting users could thoroughly test it, which apparently never happened. Second, the versioned schemas are intended to stay invariant.

We can proceed depending on the list feedback. If the feature is still untested, we can close this request, and I'll update validate-with in the few regression tests that I mistakenly bumped to -1.2 instead of -next when dropping the -1.1 alias.

**Comment by kgaillot** [comment]
Based on the list feedback so far, I'd say the feature should be killed:

* The most appealing use case to users is assigning one IP to the master instance of a stateful clone, and a pool of IPs to the slave instances. This syntax doesn't support that.
* This syntax does not make clear (or enforce) what the bounds of the instance numbers are.
* This syntax implies that particular instances can be identified uniquely, which is not the case (the instance numbers are purely internal to pacemaker, and have no relation to user-visible information such as nodes, roles, etc.).
* This syntax allows constraining only some of a clone's instances, which is at a minimum confusing and more likely dangerous.

I think current syntax adequately handles most intended use cases -- just colocate the resources with the clone (and role if desired), then anti-colocate with each other. For example, to colocate three IP resources with the instances of a clone:

      <rsc_colocation id="coloc1" score="INFINITY" >
         <resource_set id="coloc1-set1" sequential="false">
           <resource_ref id="ip1"/>
           <resource_ref id="ip2"/>
           <resource_ref id="ip3"/>
         </resource_set>
        <resource_set id="coloc1-set2" sequential="true">
          <resource_ref id="clone1"/>
        </resource_set>
      </rsc_colocation>

      <rsc_colocation id="coloc2" score="-100" >
        <resource_set id="coloc2-set1" sequential="true">
          <resource_ref id="ip1"/>
          <resource_ref id="ip2"/>
          <resource_ref id="ip3"/>
        </resource_set>
      </rsc_colocation>

role can be added to the resource_set to colocate with the slave instances of a stateful clone.

That approach does not support colocating the clone instances with a set of primitive resources, so we can leave the code intact for now, with the possibility of adding a better syntax for that if there is demand for it.

**Comment by jnpkrn** [comment]
That was sort of my point, to provoke some kind of action about this,
removing dead code (under 99.9% of use cases) is also a good outcome.

**Comment by jnpkrn** [comment]
ML thread for reference:
http://oss.clusterlabs.org/pipermail/users/2018-January/014295.html

**Pull request closed without merging**
