### PR TITLE
Build: utilize PKG_CHECK_VAR macro + related cleanup

### PR DESCRIPTION
**Pull request by jnpkrn**

### CODE REVIEW

**Comment by kgaillot** [comment]
PKG_CHECK_VAR was introduced in pkg-config 0.28. Even RHEL 7.2 only has 0.27.1, and we need to support much older than that.

**Comment by jnpkrn** [comment]
Haven't realized that and would be nice if travis was sane enough to send failure emails to authors also on PRs.  Added a commit supplying the missing macro.

**Comment by jnpkrn** [comment]
Hmm, RHEL 6 complains about missing `AS_VAR_COPY` if it concerns us.

**Comment by jnpkrn** [comment]
That being said, RHEL 7 is fine with the last commit.

**Comment by kgaillot** [comment]
> Hmm, RHEL 6 complains about missing AS_VAR_COPY if it concerns us.

I would like to continue supporting compiling upstream on RHEL 6, even though RHEL 6 itself will never distribute a newer version. Also, RHEL 6 is a good measure for older software versions still in wide use.

**Comment by jnpkrn** [comment]
Ok, will expand those new AS_* macros manually.

**Comment by jnpkrn** [comment]
Now it passes there as well.

**Comment by kgaillot** [comment]
Are there any potential issues from colliding with the built-in PKG_CHECK_VAR (whether now or if the built-in changes in the future)? Should we use PCMK_PKG_CHECK_VAR to make it clear we're defining our own?

**Comment by jnpkrn** [comment]
Based on your suggestion, I've made the local macro conditionally defined only if not present in the system.  That's deemed a pretty stable API element (owing to its naturally imposed long-term supportability) that can only get more sophisticated internally (in which case we'd benefit from such update if available in the system) or decommissioned (unlikely), not changed radically.

**Pull request merged**
