### PR TITLE
Build: explicitly allow skipping Publican building docs and sanitize docs building as such

### PR DESCRIPTION
**Pull request by jnpkrn**
There are cases one wants to avoid Publican being involved in the build
process at all (for instance, if a local copy is too old to behave
gracefully with what build process requires).

We avoid introducing a new configure option by (sort of) overloading
--with-brand one.

See also rhbz#1326350 (instructing configure using --with-brand=
would then help).

### CODE REVIEW

**Comment by kgaillot** [comment]
Would this help the rpmbuild use case?

I think I'd rather (or in addition) omit --brand_dir whenever publican doesn't support it. We could test for that in either configure or the makefile.

**Comment by jnpkrn** [comment]
On 12/04/16 08:47 -0700, Ken Gaillot wrote:
> Would this help the rpmbuild use case?
> 
> I think I'd rather (or in addition) omit --brand_dir whenever
> publican doesn't support it. We could test for that in either
> configure or the makefile.

There's no mutual exclusion.  Let's say the proposed commit is just
a first step bringing an ability to order "don't bother with the docs
(I can read at clusterlabs.org, anyway)", which feels quite natural.

I'll add the second step per your suggestion: check whether Publican
is able to deliver the intended customizations, and skip building that
just as when avoided manually if not.

Both additional handlings have their use cases, I am sure
(some distros would be OK just with the one I started with).

-- 
Jan (Poki)

**Comment by jnpkrn** [comment]
Do not pull yet, test in a context of rhbz#1326350 pending.

**Comment by jnpkrn** [comment]
Note that the last commit retains the idea of the first one in the PR, i.e., one should specify --with-brand= to configure if Publican docs should not be generated for sure (e.g., they would be unused anyway).

**Comment by jnpkrn** [comment]
Can be pulled now if there are no more comments.
Beside EL6 successful building with Publican docs prerequisites
installed (rhbz#1326350), one can now (thanks to the last commit):
```
rpmbuild --without-doc --rebuild pacemaker.src.rpm
|| rpmbuild --define "_without_doc 1" --rebuild pacemaker.src.rpm
```

**Pull request merged**
