### PR TITLE
Fix: libcrmcommon: avoid file descriptor leak in IPC client with async connection

### PR DESCRIPTION
**Pull request by gao-yan**
Previously if qb_ipcc_connect_async() succeeded but the following poll()
failed, the file descriptor would leak.

In that case, given that disconnect function is not registered yet,
qb_ipcc_disconnect() won't clean up the socket. In any case, call
qb_ipcc_connect_continue() here so that it may fail and do the cleanup
for us.

Issue introduced in 2.1.3 by 4b60aa100.

### CODE REVIEW

**Comment by gao-yan** [comment]
Let's take a look if it makes sense. I'm meanwhile asking the user to try it out.

**Review by kgaillot — COMMENTED** [review]
Makes sense to me

**Comment by gao-yan** [comment]
Will ask the user to try this out instead.

**Review by kgaillot — APPROVED** [review]
Looks good to me. I'll wait to hear if the user is happy before merging

**Comment by gao-yan** [comment]
@kgaillot, the user gave positive feedback about this.

**Pull request merged**
