### PR TITLE
pengine: Allow use of resource meta params in location rules

### PR DESCRIPTION
**Pull request by bubble75**
This would allow following syntax (in crmsh terms):

location resource-require-home-zone /resource-.+/ \
    rule -inf: not_defined zone or zone ne meta{zone}

### CODE REVIEW

**Comment by kgaillot** [comment]
This is an interesting idea. If I understand right, this adds flexibiity to the (relatively) new rsc_pattern feature. Similarly-named resources could use a single location constraint, but the effect would differ depending on how a particular resource parameter matched a particular node attribute.

A couple of observations:

* Why look only for meta-attributes? I would think regular parameters would be more useful. For example, there is no "zone" meta-attribute. Are you using meta-attributes as a way to introduce administrative information across different resource agents? I hadn't considered such usage before.

* The syntax feels inconsistent with existing Pacemaker conventions. I'm not sure what would be better. Maybe something comparable to "#" for built-in special node attributes, like "$" for resource instance attributes and "$$" for resource meta-attributes: zone ne $$zone

**Comment by bubble75** [comment]
> Similarly-named resources could use a single location constraint, but the effect would differ depending on how a particular resource parameter matched a particular node attribute.

Exactly. Also, usage is not limited to rsc-pattern, any location with rsc will work too.

> Why look only for meta-attributes?

Well, IMHO attributes which are used as hints to resource placement only are strict meta ones. And they do not require to be listed in RA metadata (and do not need to be synchronized between different RAs, if rsc-pattern covers resources with different RAs under them). Anyways, match on resource params can be added easily.

> For example, there is no "zone" meta-attribute.

Unless you define one ;) crmsh adds some restrictions to what meta-attributes could be defined. But not pacemaker itself. I asked Andrew many years ago and iirc he answered that was intentional.

> Are you using meta-attributes as a way to introduce administrative information across different resource agents?

Meta-information you meant? Yes, don't they exist for exactly that?

> "$" for resource instance attributes and "$$" for resource meta-attributes: zone ne $$zone

From 40000ft both params and meta-attributes are just associative arrays. array{member} syntax fits that paradigm well. $$ looks to cryptic for me, I'd avoid dropping array (hash) name. Probably $param{name} and $meta{name}?  Or with any other leading symbol (~!@#$%&*)? Shouldn't we bring that to a wider audience?

**Comment by kgaillot** [comment]
> For example, there is no "zone" meta-attribute.
> 
> Unless you define one ;) crmsh adds some restrictions to what meta-attributes could be defined. But not pacemaker itself. I asked Andrew many years ago and iirc he answered that was intentional.
> 
>     Are you using meta-attributes as a way to introduce administrative information across different resource agents?
> 
> Meta-information you meant? Yes, don't they exist for exactly that?

Meta-attributes are intentionally arbitrary name-value pairs, but I was only aware of their use by pacemaker itself. It makes sense to allow administrators to use them as well for information not specific to the RA, but I'd be concerned about the possibility for name collisions (i.e. if pacemaker one day adds a meta-attribute that someone is already using locally). Perhaps we could establish (and document) a convention that pacemaker will never use a meta-attribute starting with a particular string (e.g. "user-").

**Comment by kgaillot** [comment]
> "$" for resource instance attributes and "$$" for resource meta-attributes: zone ne $$zone
> 
> From 40000ft both params and meta-attributes are just associative arrays. array{member} syntax fits that paradigm well. $$ looks to cryptic for me, I'd avoid dropping array (hash) name. Probably $param{name} and $meta{name}? Or with any other leading symbol (~!@#$%&*)? Shouldn't we bring that to a wider audience?

Looking at it again, two things occur to me: the value is currently free-form, so there is no syntax that would be reliably distinguishable from a literal value; and we are dealing with XML, so information should be structured properly rather than interpreting the value, whenever practical.

Perhaps we could add a "value-type" property to expressions, with the possible values "literal" (the default), "parameter" or "meta". For example, in the CIB:

    <rule id="dont-run-apache-rule" score="-INFINITY">
      <expression id="dont-run-apache-expr" attribute="#uname"
        operation="eq" value="c00n03" value-type="literal" />
    </rule>

or:

    <rule id="dont-run-apache-rule" score="-INFINITY">
      <expression id="dont-run-apache-expr" attribute="#uname"
        operation="eq" value="zone" value-type="meta" />
    </rule>

Higher-level tools could of course use any syntax they want to simplify it for the user.

**Comment by bubble75** [comment]
That requires rule.rng modifcation. I'm not sure what is better to do with that file. It is not referenced directly by pacemaker*.rng, but rather by constraints*.rng and nvset*.rng. Should I bump latter two and include new rule-2.8.rng there?

**Comment by kgaillot** [comment]
> That requires rule.rng modifcation. I'm not sure what is better to do with that file. It is not referenced directly by pacemaker*.rng, but rather by constraints*.rng and nvset*.rng. Should I bump latter two and include new rule-2.8.rng there?

Correct. Copy the current latest constraints/nvset/rule files to *-2.8.rng, and update the exetrnalRef to use rule-2.8.rng explicitly in constraints and nvset. It would be nice if we pulled in the latest rule*.rng automatically, but it doesn't currently.

**Comment by bubble75** [comment]
Still not sure. Proposed change is about 'rsc_location' only. But rules are used in both it (constraints.rng) and in properties/rsc params/etc (nvset.rng). Wouldn't it be better to fork rule.rng into location-rule-2.8.rng and include it from constraits-2.8.rng, leaving nvset* as is?

**Comment by kgaillot** [comment]
Our policy has been to keep the rule schema the same for constraints and nvset, even if not all possibilities are meaningful everywhere it can be used. For example, 'score' also only applies to rules in location constraints, and it is silently ignored everywhere else. As long as we document where each possibility is meaningful, I think we're fine.

BTW since we already have 'type' to define the value's data type, 'value-type' may be confusing, so let's use something else, maybe 'from' or 'source'.

**Comment by bubble75** [comment]
Update the commit with suggested changes (but with original 'value-type' until we have a better name).

**Comment by kgaillot** [comment]
Looking better. I just noticed some important issues:

* I'm not sure what lib/pengine functions, if any, are part of the public API. I'm investigating that and will comment here once I have the answer. If pe_test_rule_re() etc. are part of the public API, we'll have to preserve backward compatibility -- the usual approach is to add a new function with the new arguments, and make the old function a wrapper for it.

* lib/pengine defines two separate libraries, libpe_rules and libpe_status. libpe_rules is the smaller of the two and is designed to be usable without libpe_status, so rules.h should't include status.h (needed for the resource_t definition). I'm thinking the rule functions could take arguments for the two parameter hashtables instead of the resource.

* That brings up a question about this code:

    while (rsc && rsc->variant > pe_native) {
        rsc = rsc->parent;
    }

What is the intent of that? I don't think it will work as-is. It would only be used if a higher-level type such as group were inside another higher-level type such as a clone, but it would always end up with rsc==NULL.

**Comment by bubble75** [comment]
- public API - Unfortunately yes, but they were introduced in b5df1578 (2016-06-16). If you wish, I'll do the same thing as there - introduce pe_test_rule_re_rsc() and pe_test_expression_re_rsc(). That becomes hardly readable though...

- two parameter hashtables. Well, seven function arguments is usually a sign of the upcoming redesign ;)

- (rsc && rsc->variant > pe_native) Intention was to traverse clones/ms back to primitive with no groups in mind.
Probably it should be changed to (rsc && (rsc->variant == pe_clone || rsc->variant == pe_ms))

**Comment by kgaillot** [comment]
> public API - Unfortunately yes, but they were introduced in b5df157 (2016-06-16). If you wish, I'll do the same thing as there - introduce pe_test_rule_re_rsc() and pe_test_expression_re_rsc(). That becomes hardly readable though...

We haven't documented any of the PE library functions, but they are in public headers, so better safe than sorry I guess. b5df157 was included in the 1.1.16 release.

As far as name, probably not much can be done -- in similar situations, we've used e.g.  pe_test_rule_re_full() to indicate that it has more arguments, but that's not much better.

> two parameter hashtables. Well, seven function arguments is usually a sign of the upcoming redesign ;)

It would be abusing the purpose, but if we add them to the end of pe_re_match_data_t, we wouldn't need a new function or args. The params and match data are always needed together, so it's not a total stretch, though dubious. A separate function is probably clearer, even with a long name and args.

> (rsc && rsc->variant > pe_native) Intention was to traverse clones/ms back to primitive with no groups in mind.
> Probably it should be changed to (rsc && (rsc->variant == pe_clone || rsc->variant == pe_ms))

It's the other way around: the clone/ms is the primitive's parent. I don't think we need to worry about it, though. People could want to match meta-attributes of the primitive or its clone -- it's up to them to specify which one they want. At most, I could see making a new table combining the primitive's parameters with all of its ancestors', but we can leave it alone for now, and see how people actually use it.

**Comment by bubble75** [comment]
> if we add them to the end of pe_re_match_data_t 

That would introduce memory access issues when client is built against an older API and runs with a newer lib (which wants to check that fields at the end).

I would rather think about embedding pe_re_match_data_t into the new pe_match_data_t as 're' and use memcpy in pe_test_rule_re() from pe_re_match_data_t into pe_match_data_t.re (pe_match_data_t would be statically allocated there) and then calling new pe_test_rule_full() with address of that pe_match_data_t.

**Comment by kgaillot** [comment]
> if we add them to the end of pe_re_match_data_t
> 
> That would introduce memory access issues when client is built against an older API and runs with a newer lib (which wants to check that fields at the end).

Actually that's the advantage of adding it at the end -- it's API-compatible.

Any application compiled using the older header but dynamically linked against the newer library will be fine. The application itself won't (and can't) use the new fields directly, but the library will still allocate, populate, and utilize the new struct (the library code itself was compiled with the new header).

That's why we always add new fields at the end of public structs.

The main question here is whether that abuses the intent of the struct too much.

**Comment by bubble75** [comment]
> library will still allocate

That is not the case. pengine has it statically allocated f.e.

**Comment by kgaillot** [comment]
> library will still allocate
> 
> That is not the case. pengine has it statically allocated f.e.

Sure, but the cluster daemons and tools will always be built with the header and libraries provided with that version. We don't support mixing and matching versions among individual pacemaker components. The only concern is software outside pacemaker that builds against the libraries (sbd being the only one that I think is fairly common, but anyone could write their own).

**Comment by bubble75** [comment]
I meant third-party applications actually.

After some thinking I'd make that new pe_match_data_t an argument to pe_test_rule_full(). pe_match_data_t would have ->re of type pe_re_match_data_t* (and two hashtables), and pe_test_rule_re() would have statically allocated pe_match_data_t, sets pe_match_data_t->re to its  pe_re_match_data_t and then calls pe_test_rule_full(pe_re_match_data_t). That way we do not have much mess.

**Comment by kgaillot** [comment]
> I meant third-party applications actually.
> 
> After some thinking I'd make that new pe_match_data_t an argument to pe_test_rule_full(). pe_match_data_t would have ->re of type pe_re_match_data_t* (and two hashtables), and pe_test_rule_re() would have statically allocated pe_match_data_t, sets pe_match_data_t->re to its pe_re_match_data_t and then calls pe_test_rule_full(&pe_re_match_data_t). That way we do not have much mess.

You know, I've been following the "add-to-the-end" rule without really thinking about it. It's only sufficient when we hide the struct definition from external applications and provide new/free methods, which we rarely do. :-( Your approach is reasonable.

**Comment by bubble75** [comment]
Updated commit with suggested compatibility changes. Tested to compile only.

**Comment by kgaillot** [comment]
Looks great. Rename value-type (maybe value-source?) and let me know how testing goes, and we can merge it.

**Comment by bubble75** [comment]
Shouldn't I also prepend 'meta' and 'params' with 'rsc_'?

**Comment by kgaillot** [comment]
I think resources are the only relevant objects that will have parameters and meta-parameters, so I'd rather the simplicity of leaving it off.

Operations have them, but they wouldn't make sense in this context -- at least not without also specifying a particular operation name and interval, and that seems overkill. I don't see that being a real-world use case.

**Comment by bubble75** [comment]
Pushed updated commit, tested to work correctly.

**Comment by kgaillot** [comment]
Great, thanks!

**Comment by kgaillot** [comment]
FYI I'm going to bump the XML schema changes here to 2.9, to be able to distinguish this support from 2.8 bundle support.

**Pull request merged**
