### PR TITLE
Support "sync-crash" option with PCMK_panic_action

### PR DESCRIPTION
**Pull request by inouekazu**
This is a supplement to https://github.com/ClusterLabs/pacemaker/pull/2344.
I think some users want both log and kernel dump, but what about?

### CODE REVIEW

**Comment by wenningerk** [comment]
Nothing I'd basically oppose.
Just wanted to give a heads-up that if we are seeing more additions to come we might consider a composition out of comma-separated values. E.g. compare with what I've done with timeout-action in sbd
Just to prevent the 2^n number of comparisons ... which might become relevant when thinking of something like a delay on top ...
like: PCMK_panic_action=sync,delay,crash (or sync,halt ...)
atm there would still be time to take back sync-reboot if we see something like the above coming.

**Comment by kgaillot** [comment]
> Nothing I'd basically oppose.
> Just wanted to give a heads-up that if we are seeing more additions to come we might consider a composition out of comma-separated values. E.g. compare with what I've done with timeout-action in sbd
> Just to prevent the 2^n number of comparisons ... which might become relevant when thinking of something like a delay on top ...
> like: PCMK_panic_action=sync,delay,crash (or sync,halt ...)
> atm there would still be time to take back sync-reboot if we see something like the above coming.

That's a good point. However I think if we need to, we can do the same with dashes (e.g. sync-delay-crash) and parse it rather than compare each possible combination.

**Comment by wenningerk** [comment]
> That's a good point. However I think if we need to, we can do the same with dashes (e.g. sync-delay-crash) and parse it rather than compare each possible combination.

Speaking an agglutinative language as mother tongue I always feel the dash in English as a replacement. Maybe that is the reason why using a comma to compose several flags with free order feels more natural for me. From my memory I can recall a number of cases where a comma separated list is used in that way but none where it is done with a dash.
As long as we stay with these 2 the dash definitely is better looking. Just wanted to raise the point while we haven't really introduced the dash + consistency as we've gone the comma-way already once for something very similar.

**Comment by wenningerk** [comment]
> Hopefully no one will want a delay and we won't have to worry about it ;)

And if we could still allow both separators finally.

**Pull request merged**
