### PR TITLE
Build: configure: Use AS_IF and AS_CASE everywhere.

### PR DESCRIPTION
**Pull request by clumens**
Fixes T389

### CODE REVIEW

**Comment by clumens** [comment]
I haven't tested this beyond making sure a mock build still works and looking at everything a couple times to make sure it looks good.

Other things we could do either in this PR or a separate one...
* I noticed a reference to Darwin, which we could probably get rid of.
* There are various places that don't use the `x$whatever == x"whatever"` syntax.  Those should be changed.
* Perhaps be more consistent with formatting.

**Review by kgaillot — COMMENTED** [review]
At this rate, soon it will look like we know what we're doing ;)

> I noticed a reference to Darwin, which we could probably get rid of.

Yep, a long time ago, we supported building on OS X. I doubt it would build currently, but there's no harm in leaving it in case someone tries.

> There are various places that don't use the x$whatever == x"whatever" syntax. Those should be changed.

I'm not sure what's considered best practice, hopefully the autotools documentation mentions it somewhere. Ancient shells couldn't handle `[` without `test`, or comparing against `""`, but I doubt anything like that even exists anymore.

> Perhaps be more consistent with formatting.

Wouldn't hurt :) but I'm less concerned simply because configure.ac syntax is awkward and whatever spacing makes it more readable is fine.

**Comment by clumens** [comment]
> > There are various places that don't use the x$whatever == x"whatever" syntax. Those should be changed.
> 
> I'm not sure what's considered best practice, hopefully the autotools documentation mentions it somewhere. Ancient shells couldn't handle `[` without `test`, or comparing against `""`, but I doubt anything like that even exists anymore.

The autotools documentation is still recommending doing the X"" trick - 
https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.71/html_node/Limitations-of-Builtins.html and look for "test (strings)".

**Comment by kgaillot** [comment]
retest this please

**Comment by kgaillot** [comment]
Thanks!

**Pull request merged**
