### PR TITLE
Crm mon add fence history master

### PR DESCRIPTION
**Pull request by wenningerk**
collection of minor issues found with crm_mon

### CODE REVIEW

**Comment by kgaillot** [comment]
Interesting, I didn't realize --as-xml overrides --daemonize. This change is fine since it's consistent with that behavior, but I wonder if there might be a legitimate use case for auto-updated XML output. I suppose we can wait for someone to ask for it.

**Comment by wenningerk** [comment]
--as-xml sets --one-shot which supersedes --daemonize
and it doesn't use an output-file as --as-html would - so where would the daemon write to.
atm it actully just fixes the error-output
thought of a way to make it work - either an option to enforce continuous-mode or something like --as-xml-file that would behave like --as-html

**Comment by kgaillot** [comment]
Yep, definitely don't need to do anything about it right now.  A while back I had thought about it and came up with an idea for two new options:

--as/-a=(cgi|html|xml|monitor|plain|console|none) (default console)
--output/-O=(FILE|stdout) (default stdout)

Existing options would become deprecated aliases like:

        --as-xml = --as=xml
        --as-html FILE = --as=html --output=FILE
        --web-cgi = --as=cgi
        --disable-ncurses = --as=plain
        --simple-status = --as=monitor

**Comment by wenningerk** [comment]
Sounds like a good idea.
Could do it together with the more systematic output specification that makes the up-to-now config-parameters aliases of the new systematic specification. Basically a similar approach so would somehow fit if they are coming together.

**Pull request merged**
