### PR TITLE
Rearrange pacemaker-attrd in preparation for IPC work

### PR DESCRIPTION
**Pull request by clumens**

### CODE REVIEW

**Comment by kgaillot** [comment]
This looks good overall.

I'm not sure you want the "Move IPC-related message handlers" and "Move CPG-related message handlers" commits because those are going to be combined together for `pcmk__request_t`. E.g. attrd_peer_update() and attrd_client_update() will be a single update handler. However if your plan is to have a new update handler as a small wrapper that just does "if (peer) attrd_peer_update() else attrd_client_update()" then your approach here could work.

The "new attrd_attributes.c" commit by itself would actually make a great attrd_cib.c without anything else moved into it, since all of that is related to writing attributes to the CIB. The other stuff could still be a new attrd_attributes.c. The mainloop_timer_add() for attribute_timer_cb() looks like a good opportunity for functionization.

Ideally anything that goes from static to not would get "attrd_" in front of it. (Anything that gains static could drop "attrd_" but that matters less.)

**Comment by clumens** [comment]
> I'm not sure you want the "Move IPC-related message handlers" and "Move CPG-related message handlers" commits because those are going to be combined together for `pcmk__request_t`. E.g. attrd_peer_update() and attrd_client_update() will be a single update handler. However if your plan is to have a new update handler as a small wrapper that just does "if (peer) attrd_peer_update() else attrd_client_update()" then your approach here could work.

I think the small wrapper and then specialized message handler approach would be good.  It'd make for smaller source files and less indentation.  But, I'm hoping all these daemons will end up with very similar looking functions.  So, whatever I do here, I'd like it to be as close as possible to whatever the other daemons have.

> The "new attrd_attributes.c" commit by itself would actually make a great attrd_cib.c without anything else moved into it, since all of that is related to writing attributes to the CIB. The other stuff could still be a new attrd_attributes.c. The mainloop_timer_add() for attribute_timer_cb() looks like a good opportunity for functionization.

Would you then have attrd_attributes.c that does the misc. stuff, attrd_cib.c that does the CIB writing, and also attrd_corosync that does the CPG stuff?  I think that makes sense to me.

I have not yet taken a look at any ways to functionalize stuff here, but perhaps I should do that before the next wave of patches that starts to do the actual IPC work.

> Ideally anything that goes from static to not would get "attrd_" in front of it. (Anything that gains static could drop "attrd_" but that matters less.)

Yeah, definitely.  I'll take a look at this once we have the files figured out.

**Comment by kgaillot** [comment]
> Would you then have attrd_attributes.c that does the misc. stuff, attrd_cib.c that does the CIB writing, and also attrd_corosync that does the CPG stuff? I think that makes sense to me.

Yes, that sounds reasonable.

> 
> I have not yet taken a look at any ways to functionalize stuff here, but perhaps I should do that before the next wave of patches that starts to do the actual IPC work.

I only mentioned that one b/c it would let attribute_timer_cb() stay static. No need to spend time on refactoring the code in general.

**Comment by clumens** [comment]
The "Replace a call to attrd_client_update" patch is no longer necessary, dropping.

**Comment by kgaillot** [comment]
Whew!

**Pull request merged**
