### PR TITLE
Fix Pacemaker config directory on deb based systems.

### PR DESCRIPTION
**Pull request by koponomarenko**

### CODE REVIEW

**Comment by kgaillot** [comment]
Thanks for bringing up this issue. Looking at it some more, other systems may need /etc/default/pacemaker.d, /etc/conf.d or whatever. I think I'd rather use configure.ac to detect the local convention and define a macro for use in pacemaker.service.in. Then people can submit configure.ac patches for their OS and not keep growing the systemd unit file.

If you don't want to handle the configure.ac changes, I can do it.

**Comment by koponomarenko** [comment]
No problem. I am interested in doing this change, but my auto-tools knowledge is very humble. But I see this as a good opportunity to learn. If I understand you correct, this "sysconfig" directory should be detected in configure.ac and based on the result the proper replacement of it should be done. 
I decided to check this directory presence as it was done in pacemakers init script.
Please point me to mistakes I should fix if any. Thank you.

**Comment by kgaillot** [comment]
Investigating further, I found that checking directory existence is not sufficient. My CentOS system has an /etc/default directory, and Fedora decided to let packages use /etc/default if upstream does (https://fedorahosted.org/fpc/ticket/152). I would guess the same sort of problem occurs for other distros, particularly when installing "alien" packages.

Perhaps we can add a --with-configdir argument that defaults to /etc/sysconfig, so users can specify /etc/default on the command line when appropriate. Trying to detect the right value dynamically seems too complicated, and people are already used to using --with-* to specify distro-specific directory locations.

**Comment by koponomarenko** [comment]
Hello Ken! I made changes according to your suggestion. Is it good now? =)

Also, I did grep by "@sysconfdir@/sysconfig" and it looks like there are a lot of places in the code in which it just checks for "/etc/default" dir. Waiting for your comments.

**Comment by kgaillot** [comment]
Yes, perfect! This will be a convenient feature.

Agreed, there are many more places that can use the new variable, but it's not necessary to do that right now.

One last request: I just noticed this was submitted against the master branch. We're in the middle of the 1.1.15 release cycle, and this should be in the release, so please close and resubmit against the 1.1 branch.

**Comment by koponomarenko** [comment]
Nice! Will do it right now.

**Pull request closed without merging**
