### PR TITLE
Pkgconfig

### PR DESCRIPTION
**Pull request by rubenk**

### CODE REVIEW

**Comment by kgaillot** [comment]
Thank you for these pull requests -- they're much appreciated.

We are currently in the middle of the release cycle for Pacemaker 1.1.14. These changes are small enough that I would be happy to include them in the release; if you want to do so, please resubmit these requests against the 1.1 branch instead of the master branch. (Once the 1.1.14 final release comes out, likely in early January, we'll go back to taking all requests against the master branch.)

**Comment by rubenk** [comment]
Thanks for your fast response! I'm not in a hurry so it's fine with me if these patches miss 1.14. I've got a few more coming up anyway :)

**Comment by kgaillot** [comment]
Sure. If you change your mind, it's as easy as closing the request, changing the branch dropdown, and reopening :)

**Comment by rubenk** [comment]
In that case, let's do that :)

**Pull request closed without merging**
