### PR TITLE
Log: based: Fix CIB version values

### PR DESCRIPTION
**Pull request by nrwahl2**
939a408c, 8e9e6642, and 618e77d7 caused the CIB version attribute values to get fetched too early in `cib_process_request()`. `cib_process_command()` can change them.

This resulted in corruption (probably affecting only logging) after some commands, with garbage values being logged. For example:
```
info: Completed cib_modify operation for section nodes: OK (rc=0, origin=laptop/crmd/4, version=<81>rcT.!^K9^H<9d>U.1^K9^H<9d>U)
```

We need to fetch the values after `cib_process_command()`. Here we do it immediately before use.

### CODE REVIEW

**Comment by clumens** [comment]
This fixes the problem for me.

**Review by kgaillot — COMMENTED** [review]
Looks good, but I believe the commits did something similar elsewhere

**Comment by kgaillot** [comment]
Also, these values should always be set in the live CIB, but to be extra safe let's use `pcmk__s()` when using them

**Comment by nrwahl2** [comment]
> elsewhere

All I see is `process_ping_reply()`, and there's no intervening code in that case.

> pcmk__s()

Good point

**Review by kgaillot — APPROVED** [review]

**Pull request merged**
