### PR TITLE
A few small changes

### PR DESCRIPTION
**Pull request by kgaillot**

### CODE REVIEW

**Comment by kgaillot** [comment]
@nrwahl2 , can you review this when you get a chance? Low priority

**Comment by clumens** [comment]
There's also one in cts/lab/patterns.py to fix:
```
diff --git a/cts/lab/patterns.py b/cts/lab/patterns.py
index 1e67039a9..f5ac87d50 100644
--- a/cts/lab/patterns.py
+++ b/cts/lab/patterns.py
@@ -32,7 +32,7 @@ class BasePatterns(object):
             "CibDelXpath"    : "cibadmin --delete --xpath %s",
             # 300,000 == 5 minutes
             "RscRunning"     : BuildOptions.DAEMON_DIR + "/cts-exec-helper -R -r %s",
-            "CIBfile"        : "%s:" + BuildOptions.CONFIG_DIR + "/cib.xml",
+            "CIBfile"        : "%s:" + BuildOptions.CIB_DIR + "/cib.xml",
             "TmpDir"         : "/tmp",
 
             "BreakCommCmd"   : "iptables -A INPUT -s %s -j DROP >/dev/null 2>&1",
```

**Comment by nrwahl2** [comment]
What's wrong with using the `<version>` tag to check for 1.1 support?

Related, do we have a file (e.g., a Changelog) that shows the differences between 1.0 and 1.1? It may have been summarized via email but I don't see one in the OCF-spec repo.

**Review by nrwahl2 — APPROVED** [review]
Looks good to me

**Comment by kgaillot** [comment]
> There's also one in cts/lab/patterns.py to fix:

Whoops, thanks

**Comment by kgaillot** [comment]
> What's wrong with using the `<version>` tag to check for 1.1 support?

Nothing, it would be a decent heuristic as well, but someone could update an agent to OCF 1.1 without updating the validate-all action to handle OCF_CHECK_LEVEL since it's an optional feature. If they specifically mark the metadata with depth="0", they are at least claiming to have done it.

> 
> Related, do we have a file (e.g., a Changelog) that shows the differences between 1.0 and 1.1? It may have been summarized via email but I don't see one in the OCF-spec repo.

No, that might be worthwhile to add to the repo. We do have https://wiki.clusterlabs.org/wiki/Update_Resource_Agent_for_OCF_1.1

**Comment by kgaillot** [comment]
Updated top commit to add patterns.py change

**Pull request merged**
