### PR TITLE
Build: fix compilation -Werror compilation issue with GCC 10 with s390x

### PR DESCRIPTION
**Pull request by jnpkrn**
More a preview now, will test on Thu.

### CODE REVIEW

**Comment by jnpkrn** [comment]
There will be more fun.

**Comment by kgaillot** [comment]
Do you want to merge this part now or wait for further developments?

**Comment by jnpkrn** [comment]
Added more complete description of the current state to the
fixing commit, also explaining why more effort does not
immediately follow (we have a workaround for the building
scenario at hand).

Can be merged when OK'd.

**Comment by jnpkrn** [comment]
Actually, documented one more effect the former commit has.

**Pull request merged**
