### PR TITLE
Make stonith device probes fail after executor's stonith connection is lost

### PR DESCRIPTION
**Pull request by kgaillot**
with a bit of other fencing improvements spurred by testing. Fixes CLBZ#5352.

### CODE REVIEW

**Comment by kgaillot** [comment]
@gao-yan , I don't *think* this affects the situation your code in #1772 addressed, but you may want to test that case to be sure :)

**Comment by gao-yan** [comment]
OK, I'll build and test it.

**Comment by gao-yan** [comment]
It shouldn't affect that specific test case there since it's not a stonith resource. And indeed it doesn't according to my test :-) I'm thinking how to conduct a test with stonith resource.

**Comment by gao-yan** [comment]
I could verify the logic from https://github.com/ClusterLabs/pacemaker/pull/1772 works for stonith resource, which is not necessarily related to the changes in this pull though.

1. Configure a stonith resource and wait for it to be started
2. Put it into unmanaged mode with is-managed=false.
3. Manipulate the return code of the fence agent to make the monitor return error.
4. Change the monitor interval of the stonith resource
5. Monitor with the old interval that once failed gets canceled correctly, and monitor with the new interval is scheduled.

I was trying to connect the changes in this pull request. It behaves like:

1. Configure a stonith resource, wait for it to be started
2. Put it into unmanaged mode with is-managed=false.
3. killall -9 pacemaker-fenced
4. Monitor fails with rc=1
5. New fencer gets spawned and registers the device
6. But later monitor returns rc=7, saying:

Jul 04 18:44:20 opensuse150-1 pacemaker-fenced    [17363]  info: Ignoring API monitor action request because device st-sbd not found
Jul 04 18:44:20 opensuse150-1 pacemaker-controld  [14398] notice: Result of monitor operation for st-sbd on opensuse150-1: 7 (not running) | call=63 key=st-sbd_monitor_11000 confirmed=false cib-update=115

7. Monitor says this every interval :

Jul 04 18:44:31 opensuse150-1 pacemaker-fenced    [17363] info: Ignoring API monitor action request because device st-sbd not found

, while stonith_admin -L shows it's registered.

So in the latter case, it could not run into the logic of from https://github.com/ClusterLabs/pacemaker/pull/1772 . But the point is if the behavior makes sense although putting stonith resource into unmanaged mode is a little tricky ...

**Comment by kgaillot** [comment]
That actually is correct behavior since the resource is unmanaged -- it would normally recover from that by restarting the resource, which would register the device via the API (not just the CIB).

However you're right that it's questionable whether we should require API registration for monitor commands. In this PR, I dropped the requirement for list and status because it was obviously a bad idea for those, but monitor is more open to question.

The question is whether a fence device's recurring monitor should succeed if the device hasn't been "started" from pacemaker's point of view. The current practice is no, and I left it like that, but I'm not sure there's a good reason. To me, it makes sense that users might want to run a manual monitor command (i.e. stonith_admin --query) regardless of whether the device is started on not, and we should drop the requirement. On the other hand, maybe there was an (unfortunately undocumented) reason it was added in the first place, in which case we maybe could distinguish user-initiated vs. cluster-initiated. Or on the third hand ;) maybe that reason had to do with the old fenced and no longer applies. Whatever the case, I left that for later :)

**Comment by gao-yan** [comment]
Agreed.

**Pull request merged**
