### PR TITLE
Fix OCF_RA_PATH Autoconf variable name in pkg-config files

### PR DESCRIPTION
**Pull request by wferi**

### CODE REVIEW

**Comment by kgaillot** [comment]
Oops, thanks for catching this! It's a regression introduced in the 2.1.0 release. I'm thinking OCF_RA_INSTALL_DIR is the better alternative since it's a single directory, and more directly pacemaker-related (if someone is specifically querying pacemaker's pkgconfig for the directory and not resource-agents).

If you don't mind, please resubmit this against the 2.1 branch -- I'm going to release 2.1.2-rc1 this coming week, and the 2.1 branch is already prepped.

**Comment by wferi** [comment]
I changed the base as requested.
While having "PATH" in the name is indeed a bit misleading if this is a single directory, the "OCF directories to search for resource agents" comment is outright wrong then. Fortunately that's all internal business. I'm not sure what "INSTALL" would bring us in the name, but it's your choice.

**Comment by kgaillot** [comment]
> I changed the base as requested. While having "PATH" in the name is indeed a bit misleading if this is a single directory, the "OCF directories to search for resource agents" comment is outright wrong then. Fortunately that's all internal business. I'm not sure what "INSTALL" would bring us in the name, but it's your choice.

There are now two OCF options in configure:  --with-ocfrapath (OCF_RA_PATH) is where the running cluster should look to find "ocf:" resource agents, and can be a single directory or a colon-separated path; --with-ocfrainstalldir (OCF_RA_INSTALL_DIR) is where the "ocf:pacemaker:" agents should be installed as part of the build process, and is a single directory (presumably one of the directories on the RA path). This allows us to search for RAs in multiple locations, but we can obviously only install our own agents in one of them.

If someone's looking for the ocfdir value in pacemaker's pkg-config, the install dir makes sense to me as the thing they are looking for (and more backward compatible, since anything parsing that value won't be expecting a colon-separated path). However it would make sense at this point to expose the RA path via pkg-config as well.

**Comment by wferi** [comment]
Ah, got it now. Sorry for being dense.

**Comment by kgaillot** [comment]
> Ah, got it now. Sorry for being dense.

Not at all, we didn't think of it either until we tried implementing an RA path!

**Pull request merged**
