### PR TITLE
resource-agents: add "s"-suffix where missing in metadata

### PR DESCRIPTION
**Pull request by oalbrigt**

### CODE REVIEW

**Comment by kgaillot** [comment]
add to whitelist

**Comment by kgaillot** [comment]
The OCF standard is silent on the format of timeout, though the example RA meta-data has both e.g. "2m30s" and "100". It looks like existing RAs have a mix of with and without "s", so I guess all relevant software already handles both. Out of curiositiy, is the goal just to make it more obvious to users, or is there some problem with not having it?

**Comment by jnpkrn** [comment]
Explicit second-less qualification looks leaner and laic human
interfaces are free to do whatever normalization they see fit,
incl. more prosaic forms like:

```
Queried ocf:pacemaker:ping agent specifies these actions and
their defaults:
- start, with a timeout of 60 seconds
- stop, with a timeout of 20 seconds
- monitor, with a timeout of 60 seconds,
  run periodically each 10 seconds
For completeness, it also specifies these:
- meta-data, with a timeout of 5 seconds
- validate-all, with a timeout of 30 seconds
```

IOW. user friendly tweaks belong elsewhere, IMHO.

**Comment by oalbrigt** [comment]
@kgaillot we've added the "s"-suffix where it was missing for the main resource-agents repo (I'm fixing the last couple as we speak), for consistency with fence-agents and human readability.

**Comment by kgaillot** [comment]
I could see a new user feeling more comfortable about assuming what "10s" means vs "10", and if resource-agents is moving that way, the consistency will be helpful

**Pull request merged**
