### PR TITLE
Low: fenced: Remove relayed stonith operation.(Fix:CLBZ#5401)

### PR DESCRIPTION
**Pull request by wenningerk**

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi @HideoYamauchi , @wenningerk has backported your PR #2061. Would you have time to review this?

**Comment by HideoYamauchi** [comment]
Hi Ken,

> Hi @HideoYamauchi , @wenningerk has backported your PR #2061. Would you have time to review this?

Okay!
Please wait...

Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Klaus' backport PR works fine.

I confirmed the operation before and after applying the backport PR.
Before applying backport PR, there will be problems.
```
[root@rh76-01 pacemaker]# crm_mon -1 -Af
Stack: corosync
Current DC: rh76-01 (version 1.1.22-1a80025) - partition with quorum
Last updated: Thu May 14 06:39:13 2020
Last change: Thu May 14 06:37:03 2020 by root via cibadmin on rh76-01

2 nodes configured
3 resource instances configured

Node rh76-01: UNCLEAN (online)
Online: [ rh76-02 ]

Active resources:

 prmDummy       (ocf::pacemaker:Dummy): FAILED rh76-01
 prmStonith1-1  (stonith:external/ssh): Started rh76-02
 prmStonith2-1  (stonith:external/ssh): Started rh76-01

Node Attributes:
* Node rh76-01:
* Node rh76-02:

Migration Summary:
* Node rh76-01:
   prmDummy: migration-threshold=1 fail-count=1000000 last-failure='Thu May 14 06:38:14 2020'
* Node rh76-02:

Failed Resource Actions:
* prmDummy_stop_0 on rh76-01 'not installed' (5): call=18, status=Not installed, exitreason='',
    last-rc-change='Thu May 14 06:38:14 2020', queued=0ms, exec=0ms

Failed Fencing Actions:
* reboot of rh76-01 failed: delegate=, client=crmd.34208, origin=rh76-02,
    last-failed='Thu May 14 06:38:25 2020' 

Pending Fencing Actions:
* reboot of rh76-01 pending: client=crmd.34208, origin=rh76-01
* reboot of rh76-01 pending: client=crmd.34208, origin=rh76-01
* reboot of rh76-01 pending: client=crmd.34208, origin=rh76-01
* reboot of rh76-01 pending: client=crmd.34208, origin=rh76-01
* reboot of rh76-01 pending: client=crmd.34208, origin=rh76-01
* reboot of rh76-01 pending: client=crmd.34208, origin=rh76-01
* reboot of rh76-01 pending: client=crmd.34208, origin=rh76-01
* reboot of rh76-01 pending: client=crmd.34208, origin=rh76-01
* reboot of rh76-01 pending: client=crmd.34208, origin=rh76-01
* reboot of rh76-01 pending: client=crmd.34208, origin=rh76-01
```

After applying the backport PR, the problem goes away.
The fencing failure information, client and origin information are also switched correctly.
```
[root@rh76-01 pacemaker]# crm_mon -1 -Af
Stack: corosync
Current DC: rh76-01 (version 1.1.22-1a80025) - partition with quorum
Last updated: Thu May 14 06:50:38 2020
Last change: Thu May 14 06:48:08 2020 by root via cibadmin on rh76-01

2 nodes configured
3 resource instances configured

Node rh76-01: UNCLEAN (online)
Online: [ rh76-02 ]

Active resources:

 prmDummy       (ocf::pacemaker:Dummy): FAILED rh76-01
 prmStonith1-1  (stonith:external/ssh): Started rh76-02
 prmStonith2-1  (stonith:external/ssh): Started rh76-01

Node Attributes:
* Node rh76-01:
* Node rh76-02:

Migration Summary:
* Node rh76-01:
   prmDummy: migration-threshold=1 fail-count=1000000 last-failure='Thu May 14 06:49:25 2020'
* Node rh76-02:

Failed Resource Actions:
* prmDummy_stop_0 on rh76-01 'not installed' (5): call=18, status=Not installed, exitreason='',
    last-rc-change='Thu May 14 06:49:25 2020', queued=0ms, exec=0ms

Failed Fencing Actions:
* reboot of rh76-01 failed: delegate=, client=stonith-ng.33223, origin=rh76-02,
    last-failed='Thu May 14 06:49:36 2020' 
```

Best Regards,
Hideo Yamauchi.

**Comment by wenningerk** [comment]
Thanks for having a look Hideo!

**Pull request merged**
