### PR TITLE
Test: cts: use bash in the DummySD.service file

### PR DESCRIPTION
**Pull request by aleksei-burlakov**
systemd.daemon requires the systemd python library, that might be third
party.

### CODE REVIEW

**Comment by kgaillot** [comment]
What problem does this fix?

CTS does need the python systemd library. The upstream spec file adds an explicit dependency for Fedora > 20 and RHEL > 6. It is also listed under "Optional testing dependencies" in INSTALL.md.

**Comment by aleksei-burlakov** [comment]
Unfortunatelly, systemd-python is included in neither of versions of SUSE Enterprise Linux and it would be more preferable to patch pacemaker 1.1 version over adding the library.

**Comment by kgaillot** [comment]
This would also be an issue in the master branch, which is the current development branch for pacemaker (and ends up in 2.0 releases). The 1.1 branch is limited to backports from master.

In master, we've taken a different approach to helpers like this. They're all external now; this one is cts/pacemaker-cts-dummyd.in. That will be easier to keep compatible with both types of distro; we could wrap "import systemd.daemon" with a try/except and call systemd.daemon.notify() or subprocess.call() as appropriate.

Backporting it to 1.1 would involve a bit of extra work since it would have to be externalized, but 1.1's CTS could write and remove it the same way it does for DummySD.service already (i.e. we don't have to backport the entire cts-support change from 2.0).

Changes can go into master only, but they can't go into 1.1 only -- 1.1 is maintained solely for backward compatibility while distros get ready to adopt 2.0, and we don't want 1.1 behaving in new ways that differ from 2.0. If you want to continue with this, open a PR against master, and once we have that merged, we can deal with backporting.

**Comment by aleksei-burlakov** [comment]
I understand, that you have the policy master-first, but the code in regard of this dummy resource for master and 1.1 is already very different. We will introduce the python module for SUSE SLE releases that are shipping a pacemaker 2, but we wouldn't like to do it for older releases with a pacemaker 1.1. If it is acceptable to make such a change only for 1.1 branch this would be great, if not its sad. We will do it in our own package.

**Comment by kgaillot** [comment]
I do think it is a good idea to preserve the master-first policy, and use native facilities when available. My general idea would be easy to do in master, and would take just a bit more work to externalize that one file in 1.1:

    try:
      import systemd.daemon
      have_systemd_daemon = True
    except ImportError:
      have_systemd_daemon = False
    ...
    if systemd_daemon: systemd.daemon.notify(...)
    else: subprocess.call(["systemd-notify", ...])

But if you'd rather make a one-line patch on your side I understand :)

**Pull request closed without merging**
