### PR TITLE
Straightening commit 4657ad0 up

### PR DESCRIPTION
**Pull request by jnpkrn**

### CODE REVIEW

**Comment by kgaillot** [comment]
Looks good, but you'll need to update the pengine regression tests. Whenever changing the PE, be sure to run pengine/regression.sh from the source root.

**Comment by jnpkrn** [comment]
I thought that, but relied on either CI tests (negative) or the reviewer (positive) to holler :)
WIll add a commit for that.

**Comment by jnpkrn** [comment]
Hm, this was rather tricky as also the reason why CI hasn't reported anything:
`diff --ignore-all-space` is perhaps meant as a way to prevent unnecessary flux, but it abstract the very changes I made out of the picture.
I guess we want to mark the changes as desired explicitly, anyway?

**Comment by jnpkrn** [comment]
I am asking because the fresh expected output discovers more changes in the diff than what I changed in this PR. Should not this be rather handled in the "exit" phases (release or the candidate to be released)?

**Comment by kgaillot** [comment]
Rebase on current 1.1, you probably got it between related merges. Your diff should only show your changes.

**Comment by jnpkrn** [comment]
Of course that's not the case :-/

**Comment by jnpkrn** [comment]
Stuff like appears when I generate the outputs anew from before my changes (6a8c1e9):
```
--- a/pengine/test10/1-a-then-bm-move-b.dot
+++ b/pengine/test10/1-a-then-bm-move-b.dot
@@ -1,4 +1,4 @@
- digraph "g" {
+digraph "g" {
```

**Pull request merged**
