### PR TITLE
Low: libcommon: Erase old exit_reason. (2)

### PR DESCRIPTION
**Pull request by HideoYamauchi**
This is a modified version of the next PR.

 - https://github.com/ClusterLabs/pacemaker/pull/1341

### CODE REVIEW

**Comment by kgaillot** [comment]
Looking at the regression test changes, I'm a little hesitant to add exit-reason="" for every op that doesn't have one. This works for the regression tests, see if it handles your issue, too:

--- a/lib/common/operations.c
+++ b/lib/common/operations.c
@@ -557,7 +557,11 @@ create_operation_update(xmlNode * parent, lrmd_event_data_t * op, const char * c
     crm_xml_add(xml_op, XML_ATTR_CRM_VERSION, caller_version);
     crm_xml_add(xml_op, XML_ATTR_TRANSITION_KEY, op->user_data);
     crm_xml_add(xml_op, XML_ATTR_TRANSITION_MAGIC, magic);
-    crm_xml_add(xml_op, XML_LRM_ATTR_EXIT_REASON, exit_reason);
+    if (exit_reason) {
+        crm_xml_add(xml_op, XML_LRM_ATTR_EXIT_REASON, exit_reason);
+    } else if (crm_element_value(xml_op, XML_LRM_ATTR_EXIT_REASON)) {
+        crm_xml_replace(xml_op, XML_LRM_ATTR_EXIT_REASON, NULL);
+    }
     crm_xml_add(xml_op, XML_LRM_ATTR_TARGET, node); /* For context during triage */
 
     crm_xml_add_int(xml_op, XML_LRM_ATTR_CALLID, op->call_id);

**Comment by HideoYamauchi** [comment]
Hi Ken,

Perhaps, I think that you proposed the next correction.

```
(snip)
    crm_xml_add(xml_op, XML_ATTR_TRANSITION_KEY, op->user_data);
    crm_xml_add(xml_op, XML_ATTR_TRANSITION_MAGIC, magic);
    if (exit_reason) {
        crm_xml_add(xml_op, XML_LRM_ATTR_EXIT_REASON, exit_reason);
    } else if (crm_element_value(xml_op, XML_LRM_ATTR_EXIT_REASON)) {
        crm_xml_replace(xml_op, XML_LRM_ATTR_EXIT_REASON, NULL);
    }
    crm_log_xml_info(xml_op, "### YAMAUCHI ###");
    crm_xml_add(xml_op, XML_LRM_ATTR_TARGET, node); /* For context during triage */
(snip)
```

However, this fix does not work well.

Xml created for update will not include exit_reason.

```
Oct  6 17:37:23 rh73-01 crmd[479]:    info: ### YAMAUCHI ###   <lrm_rsc_op id="prmDummy_last_failure_0" operation_key="prmDummy_stop_0" operation="stop" crm-debug-origin="do_update_resource" crm_feature_set="3.0.14" transition-key="1:2:0:7dc7b07f-7120-4725-8826-6646ecb14a8d" transition-magic="2:1;1:2:0:7dc7b07f-7120-4725-8826-6646ecb14a8d"/>
Oct  6 17:37:23 rh73-01 crmd[479]:    info: ### YAMAUCHI ###   <lrm_rsc_op id="prmDummy_last_0" operation_key="prmDummy_stop_0" operation="stop" crm-debug-origin="do_update_resource" crm_feature_set="3.0.14" transition-key="1:2:0:7dc7b07f-7120-4725-8826-6646ecb14a8d" transition-magic="2:1;1:2:0:7dc7b07f-7120-4725-8826-6646ecb14a8d"/>

```

As a result, the contents of cib remains exit-reason.
("Start ERROR" is an old exit_reason I want to erase.)

```
        <lrm_resources>
          <lrm_resource id="prmDummy" type="Dummy" class="ocf" provider="heartbeat">
            <lrm_rsc_op id="prmDummy_last_0" operation_key="prmDummy_stop_0" operation="stop" crm-debug-origin="do_update_resource" crm_feature_set="3.0.14" transition-key="1:2:0:7dc7b07f-7120-4725-8826-6646ecb14a8d" transition-magic="2:1;1:2:0:7dc7b07f-7120-4725-8826-6646ecb14a8d" on_node="rh73-01" call-id="7" rc-code="1" op-status="2" interval="0" last-run="1507278983" last-rc-change="1507278983" exec-time="60002" queue-time="0" op-digest="f2317cad3d54cec5d7d7aa7d0bf35cf8" op-force-restart=" fake " op-restart-digest="f2317cad3d54cec5d7d7aa7d0bf35cf8" exit-reason="Start ERROR"/>
            <lrm_rsc_op id="prmDummy_last_failure_0" operation_key="prmDummy_stop_0" operation="stop" crm-debug-origin="do_update_resource" crm_feature_set="3.0.14" transition-key="1:2:0:7dc7b07f-7120-4725-8826-6646ecb14a8d" transition-magic="2:1;1:2:0:7dc7b07f-7120-4725-8826-6646ecb14a8d" exit-reason="Start ERROR" on_node="rh73-01" call-id="7" rc-code="1" op-status="2" interval="0" last-run="1507278983" last-rc-change="1507278983" exec-time="60002" queue-time="0" op-digest="f2317cad3d54cec5d7d7aa7d0bf35cf8"/>
          </lrm_resource>
```


Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Ah, I see. I think the right approach is: the same as my last suggestion, but using the empty string instead of NULL. That should achieve your goal, but will only add exit-reason="" if really needed (which should help with the regression test).

**Comment by HideoYamauchi** [comment]
Hi Ken,

Is it finally the next revision?

```
(snip)
    if (exit_reason) {
        crm_xml_add(xml_op, XML_LRM_ATTR_EXIT_REASON, exit_reason);
    } else if (crm_element_value(xml_op, XML_LRM_ATTR_EXIT_REASON)) {
        crm_xml_replace(xml_op, XML_LRM_ATTR_EXIT_REASON, NULL);
    } else {
        crm_xml_add(xml_op, XML_LRM_ATTR_EXIT_REASON, "");
    }
    crm_xml_add(xml_op, XML_LRM_ATTR_TARGET, node); /* For context during triage */
(snip)
```

With this fix, I will solve my problem as well.

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
I mean this:

```
    if (exit_reason) {
        crm_xml_add(xml_op, XML_LRM_ATTR_EXIT_REASON, exit_reason);
    } else if (crm_element_value(xml_op, XML_LRM_ATTR_EXIT_REASON)) {
        crm_xml_add(xml_op, XML_LRM_ATTR_EXIT_REASON, "");
    }
```

so that it adds exit-reason="" only if there is an existing exit-reason that needs to be overwritten.

**Comment by HideoYamauchi** [comment]
Hi Ken,

If stop timeout occurs, exit - reason is reported as NULL.
When creating an update xml, the exit-reason is not included in xml.

When problems occur, crm_xml_add (xml_op, XML_LRM_ATTR_EXIT_REASON, "") will not be executed.

```
 if (exit_reason) {
        crm_xml_add(xml_op, XML_LRM_ATTR_EXIT_REASON, exit_reason);
  } else if (crm_element_value(xml_op, XML_LRM_ATTR_EXIT_REASON)) {
        crm_xml_add(xml_op, XML_LRM_ATTR_EXIT_REASON, "");
  }
```

As a result, this fix produces the following xml and can not solve the problem.
```
Oct 10 17:43:17 rh73-01 crmd[23879]:    info: ### YAMAUCHI2 ###   <lrm_rsc_op id="prmDummy_last_failure_0" operation_key="prmDummy_stop_0" operation="stop" crm-debug-origin="do_update_resource" crm_feature_set="3.0.14" transition-key="1:3:0:30a3eccd-5bf0-47df-875f-93c312e252d8" transition-magic="2:1;1:3:0:30a3eccd-5bf0-47df-875f-93c312e252d8"/>
Oct 10 17:43:17 rh73-01 crmd[23879]:    info: ### YAMAUCHI2 ###   <lrm_rsc_op id="prmDummy_last_0" operation_key="prmDummy_stop_0" operation="stop" crm-debug-origin="do_update_resource" crm_feature_set="3.0.14" transition-key="1:3:0:30a3eccd-5bf0-47df-875f-93c312e252d8" transition-magic="2:1;1:3:0:30a3eccd-5bf0-47df-875f-93c312e252d8"/>
```

Best Reagards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

I must misunderstand the problem then. My thought with the suggested code was:

1. If there is a new exit-reason, always add it.
2. If the new exit-reason is NULL,
   2a. If there is an existing exit-reason, replace it with the empty string.
   3b. If there is no existing exit-reason, then nothing needs to be done.

Am I wrong?

**Comment by HideoYamauchi** [comment]
Hi Ken,

In this case, it is processing from do_update_resource ().

do_update_resource() ---> build_operation_update() ---> create_operation_update()

In this case, create an xml for update without searching the contents of cib already.

```
1. If there is a new exit-reason, always add it.
2.  If the new exit-reason is NULL,
   2a. If there is an existing exit-reason, replace it with the empty string.
   2b. If there is no existing exit-reason, then nothing needs to be done.
```

Therefore, there is no point in checking the existence of exit_reason at 2a, 2b.
Because the update xml is always created anew.

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Your version is correct, then. I'll update the regression tests accordingly. I've modified this request to be against the 1.1 branch, so it will be in 1.1.18.

**Comment by HideoYamauchi** [comment]
Hi Ken,

All right!

Many thanks!
Hideo Yamauchi.

**Pull request merged**
