### PR TITLE
Med: libfencing: minimize slowdown when fetching metadata

### PR DESCRIPTION
**Pull request by jnpkrn**
Commit 12cf7b9 limited bad impact of never-finishing fence agent when
asked for metadata, but imposed very impractical penalty of 1 second
unless the scheduler went crazy and favored the child being waited
for against the parent that waits for it to finish (as normally, first
its non-blocking wait-probe was too early).  This commit splits 1 s
sleeps into 100 ms ones, lowering the delay by an order of magnitude.
Alternatively, there could be a more convoluted arrangement using
eventloop, timer and SIGCHLD handling, but it would come at its own
costs.

### CODE REVIEW

**Comment by jnpkrn** [comment]
So far, Travis CI failure in `get_stonith_metadata` with `fence_dummy_monitor` looks like merely a timing issue that only got more likely with a more frequent interrupts in `select` and my guess it's also related to the VM constraints in their infra.  Will try to turn `fence_dummy_monitor` into shell or C (Python is a luxury in that case, anyway) to see if it helps.

**Comment by jnpkrn** [comment]
Non-representative comparison of shell (bash) bs. python2 in
a completely different, el7.3 VM:

```
# time fence_dummy_monitor.python >/dev/shm/foo <<<action=metadata
real    0m0.024s
user    0m0.012s
sys     0m0.005s
```
```
# time fence_dummy_monitor.sh >/dev/shm/foo <<<action=metadata
real    0m0.004s
user    0m0.001s
sys     0m0.003s
```

**Comment by jnpkrn** [comment]
(that being said, it's unfortunate that `fence-agents` are Python based
because one would expect as fast response as possible and taking shell
as a gauge, ...)

**Comment by kgaillot** [comment]
The fence_dummy_monitor change is reasonable, but I'm not comfortable with bringing the code closer to a busy wait. Maybe we could do something like action_synced_wait()?

**Comment by jnpkrn** [comment]
Yep, there's a problem of 100ms being and eternity for one machine + load, whereas it's closer to busy loop for another.

**Comment by jnpkrn** [comment]
Yes, `action_synced_wait` is appealing, but require some more considerations wrt. libraries cross-linking or how to reuse the code best.  Interim enhancement would be to add a simple linear/exponential back-off and fill the "magic constant" period with that.

**Comment by kgaillot** [comment]
I cherry-picked the "fence_dummy_monitor" commit. Closing this request, but feel free to open a new one with a different approach.

**Pull request closed without merging**
