### PR TITLE
Static analysis fixes

### PR DESCRIPTION
**Pull request by kgaillot**
This is mostly refactoring to address complaints from static analysis.

cibsecret needed a lot of changes, so a little more work was done to clean it up and fix minor issues.

### CODE REVIEW

**Comment by kgaillot** [comment]
@wenningerk , let me know if you think this is OK for 2.0. I tested cibsecret extensively, including with fping installed, though I didn't test the parallel ssh support.

**Comment by wenningerk** [comment]
Hard to say. Quite a lot of changes. Makes code better to read and more robust definitely.
Regarding the parallel ssh stuff I'd say that the code should be simple enough that we could say that it should be working if it was working before.
Regarding removal of lost assignments / increments I was very reluctant so far but this one here is overwritten near enough in the code I guess. Although not assigning it in the first place would have spared the comment ;-)

**Comment by kgaillot** [comment]
> Regarding the parallel ssh stuff I'd say that the code should be simple enough that we could say that it should be working if it was working before (given it supports '--')

I hadn't tested it because the projects aren't available in EPEL and didn't look like they are still maintained, but that was just being lazy. :)

The original pssh project died in 2012 but there's a fork on github that still gets some activity. I didn't get very far with it:

    # pssh -qi -H rhel8-2 -- hostname
    Usage: pssh [OPTIONS] command [...]

    pssh: error: no such option: -q

If I take out the "-q" it works, so at least it's not the -- that's breaking it :)

Even looking at the 2012 version that the current project was forked from, I don't see a -q option, so I'm not sure if cibsecret's pssh support was written for some other fork or what. But I don't think we're making things worse by using --.

@dmuhamedagic , do you have any insight on the pssh support in cibsecret?

I got further with pdsh, however I found I did introduce a trivial bug, so I'll fix that shortly and update this PR.

**Comment by kgaillot** [comment]
Updated. The only difference from before is two instances like:

-    PDSH_NODES=$(echo "$LIVE_NODES" | tr ' ' ',')
+    PDSH_NODES=$(echo "$LIVE_NODES" | tr '[:space:]' ',')

[:space:] is POSIX so hopefully we're safe using it

**Comment by kgaillot** [comment]
I tested that cibsecret does now work with pdsh, which must be installed on all cluster nodes

**Comment by dmuhamedagic** [comment]
On Thu, Jun 11, 2020 at 10:43:39AM -0700, Ken Gaillot wrote:
> The original pssh project died in 2012 but there's a fork on github that still gets some activity. I didn't get very far with it:
> 
>     # pssh -qi -H rhel8-2 -- hostname
>     Usage: pssh [OPTIONS] command [...]
> 
>     pssh: error: no such option: -q
> 
> If I take out the "-q" it works, so at least it's not the -- that's breaking it :)
> 
> Even looking at the 2012 version that the current project was forked from, I don't see a -q option, so I'm not sure if cibsecret's pssh support was written for some other fork or what. But I don't think we're making things worse by using --.
> 
> @dmuhamedagic , do you have any insight on the pssh support in cibsecret?

I cannot recall anything specific or why indeed was pssh chosen
and not pdsh. I would prefer pdsh, it's just slightly impractical
because with pdcp the targets need to have pdsh installed too. At
any rate, either would do. BTW, I still find pssh packaged in the
latest Debian.

**Comment by kgaillot** [comment]
> I cannot recall anything specific or why indeed was pssh chosen and not pdsh. I would prefer pdsh, it's just slightly impractical because with pdcp the targets need to have pdsh installed too. At any rate, either would do. BTW, I still find pssh packaged in the latest Debian.

I figured out the issue ... SUSE patches pssh to add a -q option. Ideally cibsecret would check for support before using that, but that can be separate from this PR.

cibsecret does support pdsh as well, and that works fine.

**Comment by kgaillot** [comment]
> I figured out the issue ... SUSE patches pssh to add a -q option. Id

The fix was trivial so I went ahead and added a commit on top for this

**Pull request merged**
