### PR TITLE
Mid: extra: Support of the dampen change by RA.

### PR DESCRIPTION
**Pull request by HideoYamauchi**
Hi All,

A change of dampen was supported by attrd.
Please revise RA in conjunction with the change.

 * https://github.com/ClusterLabs/pacemaker/commit/da9af2d2958c3b501777e45c42d2b605d162a6ca

Best Regards,
Hideo Yamauch.

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi Hideo,

If *delay* changes in the pacemaker configuration, pacemaker will stop then start the resource (or reload if supported). Therefore, I think *-B* should only be used with the start operation, not monitor. If monitor uses *-B*, there could be a potential race condition between a configuration change and a recurring monitor that gets the old value. If monitor uses *-v*, there is no way it can change the delay, which is safer.

I would suggest that the update functions could take an argument for this. For example, SysInfo's start could call *UpdateStat -B arch "`uname -m`* and UpdateStat would use the supplied argument when calling attrd_updater.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Thank you for comment.

Will it be that it is made the following modifications?

```
(snip)
ping_update() {
(snip)

    score=`expr $active \* $OCF_RESKEY_multiplier`
    if [ "$__OCF_ACTION" != start ]; then
        attrd_updater -n $OCF_RESKEY_name -v $score -d $OCF_RESKEY_dampen $attrd_options
    else
        attrd_updater -n $OCF_RESKEY_name -B $score -d $OCF_RESKEY_dampen $attrd_options
    fi
    rc=$?
(snip)
```

Consideration is a little more necessary to support reload when I do a change to use an option properly.

I think about a change again.


Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

That approach should work fine. If an agent already supports reload, and the delay option is reloadable, then yes, reload support should be included -- but there's no need to add reload support if it's not already there (unless you really want it).

**Comment by HideoYamauchi** [comment]
Hi Ken,

For example, ping becomes the following reload processing.

```
(snip)
ping_start() {
    ping_monitor
    if [ $? =  $OCF_SUCCESS ]; then
        return $OCF_SUCCESS
    fi
    touch ${OCF_RESKEY_pidfile}
    ping_update
}
(snip)
monitor)        ping_monitor;;
reload)         ping_start;;
validate-all)   ping_validate;;
(snip)

```

In ping, the following change is thought about to cope with dapmen change.
(A change to let you abolish support of reload and do stop/start.)


```
monitor)        ping_monitor;;
validate-all)   ping_validate;;
```


What do you think?


Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

I agree, removing reload from ping makes sense.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Thank you for comment.

Okay!
I reconsider it about other resource agents.
And I send a new patch.

Many Thanks!
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,

It may have a problem to abolish reload.
I think a little more.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,

My worry seems to be unnecessary.
I send a new patch.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,

One let me ask you a question.

You pointed out competition of the update by the first comment.

> If monitor uses -B, there could be a potential race condition between a configuration change and a recurring monitor that gets the old value.

However, monitor is canceled when a resource does restart(stop/start).

In what kind of case, does this phenomenon happen?

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
You're probably right. I was thinking there might be a small chance: If a recurring monitor is initiated just before a configuration change, the monitor's attrd_updater command might be started by the OS, but (for example, due to OS swapping) not complete until after the configuration change's stop and start had already run. In that case, the final value might be the old delay. (I'm not sure whether cancelling the monitor would kill any child commands already spawned.)

It's probably so unlikely that it's not important, but I would feel more comfortable if a monitor can't change a delay, since it shouldn't be able to.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Thank you for comment.

I think that it is safe not to update an attribute in monitor when I consider the special usage of the attribute of the resource.

Please take a patch in a master if the patch which I revised does not have a problem.

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

Thanks for the changes. I think the ifspeed reload action would have actually worked properly, so we could have kept it, but I don't think it's important. The ping agent could benefit from a reload action, but the one it had would not have worked correctly, so we're better off without it for now.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Okay!
Thank you for merging a patch.

Many Thanks!
Hideo Yamauchi.

**Pull request merged**
