### PR TITLE
Prepare schema code for further deprecations

### PR DESCRIPTION
**Pull request by kgaillot**
This fixes some minor issues in the schema code, in preparation for further changes

### CODE REVIEW

**Comment by kgaillot** [comment]
@clumens, can you review this when you get a chance? Thanks

**Comment by kgaillot** [comment]
There is one outstanding problem. I thought that since the setup-schema-dir make target is phony, that it would be rerun for each unit test file. However it looks like my removing files is "permanent". Maybe I'll rename them and name them back after the test.

**Comment by kgaillot** [comment]
retest this please

**Comment by clumens** [comment]
This looks fine, but I'd like to know that the remote schema transfer stuff still works.

**Comment by kgaillot** [comment]
> This looks fine, but I'd like to know that the remote schema transfer stuff still works.

Don't the unit tests cover it?

**Comment by kgaillot** [comment]
Updated to temporarily rename schemas in unit testing rather than remove them, added one bug fix on top, and fixed typos

**Comment by kgaillot** [comment]
I have no freaking clue why unit tests are failing on only some platforms. I pushed the first three trivial commits so we can merge those first.

**Comment by clumens** [comment]
> > This looks fine, but I'd like to know that the remote schema transfer stuff still works.
> 
> Don't the unit tests cover it?

They cover the basics, yeah, but there's a lot of code in daemons/execd/remoted_schemas.c that builds on top of that stuff.  I'm not sure if the other patches are a concern or not regarding that code.

**Pull request merged**
