### PR TITLE
Mid: Alert: Set SNMP_PERSISTENT_DIR directory for the snmp-trap tool.

### PR DESCRIPTION
**Pull request by HideoYamauchi**
Hi All,

I add the designation of the SNMP_PERSISTENT_DIR directory for snmptrap tool.

With this patch, I restrain the next log output with snmptrap tool.

```
crmd[3569]:  notice: notify_9:4265:stderr [ Cannot rename /var/lib/net-snmp/snmpapp.conf to /var/lib/net-snmp/snmpapp.0.conf ]
crmd[3569]:  notice: notify_9:4265:stderr [ Cannot unlink /var/lib/net-snmp/snmpapp.conf ]

crmd[6507]:  notice: notify_9:6626:stderr [ Created directory: /xxxx/.snmp_presist/cert_indexes ]
crmd[6507]:  notice: notify_9:6626:stderr [ Created directory: /xxxx/.snmp_presist/mib_indexes ]

```

The SNMP_PERSISTENT_DIR of the default is /localstatedir/lib/pacemaker/snmp .(e.g./var/lib/pacemaker/snmp)

In trap_snmp_persistent_dir parameter, the user can appoint it.

This patch was discussed with the next link.

 * https://github.com/ClusterLabs/pacemaker/pull/1190

Best Regards,
Hideo Yamauchi.

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi Hideo,

The changes to the alert agent look good.

I'd rather not make the new directory part of the pacemaker installation, though. I think alert agents should be self-contained, because they are optional, and potentially site-specific.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Thank you for comment.

Then..... I want to leave you as two next corrections.

 * A change and a correction to alert_snmp.sh.sample.in.
 * A correction to set CRM_SNMP_TRAP_TOOLS_DIR.

What do you think?

Without a problem, I test a correction again and will send the last patch next week.

Many thanks!
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,

I set up the next last patch.
How about?

 * https://github.com/HideoYamauchi/pacemaker/commit/3dd5bdc52a3cc253035417de3fbe8d5aa7bdfaf4

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

I'm reluctant to add CRM_SNMP_TRAP_TOOLS_DIR, because the sample script is not part of the core pacemaker code base.

I think it will be fine to put /var/lib/pacemaker/snmp as the explicit default, because (1) it's a sample script that's meant to be edited for the local situation; and (2) the script does "mkdir -p", so it will work fine even if someone leaves the default when they have pacemaker in a different location.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Sorry....

I was able to finally understand your opinion.
I discard introduction of CRM_SNMP_TRAP_TOOLS_DIR and send a correction only for alert_snmp.sh.sample as a patch again.

Many thanks!
Hideo Yamauchi.

**Pull request closed without merging**
