### PR TITLE
Low: rng: Add missing resource classes to template

### PR DESCRIPTION
**Pull request by krig**
Surely, the class attribute for templates should list the same
set of classes as the one for primitives?

### CODE REVIEW

**Comment by jnpkrn** [comment]
Nice catch!

Anyway, you can see the maintenance issue (cause of this one) persists
so I would suggest modularizing the enumeration (which RelaxNG allows)
and referring to it from both locations to avoid future divergency.

**Comment by jnpkrn** [comment]
Or better yet, whole ascendant `<choice>` perhaps?

**Comment by krig** [comment]
Good suggestions, I updated the pull request. I'm not fluent in relaxng so please double-check that I got it right :)

**Comment by jnpkrn** [comment]
Looks good to me, both reviewed manually and diffing the outputs of
`jing -is pacemaker-1.3.rng > diffme.rng` (jing from jingtrang project).
Thanks.

**Comment by jnpkrn** [comment]
This would likely warrant inclusion in upcoming 1.1.16 release, could you please retarget + rebase against 1.1 branch, please?

**Comment by kgaillot** [comment]
Actually, I think master is appropriate, I'm keeping 1.1 changes to a minimum so I can release it soon.

Also, this will require an XML version bump -- leave resources-1.3.rng alone, and make these changes in a new resources-2.7.rng. If someone makes a config based on this, it could fail under existing 1.3 validators, so a version bump is necessary.

**Comment by kgaillot** [comment]
See xml/Readme.md, this is a "simple addition". It walks you through the steps.

**Comment by krig** [comment]
Alright, this should do it.

**Comment by jnpkrn** [comment]
See #1183

**Comment by krig** [comment]
Deleted trailing whitespace, feel free to close this and merge #1183 with the updated commit. :+1:

**Comment by jnpkrn** [comment]
Thanks, done.  I've also noticed my very own whitespace discrepancy, tab instead of spaces :-)

**Comment by kgaillot** [comment]
> Deleted trailing whitespace, feel free to close this and merge #1183 with the updated commit.

github was smart enough to mark this one as merged once that one was merged

**Comment by jnpkrn** [comment]
On 28/11/16 10:00 -0800, Ken Gaillot wrote:
>> Deleted trailing whitespace, feel free to close this and merge #1183 with the updated commit.
> 
> github was smart enough to mark this one as merged once that one was merged

It was the easy-to-identify exact commit reuse :-)

-- 
Jan (Poki)

**Comment by krig** [comment]
Thanks!

**Pull request merged**
