### PR TITLE
Fix spelling: Negligable -> Negligible

### PR DESCRIPTION
**Pull request by wferi**

### CODE REVIEW

**Comment by wferi** [comment]
Looks like I should have created this pull request against the 1.1 branch. Is there a way to get this into 1.1.16 still? Not that it couldn't wait...

**Comment by kgaillot** [comment]
Master is fine, trying to keep 1.1 changes to a minimum so I can ship it soon

**Comment by wferi** [comment]
Ah, I thought trivial changes like this were OK nevertheless. Never mind.

**Comment by kgaillot** [comment]
For a normal release it would be, but with 1.1.16 containing an important security fix, I'm speeding up the release process, so I want as few changes as possible at this point.

**Pull request merged**
