### PR TITLE
Low: resources: Put shortdesc after longdesc in the attribute agent.

### PR DESCRIPTION
**Pull request by clumens**
This is the order required by the OCF resource agent schema.

See: rhbz#2049722

### CODE REVIEW

**Comment by kgaillot** [comment]
o2cb has the same issue

**Comment by kgaillot** [comment]
pcmk__format_option_metadata() and pacemaker-fenced.c have a similar issue for parameters

**Comment by clumens** [comment]
pacemaker-fenced has a variety of problems:
```
[root@cluster01 ~]# /usr/libexec/pacemaker/pacemaker-fenced metadata | xmllint --noout --relaxng ocf1.1.rng -
-:1: warning: failed to load external entity "ra-api-1.dtd"
<?xml version="1.0"?><!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
                                                                    ^
-:21: element shortdesc: Relax-NG validity error : Did not expect element shortdesc there
-:21: element shortdesc: Relax-NG validity error : Element parameter has extra content: shortdesc
-:34: element content: Relax-NG validity error : Element content failed to validate content
-:59: element content: Relax-NG validity error : Element content failed to validate content
-:76: element content: Relax-NG validity error : Element content failed to validate content
-:93: element content: Relax-NG validity error : Element content failed to validate content
-:110: element content: Relax-NG validity error : Element content failed to validate content
-:127: element content: Relax-NG validity error : Element content failed to validate content
-:144: element content: Relax-NG validity error : Element content failed to validate content
-:2: element resource-agent: Relax-NG validity error : Expecting an element , got nothing
- fails to validate
```

**Comment by kgaillot** [comment]
The daemon metadata options are a bit of an exception, they use the RA format for parameters but don't implement the entire agent schema. So, technically it's sufficient if they are valid XML. But, maybe we should throw in enough to make it validate against the schema, so we can validate the parts it does need.

**Pull request merged**
