### PR TITLE
Move enum rsc_recovery_type to libcrmcommon

### PR DESCRIPTION
**Pull request by kgaillot**
This is the start of a project to merge the functionality of libpe_rules and libpe_status into libcrmcommon.

### CODE REVIEW

**Comment by kgaillot** [comment]
@waltdisgrace , could you review this when you get a chance? Thanks, low priority

FYI @wenningerk @clumens @nrwahl2 @gao-yan , this is the start of a project to combine libpe_rules and libpe_status into libcrmcommon. I haven't seen a compelling reason to keep multiple smaller libraries, and I've never liked that libpe* share a source directory and overlapping code (common.c). Since I want to bring the libpe* code up to current guidelines, I figured I'd merge it into libcrmcommon at the same time. If anyone thinks that's a bad idea, now's the time to speak up :)

**Comment by nrwahl2** [comment]
I welcome it as long as no one thinks of a reason why multiple low-level libraries are beneficial. Besides the issues mentioned above, it's occasionally annoying that symbols from `libpe_*` and `libcib` are inaccessible from `libcrmcommon`.

**Comment by wenningerk** [comment]
Guess from the modularity-aspect there is no real reason to keep them separate.
And when running on something really memory constrained there is ksm today and
I guess there is no use-case where the low-level-libs wouldn't be loaded by something
else on the node. Haven't checked but which libraries does pacemaker-remote actually
need?

**Comment by kgaillot** [comment]
> Guess from the modularity-aspect there is no real reason to keep them separate. And when running on something really memory constrained there is ksm today and I guess there is no use-case where the low-level-libs wouldn't be loaded by something else on the node. Haven't checked but which libraries does pacemaker-remote actually need?

Remote uses libcrmcommon, libcrmservice, libstonithd, and liblrmd.

With lazy loading and whatnot, I suspect it doesn't matter much. For comparison, libcrmcommon + libpe_rules + libpe_status + libcib are about the same size as glib (not including libgio). libxml2 and libgnutls are bigger.

**Comment by waltdisgrace** [comment]
@kgaillot This looks good to me.

**Pull request merged**
