### PR TITLE
Minor build changes before 2.0.5 release

### PR DESCRIPTION
**Pull request by kgaillot**

### CODE REVIEW

**Comment by kgaillot** [comment]
@clumens , can you review this? It should go in 2.0.5

**Comment by kgaillot** [comment]
Added some commits needed for CI testing. @fabbione , can you review this instead, and test it with your custom install locations?

**Review by fabbione — APPROVED** [review]
@kgaillot works perfectly fine for me as-is and good to go.

Now, I can see you already started moving things around in pkg-config area. If there is still time, can you also add PKG_CHECK_VAR([OCFROOT], [resource-agents], [ocfdir]) equivalent?

And FYI I am more than happy to give configure.ac a good cleanup once 2.0.5 is out. I have noticed some level of leftovers and ordering that could make ./configure much easier (less options to specify) for pretty much everybody. Tho this is pre 2.1 work.

**Comment by fabbione** [comment]
Small correction due to a bug in ras that has been fixed today:
PKG_CHECK_VAR([OCFROOT], [resource-agents], [ocfrootdir])
that will return the correct path.

**Comment by clumens** [comment]
This all looks good to me for 2.0.5.

**Comment by kgaillot** [comment]
> Now, I can see you already started moving things around in pkg-config area. If there is still time, can you also add PKG_CHECK_VAR([OCFROOT], [resource-agents], [ocfdir]) equivalent?

@fabbione , we're looking to get 2.0.5 final out as soon as possible this week, so unless that's essential I'd rather save it for the next release around the middle of next year

**Comment by fabbione** [comment]
On 30/11/2020 17.13, Ken Gaillot wrote:
>     Now, I can see you already started moving things around in
>     pkg-config area. If there is still time, can you also add
>     PKG_CHECK_VAR([OCFROOT], [resource-agents], [ocfdir]) equivalent?
> 
> @fabbione <https://github.com/fabbione> , we're looking to get 2.0.5 
> final out as soon as possible this week, so unless that's essential I'd 
> rather save it for the next release around the middle of next year
>

Not urgent at all :) It's one configure option for CI, nothing dramatic ;)

Thanks
Fabio

**Pull request merged**
