### PR TITLE
Minor stonith fixes and refactoring

### PR DESCRIPTION
**Pull request by kgaillot**
While this includes a couple of minor fixes and some additional developer documentation, the main goal is to lay the groundwork for being able to remap reboot to off+on.

### CODE REVIEW

**Comment by kgaillot** [comment]
I'm well into a 100-random-test run of CTS with no fencing-related issues. Will update this comment when complete. Will also run the fencing regression tests if I can figure out how.

**Comment by beekhof** [comment]
Merge now?

**Comment by kgaillot** [comment]
When you asked, no -- now, yes :)

**Comment by davidvossel** [comment]
@kgaillot these changes all look good to me. great work!

**Pull request merged**
