### PR TITLE
Avoiding conditional directives that split up parts of statements.

### PR DESCRIPTION
**Pull request by RomeroMalaquias**

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi,

We generally don't do stylistic-only changes. Is there any situation where the current code causes problems?

**Comment by RomeroMalaquias** [comment]
Hi,
no, i've not found any errors. It's just a suggestion that can improve code understanding and maintainability.

**Comment by kgaillot** [comment]
There are far too many possibilities there for any person to keep up :)

The time involved in coding, review, merging, testing, etc., and the possibility of unintended consequences, isn't worth the gain for purely stylistic changes.

**Comment by RomeroMalaquias** [comment]
Ok, thanks for clarifying

**Pull request closed without merging**
