### PR TITLE
Minor clean-up of NLS code

### PR DESCRIPTION
**Pull request by kgaillot**

### CODE REVIEW

**Comment by kgaillot** [comment]
@clumens , can you review this PR when you get a chance? Low priority

**Comment by clumens** [comment]
This all looks good.  Related, I think you actually want `BuildRequires: gettext-devel` in rpm/pacemaker.spec.in, and not just gettext.

**Comment by kgaillot** [comment]
> This all looks good. Related, I think you actually want `BuildRequires: gettext-devel` in rpm/pacemaker.spec.in, and not just gettext.

The Fedora Packaging Guidelines specifically say to depend on gettext, even though gettext-devel makes more sense. I've emailed the Fedora devel list for clarification. I can change that in a separate PR though.

**Comment by clumens** [comment]
> > This all looks good. Related, I think you actually want `BuildRequires: gettext-devel` in rpm/pacemaker.spec.in, and not just gettext.
> 
> The Fedora Packaging Guidelines specifically say to depend on gettext, even though gettext-devel makes more sense. I've emailed the Fedora devel list for clarification. I can change that in a separate PR though.

Hm, I wonder if we're doing something incorrect in the build process, then.  `make mock-centos-stream-8-x86_64` fails with:

```+ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
Can't exec "autopoint": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext
error: Bad exit status from /var/tmp/rpm-tmp.ZmSiku (%build)
    Bad exit status from /var/tmp/rpm-tmp.ZmSiku (%build)
```

**Comment by kgaillot** [comment]
> Hm, I wonder if we're doing something incorrect in the build process, then.

I suspect the packaging guidelines are wrong

**Comment by kgaillot** [comment]
> > Hm, I wonder if we're doing something incorrect in the build process, then.
> 
> I suspect the packaging guidelines are wrong

Actually the guidelines are correct, according to a reply on the mailing list. gettext is lower-level much how gcc is a dependency and not gcc-devel. gettext-devel has the autoconf macros, but in a package build, configure.ac has already been expanded to configure in the source tarball.

I believe the fix for our mock issue will be to add gettext-devel to the mock-install-% target in rpm/Makefile.am, which I'll do separately. Unfortunately the package name is different for SUSE and Debian, so I'll have to come up with something to handle that.

**Comment by kgaillot** [comment]
> > > Hm, I wonder if we're doing something incorrect in the build process, then.
> > 
> > 
> > I suspect the packaging guidelines are wrong
> 
> Actually the guidelines are correct, according to a reply on the mailing list. gettext is lower-level much how gcc is a dependency and not gcc-devel. gettext-devel has the autoconf macros, but in a package build, configure.ac has already been expanded to configure in the source tarball.
> 
> I believe the fix for our mock issue will be to add gettext-devel to the mock-install-% target in rpm/Makefile.am, which I'll do separately. Unfortunately the package name is different for SUSE and Debian, so I'll have to come up with something to handle that.

OK that was completely wrong. :)

We do need to depend on gettext-devel, but only because we call autoreconf in the spec, which is a somewhat controversial practice.

autoreconf should be needed only if the spec patches an autotools input (configure.ac, Makefile.am, etc.). The upstream spec doesn't use patches, so I assume the autoreconf is in there to minimize differences from downstream specs, and avoid a gotcha for anyone adding their own patch to the upstream spec.

For now, I think depending on gettext-devel is the easiest solution. One could make a case for dropping the autoreconf upstream and depending on gettext, but then downstreams would need to re-add the autoreconf and gettext-devel if their patches need it.

**Pull request merged**
