### PR TITLE
Trivial fixes

### PR DESCRIPTION
**Pull request by kgaillot**
These are little things that came up during testing of the release candidates

### CODE REVIEW

**Comment by kgaillot** [comment]
@wenningerk , what do you think of these for 2.0?

**Comment by wenningerk** [comment]
No danger in any of those I guess.

**Comment by kgaillot** [comment]
> Would a remark make sense here?

Updated last commit, take a look

**Comment by wenningerk** [comment]
> > Would a remark make sense here?
> 
> Updated last commit, take a look

cool - should be enough as a reminder

**Pull request merged**
