### PR TITLE
Mid: extra: Script for the SNMP trap.

### PR DESCRIPTION
**Pull request by HideoYamauchi**
Hi All,

I send the script for the SNMP trap
I branch off the transmission in a parameter.

We want to put this script as the script which is available to users immediately.

We want to include this script in Pacemaker1.1.15 with order of traps control.

 * The script of Alert is different from the OCF resource, but thinks that Pacemaker should add it to the head of the environment variable handed in instance_attributes what it is.
   ex) SCRIPT_xxxx.

Best Regards,
Hideo Yamauchi.

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi Hideo,

I've discussed this with Klaus, and we think it's a great addition.

Instead of adding it as a new file, why don't you modify the existing extra/alerts/pcmk_snmp_helper.sh? I think it is an improvement over the current one, and there is no need to keep both.

In your sample configuration, the instance_attributes should go inside the alert block, and the close tag should match the open tag.

We're thinking that it would be good to add hrSystemDate (1.3.6.1.2.1.25.1.2 OID) with the value of CRM_alert_timestamp. We can do that later if you don't want to include it in this request.

**Comment by kgaillot** [comment]
Also, close this request, and resubmit it against the 1.1 branch, to get it into 1.1.15.

**Comment by HideoYamauchi** [comment]
Hi Ken,

I thought pcmk_snmp_helper.sh to be necessary as a sample.
I send this script as a patch rearranging pcmk_snmp_helper.sh.

It is my mistake to lack a terminal of instance_attributes of the sample.
```
# ================================
# <configuration>
#   <alerts>
#     <instance_attributes id="insta_9">
#       <nvpair id="trap_nodes" name="trap_node" value="no"/>
#       <nvpair id="trap_fencing" name="trap_fencing" value="no"/>
#     </instance_attributes>
#     <alert id="snmp_alert" path="/path/to/pcmk_snmp_notify.sh">
#       <recipient id="snmp_destination" value="192.168.1.2"/>
#     </alert>
#   </alerts>
# </configuration>
# ================================
```

I talked with a Japanese member, but do not seem to do the use sorting a trap on the SNMP manager side on the date and time expressly.
Thus, we require the order of transmission of the trap.

I send a patch to PM1.1 again again.

Many thanks,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken, 

Sorry...
I have got a wrong new pullrequest many times.

Best Regards,
Hideo Yamauchi.

**Comment by wenningerk** [comment]
Hi Hideo,

the attributes are still in the alerts-block instead of the alert-block ;-)

I had got that you didn't see the hrSystemDate OID timestamp as a solution to your problem.
But having seen that loosing the order of traps might be a genal issue it is still the only easy
approach when traps are coming from different nodes. This might for some reasons not apply for
your problem but to give a generic solution it is still a way to go and it is a good example
to show the possibilities of the interface enhancements.
So I think we should have the timestamp-OID in. Can be configurable via a switch as the
traps...

It is quite common in the cib to express boolean decisions via true/false - so this might
be nicer here as well - just for consistency.

Your implementation btw. is kind of talkative as it sends traps for all monitor-actions.
This might be interesting for certain cases but I guess for the default case the original
approach just to trap failed monitors would be the better solution. Thus a switch like
trap_all_monitors would be handy here as well.

Regards,
Klaus

**Comment by kgaillot** [comment]
@HideoYamauchi, no problem. I think we've all had days like that :-)

**Pull request closed without merging**
