### PR TITLE
there are tabs in files of xml dirctory which makes it not convenient…

### PR DESCRIPTION
**Pull request by liu4480**
Low: xml: use spaces instead of tabs in schema files

### CODE REVIEW

**Comment by kgaillot** [comment]
This looks fine, but please amend the commit message to be more in line with our (not very well-documented) usual style. In this case, the first line should be something like "Low: xml: use spaces instead of tabs in schema files" and the current message could be below that for more detail. In general, the first line of the commit message should be less than 80 characters for easy screen browsing.

The first word does not have strict rules, but commonly we use "Fix:" or "Feature:", or "High:" or "Low:" to indicate importance. The only real significance is that anything with "Feature:", "High:", "Fix:" or "Bug" will be considered for the release notes.

For future reference, we rarely change existing schema files. They are intended to be the definitive description of the schema at a particular point in time, so new ones can be added, but old ones are usually not changed. Formatting-only changes such as this one can be an exception.

**Comment by jnpkrn** [comment]
Re formatting of the commit title (first line):
I don't know the full history behind this habbit, but can attest
to the practical value and convenience of the (possibly structured)
prefixes in the commit titles when compiling meaningful changelog
later on.
See also http://clusterlabs.org/developers.html (Developer FAQ #1).

And one correction:
Commit title should be, by git standards, no longer than 72 characters
(with prefered boundary 50 characters, which is quite often too few).

**Comment by jnpkrn** [comment]
@liu4480 btw. if you are just after understanding the schema, you may
have a look at equivalent schemas that were just compacted to standalone
big files (as opposed to cross-referenced files you can observe here):
https://pagure.io/clufter/blob/master/f/formats/cib
(yep, they were reformatted as a side-effect of the compacting process).

**Comment by liu4480** [comment]
Hi, Ken and jnpkrn, thanks for your advices

**Comment by kgaillot** [comment]
Hi,

I'm sorry, I meant that the commit message in the git repository needs to be changed. You can use "git commit --amend" to update the commit message and then force-push it, and this request will be updated automatically. The git commit messages are used to build the change log for each new release.

**Comment by liu4480** [comment]
Hi, Ken
Sorry for the misunderstand, the commit message has been updated.

**Comment by kgaillot** [comment]
Thanks!

**Pull request merged**
