### PR TITLE
XSLT: Disallow master resources and masters XML attribute

### PR DESCRIPTION
**Pull request by nrwahl2**
Fixes part of T273. We can't drop the meta-attributes mentioned there because resource agents still use them.

### CODE REVIEW

**Comment by nrwahl2** [comment]
@waltdisgrace Can you review this when you get a chance? Thanks

**Comment by nrwahl2** [comment]
Only updated the last commit message to say that it closes the task

**Comment by kgaillot** [comment]
Also update the "Deprecated Terminology" box in Pacemaker Explained's collective resources chapter

**Review by waltdisgrace — APPROVED** [review]

**Comment by kgaillot** [comment]
The clone meta-attributes were separated into their own issue T874, so this closed T273

**Pull request merged**
