### PR TITLE
Add a test for "infinitely sticky and optionally anti-colocated group with member at migration-threshold"

### PR DESCRIPTION
**Pull request by kgaillot**
This arose from the discussion on #3092

We have an existing test bug-lf-2613 (renamed to failed-sticky-group here) that shows the desired behavior when a group with infinite stickiness has a failed member at its migration-threshold. The group should move, despite the stickiness.

Given that, it seems that a variation of the group-anticolocation test with infinite stickiness (the new failed-sticky-anticolocated-group test here) should also move the group, despite both the stickiness and the optional anti-colocation.

### CODE REVIEW

**Comment by kgaillot** [comment]
@nrwahl2 , can you review this when you get a chance? Thanks

**Comment by kgaillot** [comment]
This does not add a test for mandatory anti-colocations as discussed in #3092 , but it heads in that direction by better defining the behavior for optional anti-colocations

**Review by nrwahl2 — APPROVED** [review]
Looks good to me.

In the first commit's test summary, we say that the goal of keeping as many resources active as possible overrides X. In the second and third commits we say that the last member's migration-threshold overrides X. Optionally, we could use the same verbiage on all of them (which may be either of the above or a combination of them). I don't have strong feelings, just pointing this out.

**Comment by kgaillot** [comment]
> Looks good to me.
> 
> In the first commit's test summary, we say that the goal of keeping as many resources active as possible overrides X. In the second and third commits we say that the last member's migration-threshold overrides X. Optionally, we could use the same verbiage on all of them (which may be either of the above or a combination of them). I don't have strong feelings, just pointing this out.

Good point, I think the "goal" language is slightly more accurate since stopping the resource does technically honor the migration-threshold. Updated.

**Pull request merged**
