### PR TITLE
Fix: crm_mon: try to connect CIB while pacemakerd shutting down

### PR DESCRIPTION
**Pull request by wenningerk**
we need to do this in all output modes (xml specifically)

### CODE REVIEW

**Comment by HideoYamauchi** [comment]
Hi Klaus,

There were no problems in the test.
Please merge this fix.

And by all means, include this fix in the release of RHEL 8.4.

I have only one question.

Until this fix (https://github.com/ClusterLabs/pacemaker/pull/2278), there was no communication with pacemakerd, so crm_mon worked fine even if the pacemakerd process freezes. ..

With this fix, crm_mon will fail if the pacemakerd process freezes, resource monitoring etc. will also fail.
I think it's almost rare that the pacemkaerd process freezes, so it's not a must, but is it difficult to fix it so that crm_mon returns a result even if the pacemakerd process freezes as before?

Best Regards,
Hideo Yamauchi.

**Comment by wenningerk** [comment]
Thank you for verifying.

What we could do in theory is that in xml-output-mode we don't check for pacemakerd at all or ignore what we get back.
Ignoring might even be more preferable as it would not add the time for checking pacemakerd that if it fails and CIB connection still succeeds might still lead to a failure because of timeout.
On the other hand if pacemakerd isn't responsive we are missing the instance that keeps the sub-daemons alive (and in future is even doing more active live-checking) which is why an answer from crm_mon telling you "I don't know about the status of the cluster" might be better reflecting the actual state than something derived from bare liveness of the CIB.

**Comment by HideoYamauchi** [comment]
Hi Klaus,

> Thank you for verifying.
> 
> What we could do in theory is that in xml-output-mode we don't check for pacemakerd at all or ignore what we get back.
> Ignoring might even be more preferable as it would not add the time for checking pacemakerd that if it fails and CIB connection still succeeds might still lead to a failure because of timeout.
> On the other hand if pacemakerd isn't responsive we are missing the instance that keeps the sub-daemons alive (and in future is even doing more active live-checking) which is why an answer from crm_mon telling you `I don't know about the status of the cluster` might be better reflecting the actual state than something derived from bare liveness of the CIB.

It seems good to wait for better fixes in the future.
I look forward to future corrections.

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
I think there's a difference between pacemakerd saying that the other daemons are not (yet) available, and pacemakerd itself not responding.

In the first case, we can just pass along that info and not try anything further.

In the second case, I think we should try to contact all the daemons, and if none respond, display the current "cluster is not available" error, otherwise display a warning (something like "Warning: cluster is degraded on this node (pacemakerd [or whatever] not responding)") and show the information we do have.

**Comment by HideoYamauchi** [comment]
Hi Ken,

> I think there's a difference between pacemakerd saying that the other daemons are not (yet) available, and pacemakerd itself not responding.
> 
> In the first case, we can just pass along that info and not try anything further.
> 
> In the second case, I think we should try to contact all the daemons, and if none respond, display the current "cluster is not available" error, otherwise display a warning (something like "Warning: cluster is degraded on this node (pacemakerd [or whatever] not responding)") and show the information we do have.

If pacemakerd is freezes, crm_mon will return a response if it can connect to based and fenced even if pacemakerd_status () fails to connect.
If that connection also fails, it may be better for the connection to fail.

Either way, I hope to fix the problem when pacemakerd freezes in the future.

Best Regards,
Hideo Yamauchi.

**Comment by wenningerk** [comment]
Hi Ken, Hideo,

Guess timeouts when detecting a connection - respectively unresponsive daemon - are becoming an issue as well if we elaborate this. For interactive-mode that isn't an issue but if we finally would get a status but due to multiple timeouts checking for multiple daemons an RA operation might still timeout.
One of the reasons why I considered it preferable to have a go-to-instance that in the background checks cluster-node-health in a way that it tells us if all daemons are alive that are needed to have a database, start/stop/monitor-resources, make decisions, communicate with the other cluster-nodes ...
If we consider doing more elaborate checking in crm_mon of course the question arises why we wouldn't do that with other tools as well. Implementation wise that might lead to moving code from pacemakerd to a library. Or provide something for high-level-tools that might be composing a high-level-operation from multiple low-level tool invocations. Of course as well to consider in the light of moving low-level-tooling functionality to a library ...
^^^ Just a few unsorted thoughts coming to my mind that might still be of general interest when pushing that further ...

Klaus

**Comment by HideoYamauchi** [comment]
Hi Klaus,

I also care about resource agent timeouts as well.
I think it would be better to take a little more time to discuss and discuss various things.

Many thanks,
Hideo Yamauchi.

**Comment by wenningerk** [comment]
> Hi Klaus,
> 
> I also care about resource agent timeouts as well.
> I think it would be better to take a little more time to discuss and discuss various things.
Fully agreed! This is why I was just trying to bring up stuff coming to my mind - so that it is not forgotten and might serve as a base for discussion.
> 
> Many thanks,
> Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Klaus,

All right!

Thanks,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
> Hi Ken, Hideo,
> 
> Guess timeouts when detecting a connection - respectively unresponsive daemon - are becoming an issue as well if we elaborate this. For interactive-mode that isn't an issue but if we finally would get a status but due to multiple timeouts checking for multiple daemons an RA operation might still timeout.
> One of the reasons why I considered it preferable to have a go-to-instance that in the background checks cluster-node-health in a way that it tells us if all daemons are alive that are needed to have a database, start/stop/monitor-resources, make decisions, communicate with the other cluster-nodes ...

I think as long as pacemakerd is responding, then we don't have to check any other daemons if it tells us they are down. However if pacemakerd is not responding, it could have crashed and be respawning, and seeing what we could get from the others might be worthwhile. On the other hand, that would be a highly unusual situation and maybe not worth optimizing for.

> If we consider doing more elaborate checking in crm_mon of course the question arises why we wouldn't do that with other tools as well. Implementation wise that might lead to moving code from pacemakerd to a library. Or provide something for high-level-tools that might be composing a high-level-operation from multiple low-level tool invocations. Of course as well to consider in the light of moving low-level-tooling functionality to a library ...

I don't think any other tools need pacemakerd. Most only care about one subdaemon, and whether it's responding or not is sufficient status for their purposes. I think sbd only needs to care about pacemakerd, and as long as it is responsive before the sbd timeout it's fine.

> ^^^ Just a few unsorted thoughts coming to my mind that might still be of general interest when pushing that further ...
> 
> Klaus

**Pull request merged**
