### PR TITLE
Fix: tools: Don't display crm_resource error messages twice.

### PR DESCRIPTION
**Pull request by clumens**
Also, add the program name to any error prints that happen.  This brings
it in line with what crm_mon is doing.

### CODE REVIEW

**Comment by kgaillot** [comment]
Looks good. The CLI regression tests need updating for the expected output.

covscan is complaining too, but that's because Fabio upgraded the covscan version rather than anything related. We can look into that separately.

**Comment by clumens** [comment]
> Looks good. The CLI regression tests need updating for the expected output.

Yeah I just saw that.  I was thinking of stripping the `lt-` nonsense from the front of the output when we compare, just in case tests ever run on a platform where libtool is not involved.

**Comment by kgaillot** [comment]
> > Looks good. The CLI regression tests need updating for the expected output.
> 
> Yeah I just saw that. I was thinking of stripping the `lt-` nonsense from the front of the output when we compare, just in case tests ever run on a platform where libtool is not involved.

I thought we already did that ... the CLI and scheduler regression tests can be run from a checkout or from an install, so they need to cope with both.

**Comment by clumens** [comment]
> I thought we already did that ... the CLI and scheduler regression tests can be run from a checkout or from an install, so they need to cope with both.

I don't see anywhere that's being done.  I think this might just be working accidentally.

**Pull request merged**
