### PR TITLE
Fix migration regression

### PR DESCRIPTION
**Pull request by kgaillot**
The scenario is that a resource live-migrates twice, and the intermediate node has its history cleaned.

### CODE REVIEW

**Comment by kgaillot** [comment]
@nrwahl2 , can you review this regression fix?

@gao-yan , you may want to look it over too since you've dealt with a lot of corner cases in this code, to make sure I'm not introducing any (new or old) problems.

**Comment by nrwahl2** [comment]
It looks good on the first pass. I'm still reasoning through various scenarios for anything that might misbehave.

I'm surprised this only happens on a double migration and not a single one.

**Comment by kgaillot** [comment]
> It looks good on the first pass. I'm still reasoning through various scenarios for anything that might misbehave.
> 
> I'm surprised this only happens on a double migration and not a single one.

It probably does, this was just the scenario I found it in.

**Comment by nrwahl2** [comment]
We're probably good... And it probably applies only in the case of a double migration, since we're only touching a function that unpacks a successful `migrate_to` on a source node. The situation is simpler when the target of that operation is also the "final" target.

I've compiled some test scenarios into a gist for reference. See if anything looks "off."
https://gist.github.com/nrwahl2/18dffd766bb8de053a0d6d8486bcc066

**Comment by nrwahl2** [comment]
> I've compiled some test scenarios into a gist for reference. See if anything looks "off." https://gist.github.com/nrwahl2/18dffd766bb8de053a0d6d8486bcc066

The one concern that I remember having: If it's possible in that nodes 8-2 and 8-5 have both had their history cleared, while node 8-1 has not, then we'll end up (re)starting the resource on node 8-2 even if the resource finished migrating all the way to node 8-5 already (8-1 -> 8-2 -> 8-5).

**Comment by kgaillot** [comment]
> > I've compiled some test scenarios into a gist for reference. See if anything looks "off." https://gist.github.com/nrwahl2/18dffd766bb8de053a0d6d8486bcc066

Looks reasonable. Transition summaries don't show probes but I'm assuming they're scheduled when they should be.

BTW the fencing when rhel8-1 doesn't have a stop is because rhel8-1 is offline in this CIB, so nothing should be active on it.

> 
> The one specific concern that I remember having: If it's possible in that nodes 8-2 and 8-5 have both had their history cleared, while node 8-1 has not, then we'll end up (re)starting the resource on node 8-2 even if the resource finished migrating all the way to node 8-5 already (8-1 -> 8-2 -> 8-5).

If there's no history, hopefully a probe is scheduled before any other actions, and if the probe isn't as expected it will trigger a new transition.

**Comment by kgaillot** [comment]
Merging for now, we have plenty of time for more testing and corrections if needed

**Comment by gao-yan** [comment]
Good catch! And the fix makes sense to me.

> > The one specific concern that I remember having: If it's possible in that nodes 8-2 and 8-5 have both had their history cleared, while node 8-1 has not, then we'll end up (re)starting the resource on node 8-2 even if the resource finished migrating all the way to node 8-5 already (8-1 -> 8-2 -> 8-5).
> 
> If there's no history, hopefully a probe is scheduled before any other actions, and if the probe isn't as expected it will trigger a new transition.

Yes, I think so.

**Pull request merged**
