### PR TITLE
[WIP] Fix: build: add explicit BuildRequires for glibc-headers

### PR DESCRIPTION
**Pull request by wenningerk**

### CODE REVIEW

**Comment by wenningerk** [comment]
looks as if this isn't needed anymore with new gcc-12.0.1-0.4.fc36 that showed up in koji repo.

**Comment by kgaillot** [comment]
I think we would additionally need to tell CI to install the package in ci-update-\* in https://github.com/kronosnet/ci-tools

**Comment by kgaillot** [comment]
> I think we would additionally need to tell CI to install the package in ci-update-* in https://github.com/kronosnet/ci-tools

... if the problem shows up again. On my RHEL 8 system, glibc-headers is a dependency of glibc-devel which in turn is a dependency of gcc, so maybe one of those dependencies got lost in the new rawhide packages.

**Comment by wenningerk** [comment]
> > I think we would additionally need to tell CI to install the package in ci-update-* in https://github.com/kronosnet/ci-tools
> 
> ... if the problem shows up again. On my RHEL 8 system, glibc-headers is a dependency of glibc-devel which in turn is a dependency of gcc, so maybe one of those dependencies got lost in the new rawhide packages.

yep - guess that is what has happened there. seems to be gone.
so I guess we can close this one.
on fedora I put the dependency into the spec-file as to get it to recompile and I guess there it doesn't impose any issues as with suse where the package seems not to exist - at least not anymore.

**Pull request closed without merging**
