### PR TITLE
crm_resource --clear should print out what it does

### PR DESCRIPTION
**Pull request by clumens**
I am not sure if this is quite ready to be merged as-is.  In particular, I'm not really sure if it works with the -x option.  I don't know if what I'm doing with the second query and cluster_status is sufficient to pick up whatever has changed plus whatever was in the CIB to begin with from the input XML file.

On the other hand, that option is not documented so it seems like it's only really there just for test purposes.  It seems likely other command line options do not work correctly with it, too.

### CODE REVIEW

**Comment by kgaillot** [comment]
Looks good. Let's skip all the new code if --quiet was given. I'm guessing the cts-cli regression test output changed, so you'll need to update the reference output. I don't think anything that uses cib_conn directly (including the existing cli_resource_clear()) would work with -x, so we don't need to worry about it. The CIB_file environment variable should work transparently with cib_conn, so you might test that works.

**Comment by clumens** [comment]
Oh yes, the cts-cli regression test changed, but that changing did not fail the RPM build.  That's why I didn't do anything about it - I was counting on that failing.

**Comment by kgaillot** [comment]
> Oh yes, the cts-cli regression test changed, but that changing did not fail the RPM build. That's why I didn't do anything about it - I was counting on that failing.

cts-cli has two distinct ways of failing -- one is the tests not returning the expected codes, which will block the rpm, and the other is the command output being different from the reference output, which is displayed when you run the test manually, but doesn't block the rpm. That's bit me in the past too :)

**Comment by clumens** [comment]
CIB_file works like I was hoping it would.  Pushing a new version that does --quiet and fixes the test case.

**Pull request merged**
