### PR TITLE
High: Remember in CIB that we want to fence node

### PR DESCRIPTION
**Pull request by bubble75**
Otherwise in some circumstances node becomes clean at least if:
- fencing request was caused by a resource stop failure
- it was not satisfied before resource state cleanup (automatic or manual).

### CODE REVIEW

**Comment by bubble75** [comment]
Setting this attribute was removed by:

commit ec26f7fbaba29c72320f1d21e428dd11fbae1b66
Author: Andrew Beekhof <andrew@beekhof.net>
Date:   Mon Sep 26 18:53:11 2011 +1000

    High: controld: Convert crm_terminate_member...() to use stonith-ng directly instead of attrd->PE->crmd

**Comment by bubble75** [comment]
Well, I tested this commit and it actually makes everything work as I would expect. What I've done is:
* break fencing configuration for nodeA
* force resource failures (monitor and stop) for one resource on nodeA by modifying its RA to exit 1 on monitor and stop
* nodeA is marked UNCLEAN and "terminate" attribute is set to "true"
* modify RA back
* cleanup state of the failed resource on nodeA
* nodeA is still marked UNCLEAN, and fencing attempts continue
* fix fencing device for nodeA
* nodeA is fenced after some time
* resources move to another node

If I run 'stonith_admin -C nodeA' shortly after fixing fence resource, then crmd exits on that node and causes stop of all pacemaker daemons, nodeA is marked as 'pending'. That is what I would expect.

**Comment by bubble75** [comment]
Commit is updated to handle remote nodes as well.

**Comment by kgaillot** [comment]
I don't think this would fix the original problem.

If we get to te_fence_node(), we're already sending the fence request to stonithd, so we don't need to remember the need to do so. If I understand the original problem correctly, the PE recalculates a new transition (without a fence request) before the crmd finishes processing the original transition with the fence request. In such a case, the crmd will never see the fence request or therefore process it with te_fence_node().

Your test works because the transition with the fence request does complete, allowing the node unclean state to be recorded in the CIB, even though the fencing itself cannot complete at that point.

I think this will be trickier. Perhaps the crmd could check every transition for fence actions before processing it, and then handle them somehow if the transition is later aborted. However, I suspect that will require a good bit of intelligence, rather than simply execute all of them.

**Comment by bubble75** [comment]
@kgaillot You are correct, that wouldn't fix the original issue, but fixes another, even more evil one, which can easily be reproduced - that one in the PR description.

Concerning original issue - I plan to do some testing, poking with different op_timeout/failure_timeout settings. I believe it should be possible to choose failure_timeout so it covers the whole transition, not allowing to lose fencing event.

Additionally, I believe there was crmd crash when I saw the original issue, but I found that too late. I think that could be related to the incorrect behaviour. I plan to try to reproduce that issue next month.

**Comment by kgaillot** [comment]
I still don't understand how this would address what's in the description. If we get as far as te_fence_node(), the fence request will be sent to stonithd, so we don't need to bother remembering or reissuing it.

**Comment by bubble75** [comment]
And what then happens if stonithd fails to perform actual fencing? What I see is that failure is cleaned, PE thinks it is not longer UNCLEAN and allocates resources there. crmd performs the transition then...

**Comment by kgaillot** [comment]
If I understand correctly, the issue addressed here can only happen with failed fence actions, so I think it may be less intrusive to handle it in tengine_stonith_callback() (for the failure case) rather than te_fence_node(). That way, we're not exposing all fence actions to potential problems in the attribute handling.

However we handle it, we need to limit it to off/reboot actions. We could expose lib/pengine/common.c:check_stonith_action() as lib/common/utils.c:crm_is_kill_action(), as that would come in handy elsewhere.

The main advantage I see of using "terminate" is that the check for it is already there, which saves some coding and works with older versions in a rolling upgrade. However, I haven't traced through all the implications yet, particularly whether clearing it on first join (as is done currently) is sufficient in all cases. I'm also unsure what timing issues might arise between crmd, pengine, stonithd, attrd, and cib with this method. If we used a new node_state attribute instead, that would at least take attrd out of the equation.

**Comment by kgaillot** [comment]
Due to the code base divergence since this PR, and the questions remaining about the implementation, I've moved this to a new bug report https://bugs.clusterlabs.org/show_bug.cgi?id=5476

**Pull request closed without merging**
