### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by wferi**
While packaging Pacemaker 1.1.13 for Debian, I had to add the following patches. The first two (adding `-lm` to `libcrmcommon_la_LIBADD` and various libs to `libpengine_la_LIBADD`) were outright stopping the build, the first with

    libtool: link: gcc -shared  -fPIC -DPIC  .libs/compat.o .libs/digest.o .libs/ipc.o .libs/io.o .libs/utils.o .libs/xml.o .libs/iso8601.o .libs/remote.o .libs/mainloop.o .libs/logging.o .libs/watchdog.o .libs/md5.o   -lgnutls -lcorosync_common /usr/lib/libplumb.so /usr/lib/libpils.so -lbz2 -lxslt -lxml2 -lc -luuid -lpam -lglib-2.0 /usr/lib/x86_64-linux-gnu/libltdl.so -lqb -ldl -lrt -lpthread  -O2 -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z -Wl,defs   -Wl,-soname -Wl,libcrmcommon.so.3 -o .libs/libcrmcommon.so.3.4.0
    .libs/xml.o: In function `__xml_build_schema_list':
    /«PKGBUILDDIR»/lib/common/xml.c:379: undefined reference to `floorf'
    /«PKGBUILDDIR»/lib/common/xml.c:379: undefined reference to `floorf'
    .libs/xml.o: In function `xml_minimum_schema_index':
    /«PKGBUILDDIR»/lib/common/xml.c:165: undefined reference to `floorf'
    collect2: error: ld returned 1 exit status
    make[4]: *** [libcrmcommon.la] Error 1
    Makefile:601: recipe for target 'libcrmcommon.la' failed

and the second with

    libtool: link: gcc -shared  -fPIC -DPIC  .libs/pengine.o .libs/allocate.o .libs/utils.o .libs/constraints.o .libs/native.o .libs/group.o .libs/clone.o .libs/master.o .libs/graph.o .libs/utilization.o   -Wl,-rpath -Wl,/«PKGBUILDDIR»/lib/pengine/.libs -Wl,-rpath -Wl,/«PKGBUILDDIR»/lib/cib/.libs ../lib/pengine/.libs/libpe_status.so ../lib/cib/.libs/libcib.so -lgnutls -lcorosync_common /usr/lib/libplumb.so /usr/lib/libpils.so -lbz2 -lxslt -lxml2 -lc -luuid -lpam -lglib-2.0 /usr/lib/x86_64-linux-gnu/libltdl.so -lqb -ldl -lrt -lpthread  -O2 -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z -Wl,defs   -Wl,-soname -Wl,libpengine.so.4 -o .libs/libpengine.so.4.4.0
    .libs/pengine.o: In function `do_calculations':
    /«PKGBUILDDIR»/pengine/pengine.c:223: undefined reference to `crm_is_callsite_active'
    /«PKGBUILDDIR»/pengine/pengine.c:238: undefined reference to `crm_is_callsite_active'
    /«PKGBUILDDIR»/pengine/pengine.c:245: undefined reference to `crm_is_callsite_active'
    /«PKGBUILDDIR»/pengine/pengine.c:248: undefined reference to `crm_is_callsite_active'
    /«PKGBUILDDIR»/pengine/pengine.c:251: undefined reference to `crm_is_callsite_active'
    .libs/pengine.o:/«PKGBUILDDIR»/pengine/pengine.c:254: more undefined references to `crm_is_callsite_active' follow
    .libs/pengine.o: In function `do_calculations':
    /«PKGBUILDDIR»/pengine/pengine.c:265: undefined reference to `get_crm_log_level'
    [lots of other similar lines]

These errors are so obvious that we surely do something differently, otherwise you'd caught them. So maybe the patches fixing them aren't correct actually, but they demonstrate a solution at least.

The others are not show-stoppers, but look worth fixing regardless. Please consider incorporating them.

As I plan to submit other patches (mostly fixing various typos spotted by the Debian QA tools), please explain how you prefer receiving them. For example, do you need and want signoffs on the offered patches, or should I just leave them out?

Thanks,
Feri.

### CODE REVIEW

**Comment by beekhof** [comment]
The only one that is odd to me is:

    +	$(top_builddir)/lib/cib/libcib.la ../lib/common/libcrmcommon.la -lqb -lglib-2.0 -lxml2

The cib library links against all those (either directly or indirectly) so there should be no need to repeat them here.

What compiler version and compiler options are you using?

**Comment by wferi** [comment]
Well, `gcc --version` outputs `gcc (Debian 5.2.1-17) 5.2.1 20150911` here.
But my experiments show that `-Wl,-z,defs` necessitates repeating the libraries for me. The use of this flag is [encouraged](https://www.debian.org/doc/debian-policy/ch-files.html#s-libraries) by the Debian Policy Manual:

> Although not enforced by the build tools, shared libraries must be linked against all libraries that they use symbols from in the same way that binaries are. This ensures the correct functioning of the symbols and shlibs systems and guarantees that all libraries can be safely opened with dlopen(). Packagers may wish to use the gcc option -Wl,-z,defs when building a shared library. Since this option enforces symbol resolution at build time, a missing library reference will be caught early as a fatal build error.

If I read it correctly, this helps to avoid various problems by making the dynamic link requirements explicit in every produced object.

**Comment by beekhof** [comment]
To be honest, those options don't sound very appealing - more like a solution in search of a problem.
If you can drop that part I'll merge everything else.

**Comment by wferi** [comment]
Yes, it's a QA tool for finding problems which may be irrelevant for your code base.
I've rebased against the current master and dropped the `libpengine.la` patch.

**Pull request merged**
