### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by kgaillot**
A bit of cleanup before the 2.1.7 release

### CODE REVIEW

**Comment by kgaillot** [comment]
@waltdisgrace , can you review this when you get a chance? Thanks :)

**Comment by kgaillot** [comment]
rebased on current main to resolve conflict

**Comment by kgaillot** [comment]
rebased on current main to resolve conflict

**Comment by waltdisgrace** [comment]
> @waltdisgrace , can you review this when you get a chance? Thanks :)

Looks good to me.

**Pull request merged**
