### PR TITLE
Improvements to crm_mon output

### PR DESCRIPTION
**Pull request by kgaillot**
Slight refactoring to make plain, XML and HTML outputs behave more consistently

### CODE REVIEW

**Comment by kgaillot** [comment]
Forgot to add in commit mesage for 6b9f470 that it also changes (fixes) behavior in one other corner case: if "--group-by-node --inactive --brief" are all specified, an inactive group will now correctly be displayed briefly rather than in long format.

**Comment by kgaillot** [comment]
af0f407 needs some discussion. Previously, the plaintext/HTML outputs would print node name sometimes  as uname only, sometimes as uname:containerID and sometimes as uname (nodeID). This revision makes it more consistent as uname:containerID (nodeID) (:containerID is only printed for container remote nodes, and (nodeID) is only printed if different from uname, as was the case previously).

(As a side note, the new function is intended for human-friendly display, so the XML output does not use it. However this revision does modify the XML output to add the container ID as an attribute when appropriate.)

I think the new format is definitely appropriate in the DC header, group-by-node headings, and node attribute headings.

I did *not* use the new format in the clone Started/Stopped lists as I felt it was not appropriate there, although perhaps containerID would be important for container nodes?

I *did* use the new format in lists of Online/Offline/etc. nodes. I'm not sure whether that's a good idea or not, and it's the most visible behavioral change to users.

The question is, when is it important to see whether node ID is different from uname, and when is it important to see a container ID?

Example output:

# crm_mon -1A
Last updated: Thu Mar 19 11:28:11 2015
Last change: Thu Mar 19 11:20:24 2015
Stack: corosync
Current DC: rhel7-3 (3) - partition with quorum
Version: 1.1.12-af0f407
3 Nodes configured
8 Resources configured


Online: [ rhel7-1 (1) rhel7-2 (2) rhel7-3 (3) ]

 Fencing	(stonith:fence_xvm):	Started rhel7-1 
 rsc_rhel7-1	(ocf::heartbeat:IPaddr2):	Started rhel7-1 
 Clone Set: Connectivity [ping-1]
     Started: [ rhel7-1 rhel7-2 ]
     Stopped: [ rhel7-3 ]
 Resource Group: dummy_group
     dummy1	(ocf::pacemaker:Dummy):	Started rhel7-3 
     dummy2	(ocf::pacemaker:Dummy):	Started rhel7-3 
     dummy3	(ocf::pacemaker:Dummy):	Started rhel7-3 

Node Attributes:
* Node rhel7-1 (1):
    + #cluster-name                   	: mycluster 
    + #site-name                      	: mycluster 
    + connected                       	: 1         
* Node rhel7-2 (2):
    + #cluster-name                   	: mycluster 
    + #site-name                      	: mycluster 
    + connected                       	: 1         
* Node rhel7-3 (3):
    + #cluster-name                   	: mycluster 
    + #site-name                      	: mycluster

**Comment by beekhof** [comment]
> I did not use the new format in the clone Started/Stopped lists as I felt it was not appropriate there

Correct.  Its enough to just mention it once prior to the resources section.

> although perhaps containerID would be important for container nodes?

?

> The question is, when is it important to see whether node ID is different from uname

Its always different for cman and corosync.  Only show it if people specify --show-detail (I know its a clone option, we can make it do other things too).

> and when is it important to see a container ID?

For now, always.

**Comment by kgaillot** [comment]
Request has been amended per review.
* strnow() is now crm_now_string()
* get_node_display_name() now prints node ID only if --show-detail was specified

Re: container IDs, the question is whether container IDs should be displayed in clone started/stopped lists, for example in:

 Clone Set: Connectivity [ping-1]
     Started: [ rhel7-1 rhel7-2 ]

Should the "rhel7-1" be "rhel7-1:containerID" if it is a remote container node? If so, I need to modify the clone print method as well as crm_mon. As it stands now, the container ID will not be printed here, but it will be printed everywhere else (Online/Offline lists, group-by-node headings, node attribute headings).

As an aside, crm_mon's options are a bit disjointed. Someone can say "crm_mon --brief --show-detail" and that is not only allowed but makes sense for turning certain parts of the display on and off. I'm not sure what the best approach would be, but maybe something like "--display=ITEM,..." for fine-grained control of what is displayed, and options like "--brief" would become shorthand for certain ITEMs.

**Comment by beekhof** [comment]
> Should the "rhel7-1" be "rhel7-1:containerID" if it is a remote container node? If so, I need to modify the clone print method as well as crm_mon. As it stands now, the container ID will not be printed here, but it will be printed everywhere else (Online/Offline lists, group-by-node headings, node attribute headings).

If the container is a remote node, then it should show `containerID` only.
Otherwise, I think `rhel7-1` should be sufficient.

> As an aside, crm_mon's options are a bit disjointed. Someone can say "crm_mon --brief --show-detail" and that is not only allowed but makes sense for turning certain parts of the display on and off. I'm not sure what the best approach would be, but maybe something like "--display=ITEM,..." for fine-grained control of what is displayed, and options like "--brief" would become shorthand for certain ITEMs.

That sounds like an interesting approach

**Comment by kgaillot** [comment]
On 03/25/2015 07:32 PM, Andrew Beekhof wrote:
>> Should the "rhel7-1" be "rhel7-1:containerID" if it is a remote container node? If so, I need to modify the clone print method as well as crm_mon. As it stands now, the container ID will not be printed here, but it will be printed everywhere else (Online/Offline lists, group-by-node headings, node attribute headings).
> 
> If the container is a remote node, then it should show `containerID` only.
> Otherwise, I think `rhel7-1` should be sufficient.

I misunderstood what containerID is in this context -- I assumed it was
a Docker container ID, but actually it's the resource ID of the resource
that created the remote guest (VM or container). For example

   pcs resource create vm-guest1 VirtualDomain
      hypervisor="qemu:///system" config="/root/guest1.xml"
      meta remote-node=guest1

would be displayed as "guest1:vm-guest1".

After discussing with David, he suggested a better approach might be to
display the guest uname with the underlying host uname. So maybe
"guest1@host1".

>> As an aside, crm_mon's options are a bit disjointed. Someone can say "crm_mon --brief --show-detail" and that is not only allowed but makes sense for turning certain parts of the display on and off. I'm not sure what the best approach would be, but maybe something like "--display=ITEM,..." for fine-grained control of what is displayed, and options like "--brief" would become shorthand for certain ITEMs.
> 
> That sounds like an interesting approach

Do you want me to spend any more time on crm_mon now? I don't mind, I
saw lots of low-hanging fruit, but I don't know how you want to
prioritize it.

**Comment by beekhof** [comment]
"guest1@host1" is fine by me (for the non-xml output)

> Do you want me to spend any more time on crm_mon now?

Sure. Might as well do the xml schema while you're there too.

**Pull request merged**
