### PR TITLE
Fix init script return status

### PR DESCRIPTION
**Pull request by ChristophBerg**
In the original variant, function status() overwrite $rtrn 'in global
scope' which leads to a pretended failing stop() function and
respectively failing initscript when called with action stop.

References: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=686548
Signed-off-by: Christian Schneider <christian.schneider@aoe.com>
Signed-off-by: Christoph Berg <myon@debian.org>

### CODE REVIEW

**Comment by kgaillot** [comment]
Good catch. To be extra safe, can you make it a local variable?

**Comment by ChristophBerg** [comment]
Sure. I have meetings today but will follow up soon.

**Comment by jnpkrn** [comment]
+1 for `local`

Perhaps `shellcheck` will advise it automatically, one day:
https://github.com/koalaman/shellcheck/issues/213

**Comment by jnpkrn** [comment]
And perhaps this is important enough to include it in `1.1.15` release.
In that case, PR against `1.1` branch would be needed:
http://oss.clusterlabs.org/pipermail/developers/2016-April/000202.html

**Comment by ChristophBerg** [comment]
Apparently github doesn't allow to change the target branch for a PR, I'll open a new one: #996

**Comment by jnpkrn** [comment]
Yes, unfortunately.  There's unofficial and not paid-attention-to tracking of this deficiency dating back to 2013:
https://github.com/isaacs/github/issues/18

**Pull request closed without merging**
