### PR TITLE
(WIP) Display completed failed fencing actions in a separate section.

### PR DESCRIPTION
**Pull request by HideoYamauchi**
Hi Ken,
Hi wenningerk,

This PR reflects the following Mr. Ken's opinion, but section names are not complete, so please wait for merging.
 - https://github.com/ClusterLabs/pacemaker/pull/1790#issuecomment-518067266

As for this patch, it is also in the opinion of our members below, but it may be better to incorporate it with another option (m4?).
Also, the section name to be displayed should be a slightly nicer name.

And,Let me discuss a little more....

In the PR I wrote earlier, I said there were opinions from the members.

The opinion is as follows.

Opinion 1)
Adding a new section([Previously Failed Fencing Actions No Longer Needed]) may cause more confusion to the user.

Opinion 2)
Can the default option be changed to m2? Then, the actions displayed in “Failed Fencing Actions” are also displayed in “Fencing History” after success.
However, I think it is difficult because it has already been released as I wrote before. What do you think?

Opinion 3)
If m0 is displayed, is it possible to display it in another section after successfully displaying the displayed "Pending Fencing Actions"?
However, I think this is impossible because it cannot be determined that the completed action is a pending action.
It also contradicts the opinion that adding the previous section is confusing.

What do you think?

Best Regards,
Hideo Yamauchi.

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi Hideo,

Maybe instead of a separate section, we could change how the actions are described in the list. Something like:

    Failed Fencing Actions:
    * reboot of node1 failed: delegate=...
    * reboot of node2 (no longer needed) failed: delegate=...

**Comment by HideoYamauchi** [comment]
Hi Ken,

Thanks for your comment.

> Maybe instead of a separate section, we could change how the actions are described in the list. Something like:
> 
> ```
> Failed Fencing Actions:
> * reboot of node1 failed: delegate=...
> * reboot of node2 (no longer needed) failed: delegate=...
> ```

This display looks good to me.
I will consider it with the members.

@wenningerk : What do you think?

Best Regards,
Hideo Yamauchi.

**Comment by wenningerk** [comment]
> @wenningerk : What do you think?
> 
> Best Regards,
> Hideo Yamauchi.

I'm usually voting for an output that is very structured like e.g. in columns so that you can quickly see if anything changed and how that is clustered.
The '(no longer needed)' breaks that a little.
While keeping the column-structure and not introducing a new section I'm thinking of how something like the following would look like:
Failed Fencing Actions:
```
* reboot of node1 failed: delegate=...
--- no longer needed (superseded by successful fence action) ---
* reboot of node2 failed: delegate=...
* reboot of node2 failed: delegate=...
```

**Comment by kgaillot** [comment]
I don't think crm_mon works very well with columns since the different values may have different lengths, and some of them are optional. Also, I find the "---" line to be unclear which entry it applies to.

Maybe we could add another name=value field, but I'm not sure what to call it. superseded=true would be correct, but it's not as obvious what that means.

Thinking about it again, "no longer needed" is probably not the best wording either, since it may have been superseded by successful fencing, but then a new failure requires more fencing.

Maybe "reboot of node1 failed but later succeeded:"?

**Comment by wenningerk** [comment]
Well, yes you have a little shifting but the eye seems to compensate for that well enough - doesn't mean we couldn't/shouldn't improve the column appearance.
A more verbose output is anyway in discussion / in the works.
So a possibility would be to use your suggestion "reboot of node1 failed but later succeeded:" in the more verbose output.
I'm as well Ok for the more verbose output to become the default.

**Comment by HideoYamauchi** [comment]
Hi Ken,
Hi wenningerk,

Thanks for your comment.
When we summarize the opinions of both people, we will change to the following display.
How about it?

```
Failed Fencing Actions:
* reboot of node1 failed: delegate=...
* reboot of node1 failed but later succeeded: delegate=...
```

@wenningerk :
> I'm as well Ok for the more verbose output to become the default.
Does this mean that the opinion from our members to change the default to m2 is acceptable?

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

> Hi Ken,
> Hi wenningerk,
> 
> Thanks for your comment.
> When we summarize the opinions of both people, we will change to the following display.
> How about?
> 
> ```
> Failed Fencing Actions:
> * reboot of node1 failed: delegate=...
> * reboot of node1 failed but later succeeded: delegate=...
> ```

That works for me.

> @wenningerk :
> 
> > I'm as well Ok for the more verbose output to become the default.
> 
> Does this mean that the opinion from our members to change the default to m2 is acceptable?

Actually, Klaus was referring to an unrelated proposal, to change the display from name=value pairs to natural language. See RHBZ #1373981 and #1470834.
 
> Best Regards,
> Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,
Hi wenningerk,

> Hi Hideo,
> 
> > Hi Ken,
> > Hi wenningerk,
> > Thanks for your comment.
> > When we summarize the opinions of both people, we will change to the following display.
> > How about?
> > ```
> > Failed Fencing Actions:
> > * reboot of node1 failed: delegate=...
> > * reboot of node1 failed but later succeeded: delegate=...
> > ```
> 
> That works for me.

I will discuss with the members the idea of this display tomorrow.

> > @wenningerk :
> > > I'm as well Ok for the more verbose output to become the default.
> > 
> > 
> > Does this mean that the opinion from our members to change the default to m2 is acceptable?
> 
> Actually, Klaus was referring to an unrelated proposal, to change the display from name=value pairs to natural language. See RHBZ #1373981 and #1470834.

All right!

Many thanks,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,
Hi wenningerk,

Our members agreed with the display of this crm_mon.

```
Failed Fencing Actions:
* reboot of node1 failed: delegate=...
* reboot of node1 failed but later succeeded: delegate=...
```

I will re-create the PR for this display.

Best Regards,
Hideo Yamauchi.

**Pull request closed without merging**
