### PR TITLE
Return error instead of "not running" for failed systemd starts

### PR DESCRIPTION
**Pull request by kgaillot**
Fixes CLBZ#5383

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi @HideoYamauchi , could you please review and test this to make sure it corrects your issue?

**Comment by HideoYamauchi** [comment]
Hi Ken,

Okay!

Many thanks,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Great!

I reviewed your PR and confirmed the improvement of the issue.
The issue is improved with this PR.

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Thanks for finding and testing the issue!

**Comment by HideoYamauchi** [comment]
Thanks!

**Pull request merged**
