### PR TITLE
Backport of clone shuffling fix to 2.1.6 (not for merging)

### PR DESCRIPTION
**Pull request by nrwahl2**
This is a backport of the clone shuffling portion of https://github.com/ClusterLabs/pacemaker/pull/3137 to 2.1.6, to resolve T489 and RHBZ#1931023.

This aims to be the minimal set of changes necessary to resolve RHBZ#1931023. Note that this does **not** fix promotable bundle colocations, which is the second half of #3137. The clone shuffling fix breaks the `cancel-behind-moving-remote` test, and the promotable bundle colocations fix would restore it to its initial output.

However, `cancel-behind-moving-remote` was never a robust test. The colocation applied only very indirectly, due to assignment order and lack of any other constraints or promotion scores that might have caused a different promotion priority.

Backporting the promotable bundle colocation fix would probably be quite a bit more complicated. There are probably a lot of function name changes, functionizations, etc., to account for. So I haven't done that yet. If we don't want to ship this without the colocation fix, I'll work on it and see how complicated it turns out to be.

### CODE REVIEW

**Comment by nrwahl2** [comment]
None of the new Coverity errors look like code that I touched in this PR.

**Comment by nrwahl2** [comment]
Converted to draft so that I don't accidentally kick off another build while CI maintenance is in progress.

**Comment by clumens** [comment]
This applies cleanly and scratch builds.  I have not run it through tests yet nor looked at everything line-by-line.

**Comment by clumens** [comment]
You can close this if you want.  I've added it to builds.  Thanks.

**Pull request closed without merging**
