### PR TITLE
High: fenced: Wrong device may be selected when "dynamic-list" is specified.(Fix:CLBZ#5474) 

### PR DESCRIPTION
**Pull request by HideoYamauchi**
Hi Ken,
Hi All,

This PR will be a re-correction of the next PR.
 - https://github.com/ClusterLabs/pacemaker/pull/2410

Best Regards,
Hideo Yamauchi.

### CODE REVIEW

**Comment by HideoYamauchi** [comment]
Hi Ken,

This fixed bug is quite a problem in the Japanese community.
Our users have RHEL8.4 N-node configuration and cannot use pcmk_host_check = "dynamic-list" and pcmk_host_map.

Do you know how to get RHEL to issue an errata?

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
> Hi Ken,
> 
> This fixed bug is quite a problem in the Japanese community.
> 
> Our users cannot use the combination of pcmk_host_check = "dynamic-list" and pcmk_host_map in the N-node configuration of the virtual environment.
> 
> Many users in our community use the pacemaker that comes with RHEL 8.4.
> We think I need RHEL's Errata for improvement.
> 
> Do you know how to get RHEL to issue an errata?
> 
> Best Regards,
> Hideo Yamauchi.

Hi Hideo,

I want to make sure I understand the problem space correctly. I believe the problem occurs only under these circumstances:

* A fence device is configured that can target at least one node in the cluster, but not all of them
* The device is configured with pcmk_host_check="dynamic-list" and a pcmk_host_map that lists not only the nodes that it can target, but other nodes as well
* Fencing is required for one of the nodes that is listed in pcmk_host_map but is not fenceable by the device
* The fence agent's list action fails, causing it to wrongly report that it can fence all the nodes in pcmk_host_map, and Pacemaker selects it to fence the target

Is that correct?

**Comment by HideoYamauchi** [comment]
Hi Ken,

Thanks for your comment.

> * A fence device is configured that can target at least one node in the cluster, but not all of them
> * The device is configured with pcmk_host_check="dynamic-list" and a pcmk_host_map that lists not only the nodes that it can target, but other nodes as well
> * Fencing is required for one of the nodes that is listed in pcmk_host_map but is not fenceable by the device
> * The fence agent's list action fails, causing it to wrongly report that it can fence all the nodes in pcmk_host_map, and Pacemaker selects it to fence the target
>  Is that correct?

That's right.

The detailed settings are as written in Bugzilla, but you are aware of it.
The user needs to execute the "list" command on the device in the N-node configuration of the virtual environment to perform fencing by matching with pcmk_host_map with fence_agent that has a reliable fencing route.

Best Regards,
Hideo Yamauchi.

**Comment by wenningerk** [comment]
In scenarios as the one described above I assume the "dynamic-list" really means dynamic in a way that the answer of supported nodes changes over time.
Just as I'm thinking of it ... there is still the 60s hard-coded caching time that might lead to device-selection based on outdated data ...

**Comment by kgaillot** [comment]
> In scenarios as the one described above I assume the "dynamic-list" really means dynamic in a way that the answer of supported nodes changes over time.
> Just as I'm thinking of it ... there is still the 60s hard-coded caching time that might lead to device-selection based on outdated data ...

Sure, but that's the trade-off of caching. We could potentially make the caching time be the smaller of 60s or the list/status timeout.

**Comment by wenningerk** [comment]
Just wanted to raise awareness for the caching and that that could cause a similar issue as the one described.

**Comment by kgaillot** [comment]
> Hi Ken,
> 
> Thanks for your comment.
> 
> > * A fence device is configured that can target at least one node in the cluster, but not all of them
> > * The device is configured with pcmk_host_check="dynamic-list" and a pcmk_host_map that lists not only the nodes that it can target, but other nodes as well
> > * Fencing is required for one of the nodes that is listed in pcmk_host_map but is not fenceable by the device
> > * The fence agent's list action fails, causing it to wrongly report that it can fence all the nodes in pcmk_host_map, and Pacemaker selects it to fence the target
> >   Is that correct?
> 
> That's right.
> 
> The detailed settings are as written in Bugzilla, but you are aware of it.
> The user needs to execute the "list" command on the device in the N-node configuration of the virtual environment to perform fencing by matching with pcmk_host_map with fence_agent that has a reliable fencing route.
> 
> Best Regards,
> Hideo Yamauchi.

Hi Hideo,

I've opened a RHEL 8.5 bug for the issue:  https://bugzilla.redhat.com/show_bug.cgi?id=1978010

If any of your users can open a support case and mention that bz, it will be more likely to be approved. They can also ask for a RHEL 8.4 errata at that time if desired.

**Comment by HideoYamauchi** [comment]
Hi ken,

Thanks for your comment.

> 
> I've opened a RHEL 8.5 bug for the issue: https://bugzilla.redhat.com/show_bug.cgi?id=1978010
> 
> If any of your users can open a support case and mention that bz, it will be more likely to be approved. They can also ask for a RHEL 8.4 errata at that time if desired.

Great!
As you told me, I'll create a support case and request an Errata for Bugzilla.

Many thanks,
Hideo Yamauchi.

**Pull request merged**
