### PR TITLE
Fix: libstonithd: avoid controld shutdown hanging

### PR DESCRIPTION
**Pull request by wenningerk**
regression introduced with
'Allow removing all registered callbacks at once.'

### CODE REVIEW

**Comment by wenningerk** [comment]
This isn't necessarily beautiful but probably probably the least intrusive and most compact approach ;-)

**Comment by wenningerk** [comment]
@clumens:
Can you pls. have a look.
It seems to solve controld hanging on shutdown - at least on my cluster.
The issue was obfuscated by the short before introduced subdaemon-observation
feature that catches controld not being reactive via ipc and thus sends a KILL
after some timeout. Pacemaker-log shows pacemakerd trying to contact
controld 5 times without success and finally it sends a KILL.

**Comment by kgaillot** [comment]
This makes sense to me, though I'm not sure how the original code caused problems with existing callers

**Comment by wenningerk** [comment]
> This makes sense to me, though I'm not sure how the original code caused problems with existing callers

Didn't track it down explicitly but would expect some race between fenced disconnecting and controld shutting down itself.
In any case doing the deleting with refcnt > 0 is doomed as nothing is being deleted from the list and it thus is never getting empty.

**Comment by clumens** [comment]
Looks fine to me.

**Pull request merged**
