### PR TITLE
Cts script

### PR DESCRIPTION
**Pull request by jnpkrn**
Brushing up `cts` script (and related files: `cluster-helper`, ...).

### CODE REVIEW

**Comment by beekhof** [comment]
If you remove 704eecb I can apply the rest

**Comment by jnpkrn** [comment]
It's definitely nothing fashionable, but at least allows one to keep the help screen and the actual supported opts/args in sync (maintainability) and I thought this was a good choice provided that majority of immediate handlers were just storing a flag for later use.  Should I compact the help screen to a single `cat <<EOF` then?

**Comment by beekhof** [comment]
Yes please

**Comment by jnpkrn** [comment]
704eecb substituted for 08e01c8 and 562e09a, rest is the same.

**Comment by kgaillot** [comment]
I've never used cluster-init (or the cts script that calls it), but it looks like it should be either deleted or more thoroughly updated. It references the obsolete clusterlabs.org repo, always uses service/chkconfig rather than systemctl, has probably unnecessary support for obsolete components openais/heartbeat/pacemaker1.0, and doesn't offer the ability to install from local rpms, which is a common CTS use case.

**Comment by jnpkrn** [comment]
Hm, it's not easy to see what's fully abandoned/replaced with something better, or just became out the date for the lack of interest.

**Comment by kgaillot** [comment]
Yes, it's an issue particularly with CTS because it's not widely used outside of pacemaker developers. Things get added to it but rarely removed. Personally I have my own script that calls CTSlab.py directly, and David used phd to create test clusters.

**Comment by beekhof** [comment]
The `cts` and `cluster-init` scripts are what I use. They work for me :-)

**Pull request merged**
