### PR TITLE
wd: Correction to do to change action of the system reboot by fail_fast

### PR DESCRIPTION
**Pull request by yuusuke**
Hi All,

We want to allow us to change action when we reboot in fail_fast and sbd so that panic rises.
Because I want to acquire information at the time of these actions using kdump.

I want you to merge it because we want to use this feature from Pacemaker-1.1.14.

### CODE REVIEW

**Comment by beekhof** [comment]
You'll never reach this code if sbd is around (and if you're interested in this kind of logic, it should be), its merely a last resort.

**Comment by yuusuke** [comment]
Hi, Andrew
Thanks to reply.

I have reviewed the code again.
If sbd is being used, pcmk_panic_local () is in the normal flow was not called.
I'm sorry confirmation is not enough.

Since we believe that want to leave the information at the time of fail_fast, it was fixed commit message.

**Comment by kgaillot** [comment]
We're inclined not to clutter the pacemaker options with something of limited interest. This would only be relevant when sbd is not in use, and if this functionality is important to someone, they should probably be using sbd.

**Comment by yuusuke** [comment]
Hi, Ken
We do not plan to use the SBD at the moment.

If we do not use the SBD, Is there a way to store information about failure when fail_fast occurs by a process failure?

When the previous fail_fast occurs, immediately before the log message to restart had been saved.
However, since the sync() has been deleted by the following changes, we will not be able to save the current log.
https://github.com/ClusterLabs/pacemaker/commit/797b98431d0d6f8a65c53586d046f76ef5bdd16f

**Comment by beekhof** [comment]
You could add a sync() call before the call to sysrq_trigger('b') in pcmk_panic_local().
Beware though, that sync() call may never return which increases (potentially indefinitely) the period during which services may be running amok.

**Comment by yuusuke** [comment]
Hi, Andrew
Thanks for reply.

As you say, it will give up the adoption because it seems there is a risk in sync().
Instead, we are considering to use the SBD.
Are there any document for using SBD somewhere?

**Comment by beekhof** [comment]
There must be, somewhere...

On RHEL you can configure it with `pcs` and there is some useful information in https://bugzilla.redhat.com/show_bug.cgi?id=1221680 (when it comes back online)

**Comment by yuusuke** [comment]
Hi, Andrew and Ken
I used the SBD. However , I was not able to store log when fail_fast occurred .

I am the following settings to rsyslog.
$ OMFileAsyncWriting on
$ OMFileFlushInterval 5

By this setting , rsyslog buffers log for five seconds .

pacemakerd when fail_fast occurs it will kill the sbd (inquisitor).
sbd (watcher) is to reboot the system to detect the stop of the inquisitor.

In this case, we want to save the log has been accumulated in the buffer of rsyslog.
The system will be reboot before it is written to disk.

We have thought that you can not resolve the problem in the SBD.
I instead, before performing a reboot of the system by fail_fast, I made the correction to be added the delay specified by the user.
https://github.com/yuusuke/pacemaker/commit/2131231e05b302080abe11213f12dff46271dd05

I want you to merge this implementation .

Regards

**Comment by kgaillot** [comment]
Hi Yuusuke,

That sounds good. Please submit a new pull request with the desired patch. Let's rename the variable to PCMK_panic_delay, because it's not actually specific to fail_fast. We can comment that it applies whenever Pacemaker would panic the local node.

**Comment by kgaillot** [comment]
I would prefer to more broadly address the issue of losing logs due to fencing or panic, but since that is a tricky problem without a lot of resources to dedicate to it at the moment, I'm reopening this as a useful workaround in the meantime.

**Comment by yuusuke** [comment]
Merged Thank you!

**Pull request merged**
