### PR TITLE
low: xml: XML attribute improvements

### PR DESCRIPTION
**Pull request by waltdisgrace**
- improve efficiency by swapping crm_element_value() with pcmk__xml_attr_value() where possible

- seaparate functions that operate on xmlAttr ino xml_attr.c

closes T583

### CODE REVIEW

**Review by kgaillot — COMMENTED** [review]
Forgot to git add xml_attr.c :)

Do the new file in a separate commit from the code changes (either one can be first)

Prefix the newly exposed functions with `pcmk__`

I think xml_diff_old_attrs(), mark_created_attrs(), add_xml_changes_to_patchset(), process_v1_additions(), apply_v2_patchset(), subtract_xml_object(), show_xml_changes_recursive(), unpack_ticket_state(), unpack_operation(), and attrd_copy_xml_attributes() can use the convenience function too

**Review by kgaillot — COMMENTED** [review]
Looks good. Remember to prefix the newly non-static functions with `pcmk__`

**Review by kgaillot — COMMENTED** [review]
Looks good.

BTW, some of the efficiency changes are in the "Separate XML" commit -- not essential to reorganize those but you can if you want.

**Review by kgaillot — APPROVED** [review]

**Comment by waltdisgrace** [comment]
> BTW, some of the efficiency changes are in the "Separate XML" commit -- not essential to reorganize those but you can if you want.

Reorganized!

**Review by kgaillot — APPROVED** [review]

**Comment by kgaillot** [comment]
retest this please

**Pull request merged**
