### PR TITLE
Fix: liblrmd: Avoid double-free during notify operation

### PR DESCRIPTION
**Pull request by nrwahl2**
This commit fixes a regression introduced by 31c7fa8a, causing a
double-free in notify operations. lrmd_dispatch_internal() assigns the
exit_reason string directly from an XML node to a new lrmd_event_data_t
object (without duplicating), and this string gets freed twice.

Free #1: pcmk__create_history_xml() (reached via callback) calls
lrmd__set_result(), which frees event.exit_reason and sets it to NULL.
Free #2: lrmd_ipc_dispatch() frees the XML node, which contains a
pointer to the exit_reason string just freed, after
lrmd_dispatch_internal() returns.

Prior to 31c7fa8a, pcmk__create_history_xml reset event.rc and
event.op_status but **not** event.exit_reason.

In this commit we simply make a copy of event.exit_reason in
lrmd_dispatch_internal() before the callback. This way we don't have to
worry about whatever happens in the callback, and we can continue to
unset the exit_reason alongside the rc and op_status. The added overhead
should be minimal.

This commit also makes a copy of output. That's not strictly necessary
but adds some futureproofing and allows us to call lrmd__reset_result()
at the end of lrmd_dispatch_internal().

Resolves: RHBZ#2039675

Signed-off-by: Reid Wahl <nrwahl@protonmail.com>

### CODE REVIEW

**Comment by nrwahl2** [comment]
It's *possible* that there are other similar issues lurking from 31c7fa8. There are several places where we go from setting only `rc` and `op_status`, to setting those plus freeing and resetting `exit_reason`. Thinking specifically about cases where the `exit_reason` argument of `lrmd__set_result()` is `NULL` -- for example, in `controld_rc2event()`.

If any of those turn out to have memory problems, we can deal with them if and when they arise. valgrind is happy with a notify test after this change.

**Comment by kgaillot** [comment]
Ouch. It's always nice to add a comment describing the bug you're introducing.

Good work, thanks!

**Comment by kgaillot** [comment]
BTW, there is at least one more recently introduced segmentation fault I'm tracking down, but it was introduced after the 2.1.2 release thankfully, so unrelated to the commit mentioned here.

**Comment by nrwahl2** [comment]
@kgaillot What's the other segfault?

**Comment by kgaillot** [comment]
> @kgaillot What's the other segfault?

A nonexistent fence agent is the easiest way to trigger it. What it appears to be at this point is: in internal_stonith_action_execute(), if services_action_async_fork_notify() fails early (no fork is done), then it will call services__finalize_async_op() which will call the done callback, which will free action, and then free svc_action. But internal_stonith_action_execute() tries to use both action and svc_action after that.

**Pull request merged**
