### PR TITLE
Release 1.1.22-rc1

### PR DESCRIPTION
**Pull request by kgaillot**

### CODE REVIEW

**Comment by HideoYamauchi** [comment]
Hi Ken,

Is the change of crm_mon system that is included in 2.0 series not included in 1.1.22?


This is because our users expected the next crm_mon fix to go into 1.1.22.

```
[root@rh76hv-02 ~]# crm_mon -1 -Af
Stack: corosync
Current DC: rh76hv-02 (version 2.0.2-3e18b2a5a0) - partition WITHOUT quorum
Last updated: Wed Sep  4 14:14:52 2019
Last change: Wed Sep  4 13:56:49 2019 by root via cibadmin on rh76hv-01

2 nodes configured
2 resources configured

Online: [ rh76hv-02 ]
OFFLINE: [ rh76hv-01 ]

Active resources:
 Resource Group: grpStonith1
     prmStonith1-2      (stonith:external/ssh): Started rh76hv-02
(snip)
Failed Fencing Actions:
* reboot of rh76hv-01 failed: delegate=rh76hv-02, client=pacemaker-controld.21865, origin=rh76hv-02,
    last-failed='Wed Sep  4 13:59:15 2019' (a later attempt succeeded)
```

Is it possible to backport this display change individually to 1.1.22?


Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

> Is it possible to backport this display change individually to 1.1.22?

I think that is a good idea. I've added it to this PR. Are you able to test it?

I hope you are enjoying a day off :)

**Comment by HideoYamauchi** [comment]
Hi Ken,

Thank you for the correction.
I will test this rc1.

Many thanks,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

> I will test this rc1.

Thanks, that will help. In my own testing just now, a failed fencing event had no delegate, so is_later_succeeded() never matched it with a successful fencing (which did have a delegate).

**Comment by HideoYamauchi** [comment]
Hi Ken,

> Thanks, that will help. In my own testing just now, a failed fencing event had no delegate, so is_later_succeeded() never matched it with a successful fencing (which did have a delegate).

All right!

**Comment by HideoYamauchi** [comment]
Hi Ken,

I tested it.
After fencing was completed, it was displayed correctly.

Step1  : Start cluster.
```
[root@rh77hv-01 ~]# crm_mon -1 -Af
Stack: corosync
Current DC: rh77hv-01 (version 1.1.22-2a7435ff82) - partition with quorum
Last updated: Wed Oct 23 10:14:12 2019
Last change: Wed Oct 23 10:13:45 2019 by root via cibadmin on rh77hv-01

3 nodes configured
3 resources configured

Online: [ rh77hv-01 rh77hv-02 ]
OFFLINE: [ rh77hv-03 ]

Active resources:

 prmPrimitive01 (ocf::pacemaker:Dummy): Started rh77hv-01
 Resource Group: grpStonith1
     prmStonith1-2      (stonith:external/ssh): Started rh77hv-02
 Resource Group: grpStonith2
     prmStonith2-2      (stonith:external/ssh): Started rh77hv-01

Node Attributes:
* Node rh77hv-01:
* Node rh77hv-02:

Migration Summary:
* Node rh77hv-01:
* Node rh77hv-02:
``` 

Step2  : All fencing failed.
```
[root@rh77hv-02 ~]# crm_mon -1 -Af
Stack: corosync
Current DC: rh77hv-01 (version 1.1.22-2a7435ff82) - partition with quorum
Last updated: Wed Oct 23 10:17:03 2019
Last change: Wed Oct 23 10:13:29 2019 by root via cibadmin on rh77hv-01

3 nodes configured
3 resources configured

Node rh77hv-01: UNCLEAN (online)
Online: [ rh77hv-02 ]
OFFLINE: [ rh77hv-03 ]

Active resources:

 prmPrimitive01 (ocf::pacemaker:Dummy): FAILED rh77hv-01
 Resource Group: grpStonith1
     prmStonith1-2      (stonith:external/ssh): Started rh77hv-02
 Resource Group: grpStonith2
     prmStonith2-2      (stonith:external/ssh): Started rh77hv-01

Node Attributes:
* Node rh77hv-01:
* Node rh77hv-02:

Migration Summary:
* Node rh77hv-01:
   prmPrimitive01: migration-threshold=1 fail-count=1000000 last-failure='Wed Oct 23 10:14:57 2019'
* Node rh77hv-02:

Failed Resource Actions:
* prmPrimitive01_stop_0 on rh77hv-01 'not installed' (5): call=19, status=Not installed, exitreason='',
    last-rc-change='Wed Oct 23 10:14:57 2019', queued=0ms, exec=0ms

Failed Fencing Actions:
* reboot of rh77hv-01 failed: delegate=rh77hv-02, client=crmd.846, origin=rh77hv-02,
    last-failed='Wed Oct 23 10:15:45 2019' 
[root@rh77hv-02 ~]# crm_mon -1 -Af -m3
Stack: corosync
Current DC: rh77hv-01 (version 1.1.22-2a7435ff82) - partition with quorum
Last updated: Wed Oct 23 10:17:04 2019
Last change: Wed Oct 23 10:13:29 2019 by root via cibadmin on rh77hv-01

3 nodes configured
3 resources configured

Node rh77hv-01: UNCLEAN (online)
Online: [ rh77hv-02 ]
OFFLINE: [ rh77hv-03 ]

Active resources:

 prmPrimitive01 (ocf::pacemaker:Dummy): FAILED rh77hv-01
 Resource Group: grpStonith1
     prmStonith1-2      (stonith:external/ssh): Started rh77hv-02
 Resource Group: grpStonith2
     prmStonith2-2      (stonith:external/ssh): Started rh77hv-01

Node Attributes:
* Node rh77hv-01:
* Node rh77hv-02:

Migration Summary:
* Node rh77hv-01:
   prmPrimitive01: migration-threshold=1 fail-count=1000000 last-failure='Wed Oct 23 10:14:57 2019'
* Node rh77hv-02:

Failed Resource Actions:
* prmPrimitive01_stop_0 on rh77hv-01 'not installed' (5): call=19, status=Not installed, exitreason='',
    last-rc-change='Wed Oct 23 10:14:57 2019', queued=0ms, exec=0ms

Failed Fencing Actions:
* reboot of rh77hv-01 failed: delegate=rh77hv-02, client=crmd.846, origin=rh77hv-02,
    completed='Wed Oct 23 10:15:45 2019' 
(snip)
* reboot of rh77hv-01 failed: delegate=rh77hv-02, client=crmd.846, origin=rh77hv-02,
    completed='Wed Oct 23 10:14:46 2019' 

Fencing History:
```

Step3 : Successful after fencing fails. ("a later attempt succeeded" is displayed.)
```

[root@rh77hv-02 ~]# crm_mon -1 -Af
Stack: corosync
Current DC: rh77hv-02 (version 1.1.22-2a7435ff82) - partition WITHOUT quorum
Last updated: Wed Oct 23 10:30:55 2019
Last change: Wed Oct 23 10:13:29 2019 by root via cibadmin on rh77hv-01

3 nodes configured
3 resources configured

Online: [ rh77hv-02 ]
OFFLINE: [ rh77hv-01 rh77hv-03 ]

Active resources:

 prmPrimitive01 (ocf::pacemaker:Dummy): Started rh77hv-02
 Resource Group: grpStonith1
     prmStonith1-2      (stonith:external/ssh): Started rh77hv-02

Node Attributes:
* Node rh77hv-02:

Migration Summary:
* Node rh77hv-02:

Failed Fencing Actions:
* reboot of rh77hv-01 failed: delegate=rh77hv-02, client=crmd.846, origin=rh77hv-02,
    last-failed='Wed Oct 23 10:15:45 2019' (a later attempt succeeded)
[root@rh77hv-02 ~]# crm_mon -1 -Af -m3
Stack: corosync
Current DC: rh77hv-02 (version 1.1.22-2a7435ff82) - partition WITHOUT quorum
Last updated: Wed Oct 23 10:30:58 2019
Last change: Wed Oct 23 10:13:29 2019 by root via cibadmin on rh77hv-01

3 nodes configured
3 resources configured

Online: [ rh77hv-02 ]
OFFLINE: [ rh77hv-01 rh77hv-03 ]

Active resources:

 prmPrimitive01 (ocf::pacemaker:Dummy): Started rh77hv-02
 Resource Group: grpStonith1
     prmStonith1-2      (stonith:external/ssh): Started rh77hv-02

Node Attributes:
* Node rh77hv-02:

Migration Summary:
* Node rh77hv-02:

Failed Fencing Actions:
* reboot of rh77hv-01 failed: delegate=rh77hv-02, client=crmd.846, origin=rh77hv-02,
    completed='Wed Oct 23 10:15:45 2019' (a later attempt succeeded)
(snip)
* reboot of rh77hv-01 failed: delegate=rh77hv-02, client=crmd.846, origin=rh77hv-02,
    completed='Wed Oct 23 10:14:46 2019' (a later attempt succeeded)

Fencing History:
* reboot of rh77hv-01 successful: delegate=rh77hv-02, client=crmd.846, origin=rh77hv-02,
    completed='Wed Oct 23 10:30:50 2019'
```

Many thanks,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
> I tested it.
> After fencing was completed, it was displayed correctly.

Great, thanks! I'll release this.

**Pull request merged**
