### PR TITLE
Low: crmd: Move to common function.

### PR DESCRIPTION
**Pull request by HideoYamauchi**
Hi All,

We are going to include the trap function of the attribute.
I move some functions of the notify function to a common function first.

Best Regards,
Hideo Yamauchi.

### CODE REVIEW

**Comment by wenningerk** [comment]
Hi Hideo!

Yes ... that was on my agenda ;-)
I was reluctant doing a cut and paste here (what you did after a quick look at the diff)
because I was considering the possibility of getting rid of all the *_hd_* stuff by just globally introducing
a time-date-structure in pacemaker that already holds the high-resolution-part.
There is a 2nd local high-resolution-implementation somewhere in the code btw. ...
But anyway we could still pursue this final goal with a 2-step approach ...

Regards,
Kaus

**Comment by HideoYamauchi** [comment]
Hi Klaus,

>I was reluctant doing a cut and paste here (what you did after a quick look at the diff)
>because I was considering the possibility of getting rid of all the *_hr_* stuff by just globally introducing
>a time-date-structure in pacemaker that already holds the high-resolution-part.
>There is a 2nd local high-resolution-implementation somewhere in the code btw. 

I examine the removal of *_hr_* of the function.
I confirm it about the second implementation(high-resolution-implementation).

Best Regard,
Hideo Yamauchi.

**Comment by wenningerk** [comment]
Was just stating why I hadn't done what your diff proposes already.
But I'm fine with your suggestion and we can tackle a possible removal
of the \*\_hr\_\* in a 2nd step. But if you want to do it now go ahead ...

**Comment by HideoYamauchi** [comment]
Hi Klaus,

Thank you for comment.
I intend to contribute the patch which removed `*_hr_*` again.

Many thanks,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Klaus,

I reviewed a source code.
I think that it is not necessary to remove `*_hr_*` from the function.

What do you think?

Best Regards,
Hideo Yamauchi.

**Comment by wenningerk** [comment]
Hi Hideo!

Of course it is not necessary and you can move the functions as they are.
It is just a little bit unnecessary and ugly to have 2 sets of library-functions
with \*\_hr\_\* and without.
But as said no problem to tackle that sometimes later (or never at all ;-) ).
So no objections from my side...

Regards,
Klaus

**Comment by HideoYamauchi** [comment]
Hi Klaus,

>But as said no problem to tackle that sometimes later (or never at all ;-) ).
>So no objections from my side...

Okay!
I wait for comment of Ken.

Many thanks,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

I have some ideas for a new time interface as a future project, so let's declare these in a new file include/crm/common/iso8601_internal.h instead of iso8601.h, so it's not a public API that we have to support long-term.

Thanks!

**Comment by HideoYamauchi** [comment]
Hi Ken,

Okay!
I try that I move the definition in new iso8601_internal.h file.

Many thanks,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Should the function include all in iso8601_internal.h without moving a function in iso8601.c?

 - example :  iso8601_internal.h
```
#include <time.h>
#include <sys/time.h>
#include <ctype.h>
#include <crm/common/iso8601.h>

typedef struct crm_time_us crm_time_hr_t;
crm_time_hr_t *crm_time_hr_convert(crm_time_hr_t *target, crm_time_t *dt);
void crm_time_set_hr_dt(crm_time_t *target, crm_time_hr_t *hr_dt);
crm_time_hr_t *crm_time_timeval_hr_convert(crm_time_hr_t *target,
                                           struct timeval *tv);
crm_time_hr_t *crm_time_hr_new(const char *date_time);
void crm_time_hr_free(crm_time_hr_t * hr_dt);
char *crm_time_format_hr(const char *format, crm_time_hr_t * hr_dt);

(snip)
static void
ha_get_tm_time( struct tm *target, crm_time_t *source)
{
    *target = (struct tm) {
        .tm_year = source->years - 1900,
        .tm_yday = source->days - 1,
        .tm_sec = source->seconds % 60,
        .tm_min = ( source->seconds / 60 ) % 60,
        .tm_hour = source->seconds / 60 / 60,
(snip)
char *
crm_time_format_hr(const char *format, crm_time_hr_t * hr_dt)
{    const char *mark_s;
    int max = 128, scanned_pos = 0, printed_pos = 0, fmt_pos = 0,
(snip)

```

Best Regards,
Hideo Yamauchi.

**Comment by wenningerk** [comment]
Hi Hideo!

Guess this is not what Ken meant.
Global symbols should be fine. Just the definitions should stay in an internal header
to not lure others to use the functions so that we have to provide them later on
once we have moved to something nicer.
If sbdy puts a definition inside a c-files he has to expect that to break sooner
or later.

Regards,
Klaus

**Comment by HideoYamauchi** [comment]
Hi Klaus,

Will a function of notify.c be to move only a definition in iso8601_internal.h without moving?

 - example : iso8601_internal.h
```
#include <time.h>
#include <sys/time.h>
#include <ctype.h>
#include <crm/common/iso8601.h>

typedef struct crm_time_us crm_time_hr_t;
crm_time_hr_t *crm_time_hr_convert(crm_time_hr_t *target, crm_time_t *dt);
void crm_time_set_hr_dt(crm_time_t *target, crm_time_hr_t *hr_dt);
crm_time_hr_t *crm_time_timeval_hr_convert(crm_time_hr_t *target,
                                           struct timeval *tv);
crm_time_hr_t *crm_time_hr_new(const char *date_time);
void crm_time_hr_free(crm_time_hr_t * hr_dt);
char *crm_time_format_hr(const char *format, crm_time_hr_t * hr_dt);

crm_time_t *parse_date(const char *date_str); /* in iso8601.c global but
                                                 not in header */

struct crm_time_us {
    int years;
    int months;                 /* Only for durations */
    int days;
    int seconds;
    int offset;                 /* Seconds */
    bool duration;
    int useconds;
};

struct crm_time_s {
    int years;
    int months;                 /* Only for durations */
    int days;
    int seconds;
    int offset;                 /* Seconds */
    bool duration;
};
```
Does the function of notify.c not move until Mr. Ken introduces a new function?

Many thanks,
Hideo Yamauchi.

**Comment by wenningerk** [comment]
Hi Hideo,

depends on where we intend to use them if they would stay in notify.c or go to iso8601.c.
Guess the whole intent is coming because moving the actual execution to lrmd (including
the creation of the attribute-triggered events) would lead to the timestamp-functions being
needed both in crmd and lrmd. Stamping as early as possible leads to them still being
needed in crmd. As this attempt will probably result in more common code between
the crmd and the lrmd part this sounds like the natural place if not iso8601.c.
But maybe Ken can give us some insight in his ideas so that it becomes easier to do
future proof decisions here.

Regards,
Klaus

**Comment by HideoYamauchi** [comment]
Hi Klaus,

Then I change only a definition in iso8601_intenal.h.

I advance to the correction of the attribute trap while expecting it for a future correction of Mr. Ken.
A function similar to notify.c is necessary for an attribute trap, but it sends a correction by different PR again.
This PR is closed once and sends PR again.

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

Sorry for not being clearer.

It is correct to move the function definitions from notify.c to iso8601.c, which will make them available via libcrmcommon to both crmd and attrd.

It is only the parts that were to be moved to iso8601.h (the typedef, struct and function declarations) that should go into a new iso8601_internal.h. Anything in iso8601.h is considered part of the public library API, and we aim to keep those backward-compatible for as long as possible. Anything in a file with "internal" in its name is for pacemaker's use only, and can change in any release. So, using an internal header will make it easier for us to change the interface sometime in the future, though there are no immediate plans to do so.

**Comment by HideoYamauchi** [comment]
Hi Ken,

I am still confused a little.
I am weak in English, and I am sorry.

How about by the next correction?
 -  https://github.com/HideoYamauchi/pacemaker/commit/96fe0ddb9254cdc6a847b9d45f92d9649320c557

Because the function moved to iso8601.c, I become able to use it from attrd(or other ).

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
> How about by the next correction?
> 
>     HideoYamauchi@96fe0dd

Hi Hideo,

Yes, that is what I had in mind. 

Thanks,

**Comment by HideoYamauchi** [comment]
Hi Ken,

I repair some corrections neatly.
And I send it by new PR.

Many thanks,
Hideo Yamauchi.

**Pull request closed without merging**
