### PR TITLE
Doc: restricted namespace for custom meta-attributes

### PR DESCRIPTION
**Pull request by jnpkrn**
Spun off from https://github.com/ClusterLabs/pacemaker/pull/1500#discussion_r197303666

### CODE REVIEW

**Comment by jnpkrn** [comment]
Currently `DTD Validation failed`, but open for discussion.

**Comment by jnpkrn** [comment]
Note that `x-constraints_` prefix serves primarily as a referable synchronization
point for high-level management tool (instead of seeing meaninglessly invented
`x-crmsh_`, `x-pcs_`, ...

**Comment by kgaillot** [comment]
I don't want to impose any new requirements for meta-attribute naming. People can choose a prefix of their own (just like OCF providers) if they want to reduce the chance of conflicts.

**Comment by jnpkrn** [comment]
On 22/06/18 14:06 -0700, Ken Gaillot wrote:
> I don't want to impose any new requirements for meta-attribute
> naming.

Then you are preventing unbreaking the inherent brokenness
(that irks me oh so much).

> People can choose a prefix of their own (just like OCF
> providers) if they want to reduce the chance of conflicts.

Nice, instead of setting up a path towards enforced separation
in CIB 4.0+ or so.

-- 
Jan (Poki)

**Comment by kgaillot** [comment]
> Then you are preventing unbreaking the inherent brokenness (that irks me oh so much).

An inelegant design with inherent flaws is not broken. Causing an existing configuration that works to stop working *is* broken.

There are far more issues to be tackled than time to tackle them, and we have to prioritize. AFAIK, in a decade there have been zero user complaints about colliding meta-attribute names. Meanwhile, there are dozens of serious outstanding bug reports that are affecting users now.

We had a rare opportunity with the 2.0 cycle to make some big design changes, but we are too late in that cycle to introduce new ones, and even at its beginning, we took as much care as possible to preserve compatibility with existing configurations.

> Nice, instead of setting up a path towards enforced separation in CIB 4.0+ or so.

Exactly, we have a trivial workaround that users can use today, that requires zero developer effort.

**Comment by jnpkrn** [comment]
On 25/06/18 11:01 -0700, Ken Gaillot wrote:
>> Then you are preventing unbreaking the inherent brokenness (that irks me oh so much).
> 
> An inelegant design with inherent flaws is not broken. Causing an
> existing configuration that works to stop working *is* broken.

How do you infer I plan to break it _now_?

Not even
https://github.com/ClusterLabs/pacemaker/pull/1500#discussion_r197535719
mentions this, the term "mandates" is intentionally slightly stronger
than what the situation with 3.* schemas is going to look like
(as mentioned at the referenced comment, then it's OK to lift also
the restriction on previously banned names as a restriction from
escaping from the original semantics).

The plan would be to instruct users (this PR) and warn them actively
(simple check yet to be added) in CIB 3.* timeframe, and only after
this deprecation period, migrate meta-attributes not recognized by
pacemaker at given terminal 3.X version as gracefully as possible
into `x-overflow` namespace (realized it should be reserved as well)
adjusting possible `value-source` references along the way.

This whole arrangement with selective acceptance of enumerated items
and those matching say `x-.*` regexp is feasible with RelaxNG.

> There are far more issues to be tackled than time to tackle them,
> and we have to prioritize. AFAIK, in a decade there have been zero
> user complaints about colliding meta-attribute names.

Again, misunderstood :-/

This is about _sane data model_, because only then, _sane
configuration upgrades_ can be performed.  I know what I am talking
about.

And afterall, the practically meaningful use of custom meta-attributes
wasn't introduced until 1.1.17 ... people are not even aware of
@id-ref sugar till today.

> Meanwhile, there are dozens of serious outstanding bug reports that
> are affecting users now.

Sure, will always be ... how many of them are caused by defective
design?  Isn't proper design a best line of defense?
Anticipating future dead ends instead of ad-hoc solutions?

> We had a rare opportunity with the 2.0 cycle to make some big design
> changes, but we are too late in that cycle to introduce new ones,
> and even at its beginning, we took as much care as possible to
> preserve compatibility with existing configurations.

As mentioned, actual active change would happen with CIB 4+

>> Nice, instead of setting up a path towards enforced separation in CIB 4.0+ or so.
> 
> Exactly, we have a trivial workaround that users can use today, that
> requires zero developer effort.

The purpose here is to get users do the right thing now with the
new configurations and warn those with existing ones carrying custom
meta-attributes (also finally it would then be valid to emit warnings
like "clone-maximum not recognized" to capture user's own mistakes),
all with the goal to make configuration management easier in the
future.  For instance, upgrade arrangements desperately need sane
preconditions.  Also, have you ever tried to view the configuration
surface from say pcs perspective?

Immediate profits (everything has a trivial workaround if you are
willing to scale "trivial" out of proportion) need to be balanced
with long term ones + wider context.

That's what I am trying to do here.
Maybe the messages just gets lost?

-- 
Jan (Poki)

**Comment by kgaillot** [comment]
I don't think restricting the user name space is a good solution to this issue (despite that being my first suggestion back when). I think ultimately we need a separate namespace, by moving one or the other use cases to a new element. Conceptually the easiest approach would be a new user_attributes block ignored by pacemaker, but given our other long-term design objectives, I prefer the idea of moving pacemaker's options to structured elements. However it's just not important enough to merit any attention at this time. The likelihood of problems for either users or upgrades is minuscule.

As it turns out, in practice ad-hoc solutions do indeed fare better than anticipating future issues (which is why the latter is often called "a solution in search of a problem"). It's a counterintuitive result but borne out in actual operation. There is a balance between elegant design and responsiveness to change, and the latter wins most of the time. (There are exceptions of course.) We should definitely improve our design when practical, but it has to be balanced against other values such as user-friendliness, backward compatibility, and best use of time.

**Comment by jnpkrn** [comment]
Gosh, the point is still not being taken here :-(

Nobody claims the envisioned arrangement will be the ultimate
static one!  I think that structured elements approach will only
generate new worries without having any added value, but that's
ulterior here.

What's needed is to work towards actively segregating the single namespace
here.  Unlike with `instance_attributes` where it happens implicitly based on
what the particular execution agent declares.
I push this segregation slowly forward, the effort must start somewhere,
that's what I am doing with this PR.  WIth that in place, it's also easy to
perform something with `x-*` meta-attributes en masse, whether it's to move
them to `user_attributes` or something else.  Recommended subnamespacing
will further ensure that (custom made, mostly) syntactically based annotation
tools won't collide.

With the segregated namespace, any further mechanical processing and
sanity checking is a breeze.  Now, it's a tragedy.

The push won't be hard, there's a whole 3.x schemas timeframe to adapt
at one's discretion and deliberation (for an educated adaptation), it will get
hard-upgraded afterwards.  The affected audience will be minimal (compare
to `@id-ref`) but the gentleness of the transition is ensured here fully.

Lots of words burnt on this already.
Can't you just trust me and my intuition?
That would be most productive here.

Otherwise I am all in for retaining for once-dropped meta-attributes
as arranged already and I could have spared then-apparently futile effort
with a design towards better configuration management, as initiatives
like this from someone having enough insights will prove as generally
unwanted.

**Comment by kgaillot** [comment]
> Gosh, the point is still not being taken here :-(
> 
> Nobody claims the envisioned arrangement will be the ultimate
> static one! I think that structured elements approach will only
> generate new worries without having any added value, but that's
> ulterior here.

I don't think it's a helpful solution short-term or long-term to restrict users' naming choices in meta-attributes, when there haven't been restrictions to this point. I don't want to tell users one thing now and then come up with a completely different approach later.
 
> What's needed is to work towards actively segregating the single namespace
> here. Unlike with instance_attributes where it happens implicitly based on

No, it's not needed. It's been this way for a decade with no complaints or issues. It would be nice to have a better design, but it's not necessary by any stretch of the imagination.

> what the particular execution agent declares.
> I push this segregation slowly forward, the effort must start somewhere,
> that's what I am doing with this PR. WIth that in place, it's also easy to
> perform something with x-* meta-attributes en masse, whether it's to move
> them to user_attributes or something else. Recommended subnamespacing
> will further ensure that (custom made, mostly) syntactically based annotation
> tools won't collide.
> 
> With the segregated namespace, any further mechanical processing and
> sanity checking is a breeze. Now, it's a tragedy.
> 
> The push won't be hard, there's a whole 3.x schemas timeframe to adapt
> at one's discretion and deliberation (for an educated adaptation), it will get
> hard-upgraded afterwards. The affected audience will be minimal (compare
> to @id-ref) but the gentleness of the transition is ensured here fully.

There's absolutely no reason to inconvenience users on this point. The marginal benefit to us is insignificant compared to requiring a system administrator to spend time on infrastructure unnecessarily. Users' needs are paramount. Anything we do has to be of more benefit than cost to them. There's absolutely no need to make them change their existing configuration for the sake of some shining vision. It's OK to have designs that are less than ideal.

> Lots of words burnt on this already.
> Can't you just trust me and my intuition?
> That would be most productive here.

Three decades of experience in development and system/network administration roles tell me you have a strong developer's perspective but not so much a user's perspective. Users should not be inconvenienced unless absolutely necessary, and this is not anywhere near necessary.

> Otherwise I am all in for retaining for once-dropped meta-attributes
> as arranged already and I could have spared then-apparently futile effort
> with a design towards better configuration management, as initiatives
> like this from someone having enough insights will prove as generally
> unwanted.

**Comment by jnpkrn** [comment]
On 25/06/18 16:42 -0700, Ken Gaillot wrote:
>> Gosh, the point is still not being taken here :-(
>> 
>> Nobody claims the envisioned arrangement will be the ultimate
>> static one! I think that structured elements approach will only
>> generate new worries without having any added value, but that's
>> ulterior here.
> 
> I don't think it's a helpful solution short-term or long-term to
> restrict users' naming choices in meta-attributes, when there
> haven't been restrictions to this point. I don't want to tell users
> one thing now and then come up with a completely different approach
> later.

Once the bi-compatible separation is done, it may rest without
any different approach being required.  Though if there's another
approach, the precondition state space will be easy to tranform,
unlike with the current state.

>> What's needed is to work towards actively segregating the single namespace
>> here. Unlike with instance_attributes where it happens implicitly based on
> 
> No, it's not needed. It's been this way for a decade with no
> complaints or issues. It would be nice to have a better design, but
> it's not necessary by any stretch of the imagination.

As someone who worked on the configuration upgrades and meet up
pcs folks on daily basis, I claim it would be bad in carrying the
broken status quo on when we can start with harmless, moderately
paced normalizing towards the sanity, opt-in first, than
catch-the-rest automatic change.  Future will be grateful.

>> what the particular execution agent declares.
>> I push this segregation slowly forward, the effort must start somewhere,
>> that's what I am doing with this PR. WIth that in place, it's also easy to
>> perform something with x-* meta-attributes en masse, whether it's to move
>> them to user_attributes or something else. Recommended subnamespacing
>> will further ensure that (custom made, mostly) syntactically based annotation
>> tools won't collide.
>> 
>> With the segregated namespace, any further mechanical processing and
>> sanity checking is a breeze. Now, it's a tragedy.
>> 
>> The push won't be hard, there's a whole 3.x schemas timeframe to adapt
>> at one's discretion and deliberation (for an educated adaptation), it will get
>> hard-upgraded afterwards. The affected audience will be minimal (compare
>> to @id-ref) but the gentleness of the transition is ensured here fully.
> 
> There's absolutely no reason to inconvenience users on this point.
> The marginal benefit to us is insignificant compared to requiring a
> system administrator to spend time on infrastructure unnecessarily.

Still not bought?  One is totally free to ignore the warning messages
for the whole 3.* line of CIB schemas, only in place because of possibly
3rd party configuration annotation tool may likewise need to be modified
to follow x-*/x-appname_* scheme along the keys in CIB themselves.

> Users' needs are paramount. Anything we do has to be of more benefit
> than cost to them. There's absolutely no need to make them change
> their existing configuration for the sake of some shining vision.

Well, you are buiding your argument on the "costs" term while you
haven't considered costs for the wider ecosystem should the
configuration surface change radically -- my short-term proposal
is minimalistic and fully compatible, and is a shift towards
clear separation of the two domains put into single namespace.
That alone fits the bill and makes the situation clear.
So not clear what you "costs" refer to.

> It's OK to have designs that are less than ideal.

That's why the proposed design doesn't attempt to do anything
else, but to draw the line least intrusive way.

>> Lots of words burnt on this already.
>> Can't you just trust me and my intuition?
>> That would be most productive here.
> 
> Three decades of experience in development and system/network
> administration roles tell me you have a strong developer's
> perspective but not so much a user's perspective.

Oh well, times where huge changes posed no issue, as there was
just a handful of meaningful services, administrators were not
a lazy squad.  Actually now the user friendliness expectations
are set much much higher and I think you deeply underestimate
that all this effort puts user first:

- to repeat it again: no immediate nor even possibly delayed costs
  of radically changed configuration schema, plus it actively prevents
  users to shoot in their feet in case pacemaker claims a new
  meta-attribute -- do you think it's friendlier when this happens???

- nice warnings when there's a typo in the meta attribute
  (currently cannot be present ... by mis-design), on the other
  hand, ability to take configuration from newer cluster stack
  and it should work also with older pacemaker cluster, only
  some meta-attributes may not be understood, which will get
  complained about

More elaborate advantages available with little internal modifications:

- extensibility of the validation schemes:
  application-specific meta-attributes can drop in the subgrammar
  of x-appname_* definitions, schema can be easily regenerated
  and they will get validation for free

- high level management tools can only benefit with restrictions
  on the namespace (see typo checking), possibly extensible with
  proper data typing; also the implementation of the prefix-based
  convenition is trivial enough

I really don't get it how you infer this change should have anything
to do with user unfriendliness (like it happens with status quo, sadly).

> Users should not be inconvenienced unless absolutely necessary, and
> this is not anywhere near necessary.
> 
>> Otherwise I am all in for retaining for once-dropped meta-attributes
>> as arranged already and I could have spared then-apparently futile effort
>> with a design towards better configuration management, as initiatives
>> like this from someone having enough insights will prove as generally
>> unwanted.

This is clearly a matter for wider discussion as the misunderstanding
of the genuinely well meant objectives is causing too much spasm
and friction between two heads.  Anyway, if the verdict is positive,
it makes 100% sense to deliver the ground work -- documentation update
per this PR and warning emitting of unrecognized meta attributes
(i.e., not pacemaker proper + x-prefixed ones) -- yet in 2.0, to allow
for smooth transition even from 2.0 to 3.0+.

-- 
Jan (Poki)

**Comment by jnpkrn** [comment]
Another example of "local extensions", fitting the very scheme:
http://refspecs.linuxbase.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/initscrcomconv.html#AEN25772

**Pull request closed without merging**
