### PR TITLE
Build enhancements

### PR DESCRIPTION
**Pull request by wferi**
One might want to `--disable-cts` if (s)he doesn't want to install it or simply hasn't got Python around.

### CODE REVIEW

**Comment by kgaillot** [comment]
This seems reasonable, but I want to think about it for a while. There is more python in pacemaker besides cts (fencing and lrmd regression tests, and the dummy fence agent), and more importantly, we're likely to convert more tools to python in the future, as some of them are getting a bit complicated for a shell script. I could easily see things like the ocf:pacemaker:ping resource and the crm_report tool becoming python.

**Comment by wferi** [comment]
My aim was more to avoid building and installing stuff (most prominently the CTS) I don't package. But the `/usr/share/pacemaker/tests` directory fall in this category as well. If you'd prefer something like `--disable-tests` which excludes the `cts` subdir and also the test-related parts of the `fencing`, `lrmd`, `tools` and `pengine` subdirs, I'd go for that.
At the same time, I'd be happy to run internal unit tests (think `make check`) during the build, provided they don't install anything (and don't rebuild the whole tree with clang). The `pengine` subdir actually had something like that, but it feels mostly disabled. Could you please comment on its status? Thanks.

**Comment by kgaillot** [comment]
Disabling all testing code would make more sense, and would skip all current python. However, in the long term, there will likely be more python, and it may be important, and if not essential. We do list python as a build dependency, so I'm not sure this is desirable upstream.

Some of the regression tests can definitely be run from a build directory without causing trouble. I only ever run the pengine tests that way:

    ./pengine/regression.sh
    [ -s pengine/.regression.failed.diff ] && echo "Failed"

I'm not sure which of the other tests are suitable for that. I know some of them expect various cluster software to be installed in their usual locations.

**Comment by wferi** [comment]
Thanks for your comments. I replaced the proposed change with another making all testing code and data optional (even `lrmd_test`, though I'm not completely sure about that). This does not touch Python detection at all, neither adds the version constraint. Do you find this more acceptable?

**Comment by kgaillot** [comment]
Will this option still be useful to you when python is used more extensively by tools and agents?

**Comment by wferi** [comment]
Yes, provided it excludes stuff which is not useful for the regular user. Currently I'm removing these during packaging, but that's somewhat fragile, for example because the directory names change according to the used Python version. Wildcarding, on the other hand, can be dangerous. It's best to not install the unneeded components in the first place; that also streamlines packaging and makes it self-explanatory.

**Comment by kgaillot** [comment]
I don't think this is desirable upstream. The goal of not packaging certain parts of pacemaker is properly handled on the packaging side rather than in configure, and the goal of avoiding python isn't compatible with python being a stated build dependency of pacemaker.

However, I think your patch is sound for your purposes. If you want resubmit moving some statements around so your private patch is smaller, I'm fine with that.

**Comment by wferi** [comment]
I split up the patch. If I understand you right, you're fine with the first one. The second looks stupid in isolation, and you object to the third one. I agree it isn't directly useful upstream, but more like 5f23492 in spirit: it helps packagers. I'm a little worried about context changes breaking it more often than necessary, that's why I'm trying to persuade you.
Please forget the Python relation; as you pointed out, it's a passing coincidence, which I shouldn't have mentioned at all. I'm actually happy to see Python replacing convoluted shell scripting, especially in critical applications like resource and fencing agents. We just need some helper libraries for OCF (and/or centralized retry logic; but I digress).
More to the point, maybe I'm misguided trying to not package the tests. Do you think there'd be considerable value in that? I know of the `pacemaker-cts` RPM, but I still wonder. On the other hand, I'll definitely run `pengine/regression.sh` during package build. Aren't you interested in turning it into standard Automake tests?

**Comment by kgaillot** [comment]
> I split up the patch. If I understand you right, you're fine with the first one. The second looks stupid in isolation, and you object to the third one. I agree it isn't directly useful upstream, but more like 5f23492 in spirit: it helps packagers. I'm a little worried about context changes breaking it more often than necessary, that's why I'm trying to persuade you.

Right, I'm fine with the first two; if you pull the third, I'll merge this. I think the first two help minimize the risk of future context changes.

5f23492 is important for building (not just packaging) on distros that don't use /etc/sysconfig (ie it's needed to build the init scripts etc.). I think we want to avoid blurring the line between building vs packaging too much.

> More to the point, maybe I'm misguided trying to not package the tests. Do you think there'd be considerable value in that? I know of the pacemaker-cts RPM, but I still wonder. On the other hand, I'll definitely run pengine/regression.sh during package build. Aren't you interested in turning it into standard Automake tests?

You're right, most users won't care about the tests, though we do hear occasionally of someone who does. I don't think it's necessary to package it for a distro; it's just a bonus for advanced users (especially those who might be interested in modifying the code and ensuring they didn't break anything, or those who might be interested in building in an unusual environment).

It would probably be a good idea to run some regression tests as "make check". I wasn't actually familar with what we had currently, and interestingly we do run a single pengine regression test via make check, then build the documentation for some reason, then attempt to run clang's static analyzer. So it looks like a mess :-) One more cleanup for the to-do list ...

**Comment by wferi** [comment]
OK, I rebased onto current master and added comments to the strange splits.
Let's see how this works out.

**Pull request merged**
