### PR TITLE
Improve executor fence device handling

### PR DESCRIPTION
**Pull request by kgaillot**
These address some small issues found while investigating CLBZ#5352 (which is not directly addressed here).

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi @HideoYamauchi , can you review these changes? It will be easier to look at the commits individually. This will support a fix for CLBZ#5352 (which I don't have ready yet).

**Comment by HideoYamauchi** [comment]
Hi Ken,

All right!

I will review this week.
Please give me some time.

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

Thank you very much for doing this. There's no rush.

FYI, I just pushed one small change, I dropped the "make stonith_started field a boolean" commit because I think I'm going to use that field in a new way for the CLBZ#5352 fix.

**Comment by HideoYamauchi** [comment]
Hi Ken,

I reviewed it, but I did not point out.
Also, I checked the operation again for the bug I reported (CLBZ # 5352), but the problem has been improved as in the previous correction.

I think that there is no problem with this fix.

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo, thanks for reviewing and testing!

**Pull request merged**
