### PR TITLE
Low: libcommon: Erase old exit_reason.

### PR DESCRIPTION
**Pull request by HideoYamauchi**

### CODE REVIEW

**Comment by kgaillot** [comment]
I don't think we should use an explicit "none" -- I plan to eventually make crm_mon hide exit_reason if it's NULL, and we wouldn't want to show "none" to the user in that case instead.

I think simply using crm_xml_replace() instead of crm_xml_add() will work. If the value is NULL, crm_xml_replace() will remove the attribute from the XML.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Okay!
I try it!

Many Thanks!
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Using create_operation_update, crm_xml_replace will not work.

'''
(snip)
xmlNode *create_operation_update(xmlNode * parent, lrmd_event_data_t * op, const char * caller_version,
                        int target_rc, const char * node, const char * origin, int level)
(snip)
  again:
    xml_op = find_entity(parent, XML_LRM_TAG_RSC_OP, op_id);
    if (xml_op == NULL) {
        xml_op = create_xml_node(parent, XML_LRM_TAG_RSC_OP);
    }
(snip)
    crm_xml_add(xml_op, XML_ATTR_ID, op_id);    crm_xml_add(xml_op, XML_LRM_ATTR_TASK_KEY, key);    crm_xml_add(xml_op, XML_LRM_ATTR_TASK, task);    crm_xml_add(xml_op, XML_ATTR_ORIGIN, origin);
    crm_xml_add(xml_op, XML_ATTR_CRM_VERSION, caller_version);
    crm_xml_add(xml_op, XML_ATTR_TRANSITION_KEY, op->user_data);
    crm_xml_add(xml_op, XML_ATTR_TRANSITION_MAGIC, magic);
    crm_xml_replace(xml_op, XML_LRM_ATTR_EXIT_REASON, exit_reason);

'''

This is because xml in this case is all created for updating, so when adding exit_reason, exit_reason has not been set to xml for updating yet.

'''
<lrm_rsc_op id="prmDummy_last_failure_0" operation_key="prmDummy_stop_0" operation="stop" crm-debug-origin="do_update_resource" crm_feature_set="3.0.14" transition-key="1:3:0:fd87fe3d-160e-4b2d-8394-90d667f9b2a1" transition-magic="2:1;1:3:0:fd87fe3d-160e-4b2d-8394-90d667f9b2a1"/>
'''

Therefore, crm_xml_replace will fail with output of the following log.

'''
Oct  4 19:12:46 rh73-01 crmd[9319]:   error: crm_xml_replace: Triggered assert at xml.c:2550 : old_value != value
''''

Is there any good API?

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
I forgot that crm_xml_replace() checks that the value can't be the same. I'm not sure why it does that, but I think it is needed somewhere it is already used.

It's a little awkward, but maybe we could grab the existing crm_element_value(), and only call crm_xml_replace() if the result is not the same as the new value.

Alternatively, maybe we could try crm_xml_add() with an empty string ("") instead of "none".

**Comment by HideoYamauchi** [comment]
Hi Ken,

Okay!

I tried it a lot, but there was no way to do it well.
I will take a method to set "" instead of "none".

Many thanks,
Hideo Yamauchi.

**Pull request closed without merging**
