### PR TITLE
translate fenced files for zh_cn

### PR DESCRIPTION
**Pull request by luckhuanhuan**
translate fenced files for zh_cn

### CODE REVIEW

**Comment by wenningerk** [comment]
test this please

**Comment by kgaillot** [comment]
Hi,

Thank you for the additional translations. With previous translations, we figured out that including XML in the translated text causes problems. We solved that with the add_desc() function in lib/common/options.c. To avoid duplicating that effort, the best solution here will be to convert pacemakerd-fenced to use `pcmk__format_option_metadata()`.

Thankfully, that is an easy process. The biggest step is to define an array of `pcmk__cluster_option_t` (which could be named fencer_options[]). Then all we need to do is call `pcmk__format_option_metadata()` with that array, in pacemaker-fenced.c's main() where it handles "metadata", instead of all the printf()'s.  See crmd_opts[] and crmd_metadata() in daemons/controld/controld_control.c for an example with translations.

If you do not have time for that, I can take it and get back with you when it is ready.

**Comment by luckhuanhuan** [comment]
> Hi,
> 
> Thank you for the additional translations. With previous translations, we figured out that including XML in the translated text causes problems. We solved that with the add_desc() function in lib/common/options.c. To avoid duplicating that effort, the best solution here will be to convert pacemakerd-fenced to use `pcmk__format_option_metadata()`.
> 
> Thankfully, that is an easy process. The biggest step is to define an array of `pcmk__cluster_option_t` (which could be named fencer_options[]). Then all we need to do is call `pcmk__format_option_metadata()` with that array, in pacemaker-fenced.c's main() where it handles "metadata", instead of all the printf()'s. See crmd_opts[] and crmd_metadata() in daemons/controld/controld_control.c for an example with translations.
> 
> If you do not have time for that, I can take it and get back with you when it is ready.

OKay , I'll try it.

**Comment by wenningerk** [comment]
Maybe try to get rid of that merge commit.

**Comment by wenningerk** [comment]
If you closed because of the merge commit you wouldn't necessarily have to.
If I screw things up on a branch I usually delete it on my local clone, recreate it
and fast-forward-push it to my github-repo.
If that was for other reasons please forget my comment ;-)

**Pull request closed without merging**
