### PR TITLE
README: add missing build dependencies

### PR DESCRIPTION
**Pull request by Hi-Angel**

### CODE REVIEW

**Comment by Hi-Angel** [comment]
Yes

**Comment by Hi-Angel** [comment]
Yeah, I was building on Ubuntu-18.04.

Actually, I think I could simply add a subsection: `On Ubuntu you may additionally need these packages`, and list these. What do you think?

**Comment by Hi-Angel** [comment]
I mean, I kinda like that at least for some distros these dependencies name actual packages.

**Comment by Hi-Angel** [comment]
It's not like one can't infer from the Fedora/Suse package names the actual software used. In fact, I just did that for Ubuntu. And the names are pretty similar too.

**Comment by Hi-Angel** [comment]
I think, having packages for one distro in a single line or lines next to each other *(as it is now)* makes it easier to just copy-paste the whole thing into a terminal, maybe with a few modifications. Having a table though requires copying them one-by-one.

But I'm not really opposed, it's just a thought. I can arrange it to a table if you want. Note though: I assume that Fedora/Suse dependencies are the ones already present in INSTALL.md, otherwise I wouldn't know what they are.

**Comment by Hi-Angel** [comment]
@kgaillot I made a table in a separate branch, you can look at it [here](https://github.com/Hi-Angel/pacemaker/blob/build-deps-to-table/INSTALL.md). See if you're okay with it.

> All of those libraries are included in corosynclib-devel on Fedora/Red Hat based distros

Btw, the dependencies also list bash. Is bash not installed by default on Fedora or Suse?

**Comment by Hi-Angel** [comment]
I think I could also move `Version` to a separate column. The first one probably, so people wouldn't miss it.

**Comment by Hi-Angel** [comment]
> A separate column makes sense, but I think it would look more natural as the last one.

I agree it looks more natural as the last one. But imagine the table has 7 columns, so the version is the 7th one. I think most readers would stop reading after 3rd or 4th column, and will never know there's a version requirement until something goes wrong.

On the other hand, making it the first column ensures readers wouldn't miss it.

-----

I pushed the commit, the changes I made, compared to the table in example, per previous comment:

* fixed names of dependencies for Suse
* removed bash dependency
* added `Version` column *(it's the 1st column per my note above)*.

**Comment by kgaillot** [comment]
I think version as the first column works well. I'd rather leave version blank than "any" since there may be a minimum version, we're just not aware of what it is.

The python dependency is on version 2.7 or later. However the package name could vary not only by distro but by distro version (mainly python vs python3). Hopefully just putting "python" will be clear enough for people to know what to use. (I don't think we need to mention python-devel since it's not strictly a requirement.)

Debian's libcfg-dev etc. shouldn't go in the Build Dependencies table. They're specific to corosync, so they need to be under Cluster Stack Dependencies. Currently, only corosync is supported as a cluster layer, but in the past and theoretically in the future we could support alternatives, so the Cluster Stack Dependencies table needs to be designed with that in mind (i.e. it should be clear that the four Debian libraries are collectively the corosync choice). The corosync dependency is on version 2.0.0 or later.

Did you push the SUSE names? I still see the same ones as Fedora.

Thanks for all your work on this!

**Comment by Hi-Angel** [comment]
> I think version as the first column works well. I'd rather leave version blank than "any" since there may be a minimum version, we're just not aware of what it is.

Good point, done.

> The python dependency is on version 2.7 or later

Hmm… python2, are you sure…? I'm pretty sure at work we were installing the 3rd version. Besides, there's [an active work to remove python2 from Fedora as well](https://www.phoronix.com/scan.php?page=news_item&px=Fedora-32-Python2-Removal).

> Debian's libcfg-dev etc. shouldn't go in the Build Dependencies table. They're specific to corosync, so they need to be under Cluster Stack Dependencies. Currently, only corosync is supported as a cluster layer, but in the past and theoretically in the future we could support alternatives, so the Cluster Stack Dependencies table needs to be designed with that in mind (i.e. it should be clear that the four Debian libraries are collectively the corosync choice).

Note, this is the `-dev` package. AFAIR this package was actually required for pacemaker `./configure` to succeed, so one can't build pacemaker without that dependency.

> Did you push the SUSE names? I still see the same ones as Fedora.

Oh, I forgot to say: in your comment the `libtool-ltdl-devel` dependency is empty. Does it mean it's not needed for Suse, or is it a typo? As for the rest: the only other dependency from that list that I found in build dependencies is `bzip2-devel` → `libbz2-devel`, I changed that one.

**Comment by kgaillot** [comment]
> Hmm… python2, are you sure…? I'm pretty sure at work we were installing the 3rd version. Besides, there's [an active work to remove python2 from Fedora as well](https://www.phoronix.com/scan.php?page=news_item&px=Fedora-32-Python2-Removal).

Yes, Pacemaker supports build platforms going about 10 years back. To be clearer, the requirement is 2.7, or 3.2 or later.


> Note, this is the `-dev` package. AFAIR this package was actually required for pacemaker `./configure` to succeed, so one can't build pacemaker without that dependency.

Right, the "Cluster Stack Dependencies" and "Optional Build Dependencies" sections should really be subsections of "Build Dependencies".

The idea is that every build needs what's currently under "Build Dependencies", plus at least one of the cluster stack dependencies. It just so happens that at the moment, there is only one supported cluster stack.

> Oh, I forgot to say: in your comment the `libtool-ltdl-devel` dependency is empty. Does it mean it's not needed for Suse, or is it a typo?

SUSE doesn't have a separate package for that. It's included in their libtool package. So, perhaps it would make sense to put it on one line with "libtool, libtool-ltdl-devel" for Fedora. We could do the same for Debian's corosynclib-devel equivalents.

**Comment by Hi-Angel** [comment]
I added python version.

> Right, the "Cluster Stack Dependencies" and "Optional Build Dependencies" sections should really be subsections of "Build Dependencies".
>
> The idea is that every build needs what's currently under "Build Dependencies", plus at least one of the cluster stack dependencies. It just so happens that at the moment, there is only one supported cluster stack.

As I understand, you want me to also make a table of these two subsections. Can't say I like the idea because I did not test these dependencies on Ubuntu, so I don't know if all of it correct. But anyway, I'm adding a commit where I transform these 2 sections into subsections of "Build Dependencies", and reformat their content into tables. The names of dependencies I googled up.

Also, since each package in "Optional Dependencies" has explanation what it's needed for, I had to add a column "Package purpose". I'm not sure where to put it, so I placed it after Version for consistency. See if you want to move it elsewhere, it's easy to do for me with vim-mode in Emacs.

> SUSE doesn't have a separate package for that. It's included in their libtool package. So, perhaps it would make sense to put it on one line with "libtool, libtool-ltdl-devel" for Fedora. We could do the same for Debian's corosynclib-devel equivalents.

I see, thanks. I'd prefer to leave these 2 packages on separate rows though, because, well, they're separate packages, and the devel package, for example, is called differently on Debian. And it also takes less space this way.

**Comment by kgaillot** [comment]
OK, I think it's really close now. My last concerns:

The python package name varies by distro version. E.g. Debian squeeze and earlier don't have a supported python3 package, and the latest Fedora and RHEL releases don't have a python package. Rather than try to enumerate all the possibilities, I'd be fine with just saying "Python 2.7 or Python 3.2 or later" (maybe even outside the table). I think Python is common enough that people will know what package to get.

Debian doesn't need corosync-dev. That's an implicit dependency (and currently just a transitional package for the actual libcorosync-common-dev) of the main 4 (libcpg-dev etc.), which are the real equivalent of corosynclib-devel/libcorosync-devel.

Now that we're listing the corosync packages separately, the "pick at least one" could be confusing. I think we can just drop it; we can re-add something like it later if we support a new stack.

I'd say "Only corosync 2 or later is currently supported" or put 2.0.0 or later in the version column.

Instead of "Package Purpose", I think "Feature Enabled" might make it more clear. I think making that the first column might be easier to read, but I'm fine either way.

**Comment by Hi-Angel** [comment]
> The python package name varies by distro version. E.g. Debian squeeze and earlier don't have a supported python3 package, and the latest Fedora and RHEL releases don't have a python package. Rather than try to enumerate all the possibilities, I'd be fine with just saying "Python 2.7 or Python 3.2 or later" (maybe even outside the table). I think Python is common enough that people will know what package to get.

Okay, indeed such info seems hard to stuff into a table row, so I put it next to the table. A comment explaining that now in commit description too.

> Debian doesn't need corosync-dev. That's an implicit dependency (and currently just a transitional package for the actual libcorosync-common-dev) of the main 4 (libcpg-dev etc.), which are the real equivalent of corosynclib-devel/libcorosync-devel.

Ah, indeed, so it should get implicitly installed with libcpg-dev. Okay, I blanked out that cell for Debian.

> Now that we're listing the corosync packages separately, the "pick at least one" could be confusing. I think we can just drop it; we can re-add something like it later if we support a new stack.

Done.

> I'd say "Only corosync 2 or later is currently supported" or put 2.0.0 or later in the version column.

Done.

> Instead of "Package Purpose", I think "Feature Enabled" might make it more clear.

Done.

> I think making that the first column might be easier to read, but I'm fine either way.

Done.

**Comment by kgaillot** [comment]
Looks beautiful.

The only thing left is to move the 4 new Debian dependencies to "Cluster Stack Dependencies". The cluster stack dependencies are build dependencies -- they are required to do a build. They're just separated out under their own heading. We can reword the heading if it's not clear enough.

**Comment by Hi-Angel** [comment]
Done.

**Comment by Hi-Angel** [comment]
> We can reword the heading if it's not clear enough.

I do think it could be clearer, but off the top of my head I don't see any better naming.

**Comment by kgaillot** [comment]
Thanks, I know this grew into more work than planned!

**Pull request merged**
