### PR TITLE
Doc: added documentation for alerts-feature (removed ClusterMon)

### PR DESCRIPTION
**Pull request by wenningerk**
Mid: added sample script for alerts vis SMTP
Low: extra: a little more quoting of variables in SNMP alert scripts

alert-scripts might still need some testing...not sure if I will manage today...but they are kind of needed to back the documentation...so I put them into the commit

doc-file lost somehow on the way should now be reconstructed from my last build prior to test-reading in the browser - hope I've found all typos and formatting-deficiencies again...

### CODE REVIEW

**Comment by kgaillot** [comment]
Looks good. Please separate into three commits -- it helps when making the change log and when doing git blame/history/show etc.

**Comment by wenningerk** [comment]
...tempting to have just one commit as there is no native support in git to amend older commits (have a script that does it but I'm not so sure if I should really trust it...)...

anyway done...

**Comment by HideoYamauchi** [comment]
Hi Ken,

Two have a problem with latest pcmk_snmp_helper.sh somehow or other.

Problem 1) An error occurs.
```
Jun  5 15:40:41 ct72-01 crmd[28504]:  notice: notify_9:28635:stderr [ /opt/pcmk_snmp_helper.sh: line 90: syntax error near unexpected token `fi' ]
Jun  5 15:40:41 ct72-01 crmd[28504]:  notice: notify_9:28635:stderr [ /opt/pcmk_snmp_helper.sh: line 90: `fi' ]
```
Problem 2) The next error is given even if I revise the first error.

```
Jun  5 15:46:26 ct72-01 crmd[31173]:  notice: notify_9:31270:stderr [ HOST-RESOURCES-MIB::hrSystemDate: Value out of range (Bad string length :: {(8), (11)}) ]
Jun  5 15:46:26 ct72-01 crmd[31173]: warning: Notification 1 (/opt/pcmk_snmp_helper.sh) failed: 1
Jun  5 15:46:26 ct72-01 crmd[31173]:  notice: notify_9:31284:stderr [ HOST-RESOURCES-MIB::hrSystemDate: Value out of range (Bad string length :: {(8), (11)}) ]
Jun  5 15:46:26 ct72-01 crmd[31173]: warning: Notification 2 (/opt/pcmk_snmp_helper.sh) failed: 1
Jun  5 15:46:26 ct72-01 crmd[31173]:  notice: notify_9:31290:stderr [ HOST-RESOURCES-MIB::hrSystemDate: Value out of range (Bad string length :: {(8), (11)}) ]
Jun  5 15:46:26 ct72-01 crmd[31173]: warning: Notification 3 (/opt/pcmk_snmp_helper.sh) failed: 1

```

Best Regards,
Hideo Yamauchi.

**Comment by wenningerk** [comment]
Oops 'if' is missing the then. Didn't manage to test that before the weekend but wanted to get in the documentation referencing the script...
For the 2nd: did you specify the timestamp-format="%Y-%m-%d,%H:%M:%S.%01N"?
                     that should match the asn.1

**Comment by wenningerk** [comment]
just checked about the time-format:

`[kwenning@kwenning ~]$ snmptrap -v 2c -c public "127.0.0.1" "" PACEMAKER-MIB::pacemakerNotificationTrap HOST-RESOURCES-MIB::hrSystemDate s "16-06-05,10:00:37.9"

[kwenning@kwenning ~]$ snmptrap -v 2c -c public "127.0.0.1" "" PACEMAKER-MIB::pacemakerNotificationTrap HOST-RESOURCES-MIB::hrSystemDate s "10:00:37.000009"HOST-RESOURCES-MIB::hrSystemDate: Value out of range (Bad string length :: {(8), (11)})`

The 2nd is what you would get with the default timestamp-format-string: "%H:%M:%S.%06N"

**Comment by HideoYamauchi** [comment]
Hi Klaus,

I confirmed a trap in the script which you revised.

By the following setting, a trap of PCMK was able to transmit.
```
<instance_attributes id="insta_9">
  <nvpair id="trap_add_hires_timestamp_oid" name="trap_add_hires_timestamp_oid" value="false"/>
</instance_attributes>

```

By the following setting, a trap added hrSystemDate to was able to transmit.

```
<meta_attributes id="config_for_timestamp">
 <nvpair id="ts_fmt" name="timestamp-format" value="%Y-%m-%d,%H:%M:%S.%01N"/>
</meta_attributes>

```

Many thanks!
Hideo Yamauchi.

**Comment by wenningerk** [comment]
Thanks for testing Hideo!

**Pull request merged**
