### PR TITLE
Mid: crmd: Keep a state of LRMD in the DC node latest.

### PR DESCRIPTION
**Pull request by HideoYamauchi**
This patch prevents that a state of LRMD of the DC node disappears by the participation of the node during an action.

It is the correspondence patch of the next bug.
 * http://bugs.clusterlabs.org/show_bug.cgi?id=5286

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi Hideo,

Thanks for figuring this out!

Would you mind combining the two commits into one? I think it would be easier for someone in the future looking at the git history.

Even though do_lrm_query() should never fail in this case, to be safe, we need to fall through to the join_ack->xml case if it does. Otherwise, with no CIB update, there will be no call_id, the callback won't be called, and the join won't be finalized.

**Comment by HideoYamauchi** [comment]
Hi Ken,

>Would you mind combining the two commits into one? I think it would be easier for someone in the >future looking at the git history.

Sorry...By my operation error, the patch has been divided into two.
If this discussion is over, I bundle up one patch.

>Even though do_lrm_query() should never fail in this case, to be safe, we need to fall through to the >join_ack->xml case if it does. Otherwise, with no CIB update, there will be no call_id, the callback >won't be called, and the join won't be finalized.

How about by the next correction?

```
(snip)
        if (now_dc_lrmd_state != NULL) {
            crm_debug("LRM state is updated from do_lrm_query.(%s)", join_from);
            fsa_cib_update(XML_CIB_TAG_STATUS, now_dc_lrmd_state,
                cib_scope_local | cib_quorum_override | cib_can_create, call_id, NULL);
            free(now_dc_lrmd_state);
        } else {
            crm_warn("Could not get our LRM state. LRM state is updated from join_ack->xml.(%s)", join_from);
            fsa_cib_update(XML_CIB_TAG_STATUS, join_ack->xml,
                cib_scope_local | cib_quorum_override | cib_can_create, call_id, NULL);
        }

(snip)
```

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

That would work, thanks.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Okay!
I will send a new patch tomorrow again.

Many thanks!
Hideo Yamauchi.

**Pull request closed without merging**
