### PR TITLE
Mid: crm_mon: Displays completed fault actions as processed.

### PR DESCRIPTION
**Pull request by HideoYamauchi**
Hi All,
Hi Ken,
Hi wenningerk,

This is a modification of crm_mon discussed in the next PR.

The contents of the failure displayed in "Failed Fencing Actions" are displayed with "... but later succeeded" after STONITH is completed.

This should reduce user confusion.

(After failure)
```
[root@rh76hv-02 ~]# crm_mon -1 -Af
Stack: corosync
Current DC: rh76hv-02 (version 2.0.2-7551bea7fa) - partition WITHOUT quorum
Last updated: Tue Aug 27 08:46:16 2019
Last change: Tue Aug 27 08:41:37 2019 by root via cibadmin on rh76hv-01

2 nodes configured
2 resources configured

Node rh76hv-01: UNCLEAN (offline)
Online: [ rh76hv-02 ]

Active resources:

 Resource Group: grpStonith1
     prmStonith1-2      (stonith:external/ssh): Started rh76hv-02
 Resource Group: grpStonith2
     prmStonith2-2      (stonith:external/ssh): Started rh76hv-01 (UNCLEAN)

Node Attributes:
* Node rh76hv-02:

Migration Summary:
* Node rh76hv-02:

Failed Fencing Actions:
* reboot of rh76hv-01 failed: delegate=rh76hv-02, client=pacemaker-controld.5743, origin=rh76hv-02,
    last-failed='Tue Aug 27 08:45:48 2019'
```

(After completion)
```
[root@rh76hv-02 ~]# crm_mon -1 -Af
Stack: corosync
Current DC: rh76hv-02 (version 2.0.2-7551bea7fa) - partition WITHOUT quorum
Last updated: Tue Aug 27 09:03:30 2019
Last change: Tue Aug 27 08:41:37 2019 by root via cibadmin on rh76hv-01

2 nodes configured
2 resources configured

Online: [ rh76hv-02 ]
OFFLINE: [ rh76hv-01 ]

Active resources:

 Resource Group: grpStonith1
     prmStonith1-2      (stonith:external/ssh): Started rh76hv-02

Node Attributes:
* Node rh76hv-02:

Migration Summary:
* Node rh76hv-02:

Failed Fencing Actions:
* reboot of rh76hv-01 failed but later succeeded: delegate=rh76hv-02, client=pacemaker-controld.5743, origin=rh76hv-02,
    last-failed='Tue Aug 27 08:45:48 2019'
```

Best Regards,
Hideo Yamauchi.

### CODE REVIEW

**Comment by wenningerk** [comment]
My concern is still loosing the table-like appearance (not exactly but in the usual case of node-names being equally long in a cluster close enough for the human eye) and a way to at least switch back.
Btw. did we ever think of something like that:

```
Failed Fencing Actions ('-' marks those superseded by later success):
* reboot ...
- reboot of rh76hv-01 failed: delegate=rh76hv-02, client=pacemaker-controld.5743, origin=rh76hv-02,
    last-failed='Tue Aug 27 08:45:48 2019'
```

For not having to go through a potentially long list giving a list reduced to the most recent successes (per target-node) instead of the full history would speed things up significantly. Creating that shouldn't be a big issue as most of the code should be there already.

**Comment by HideoYamauchi** [comment]
Hi Ken,
Hi wenningerk,

I think there is no doubt that it will prevent user confusion, whether it is the first PR display or the other two proposals.

If I make the other two proposals, I will consider with the members again.

Which display plan would you like to use?

(Plan1 from wenningerk)
```
Failed Fencing Actions ('-' marks those superseded by later success):
* reboot ...
- reboot of rh76hv-01 failed: delegate=rh76hv-02, client=pacemaker-controld.5743, origin=rh76hv-02,
    last-failed='Tue Aug 27 08:45:48 2019'
```

(Plan2 from Ken)
```
* reboot of rh76hv-01 failed: delegate=rh76hv-02, client=pacemaker-controld.5743, origin=rh76hv-02,
last-failed='Tue Aug 27 08:45:48 2019' (a later attempt succeeded)
```

I agree with Ken's proposal, which is not much different from what I discussed with the members before.

Best Regards,
Hideo Yamauchi.

**Comment by wenningerk** [comment]
> @wenningerk and @HideoYamauchi, how about:
> 
> ```
> * reboot of rh76hv-01 failed: delegate=rh76hv-02, client=pacemaker-controld.5743, origin=rh76hv-02,
> last-failed='Tue Aug 27 08:45:48 2019' (a later attempt succeeded)
> ```

Having a textual explanation at the end probably makes it less prone for misunderstandings when seen for the first time (or not so often). While marking in front might give a quicker overview for the experienced user. Guess I could live with both.

**Comment by HideoYamauchi** [comment]
Hi Ken,
Hi wenningerk,

I will once again discuss the two ideas with the members.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,
Hi wenningerk,

I discussed with our members.
We want to choose the following crm_mon display.

```
Failed Fencing Actions:
* reboot of rh76hv-01 failed: delegate=rh76hv-02, client=pacemaker-controld.5743, origin=rh76hv-02,
last-failed='Tue Aug 27 08:45:48 2019' (a later attempt succeeded)
```

How about it?
If there is no objection, I will conduct PR again next week.

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

That looks good to me.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Thank you for your consent.
I will wait this week for any other opinions.

After that, if there is no other opinion, create a new PR.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Sorry....I deleted the PR by mistake.
PR was also closed.

I will issue a new PR soon.

Best Regards,
Hideo Yamauchi.

**Pull request closed without merging**
