### PR TITLE
Create new libpacemaker source file for functions related to scheduling fencing

### PR DESCRIPTION
**Pull request by kgaillot**
This is part of a general "best practices" project for libpacemaker (narrowly defined to following current Pacemaker development guidelines). Some of the source files were ridiculously huge, and this is a step toward making them more manageable.

### CODE REVIEW

**Comment by kgaillot** [comment]
@clumens , can you review this when you get a chance? Low priority

**Comment by fabbione** [comment]
Please be aware that this PR breaks clang build:
https://ci.kronosnet.org/job/pacemaker-build-all-nonvoting-clang/1980/

**Comment by kgaillot** [comment]
> Please be aware that this PR breaks clang build:
> https://ci.kronosnet.org/job/pacemaker-build-all-nonvoting-clang/1980/

Actually it was already broken ... there's a fix in the 2.1 branch.

I've been holding off on the final 2.1.1 release (which would be pulled back into master) b/c a user (@ioguix) who wanted to do some testing is on holiday. I believe he will be back soon, but if not, I can pull the current 2.1 into master.

**Comment by fabbione** [comment]
> > Please be aware that this PR breaks clang build:
> > https://ci.kronosnet.org/job/pacemaker-build-all-nonvoting-clang/1980/
> 
> Actually it was already broken ... there's a fix in the 2.1 branch.
> 
> I've been holding off on the final 2.1.1 release (which would be pulled back into master) b/c a user (@ioguix) who wanted to do some testing is on holiday. I believe he will be back soon, but if not, I can pull the current 2.1 into master.

In general, build fixes should be merged back and forth as necessary. It's not so much about release, it's about keeping the tree sane, buildable and testable at all times, otherwise it defeats the purpose of CI with unnecessary failures.

**Comment by clumens** [comment]
This looks good to me.

**Pull request merged**
