### PR TITLE
Fix RHBZ#1287315: stonithd: Trigger cib_devices_update in case of …

### PR DESCRIPTION
**Pull request by wenningerk**
…deletion of just an attribute

### CODE REVIEW

**Comment by wenningerk** [comment]
If we are anyway doing cib_device_updates we can as well spare stonith_device_remove and all the parsing for the resource-name and the subsequent looping through the xml-code.

**Comment by kgaillot** [comment]
Looks great. Have you tested it?

**Comment by wenningerk** [comment]
Well, tried to reproduce the behaviour that deleting an attribute removes the whole device, which was reproducible very well in my test-scenario before.
CTS is still running...

**Comment by kgaillot** [comment]
Let me know if CTS has any issues, but it sounds like it's good. You can mark the RH bug as POST.

**Comment by wenningerk** [comment]
Had moved it already to POST once I had the fix in my pacemaker-repo on github. Was that premature?

**Comment by kgaillot** [comment]
It's not a big deal, because POST is mainly informational and doesn't lead to any actions. But the intent is to indicate that the fix has been included upstream, so it's best to wait and include the final upstream commit number.

**Comment by wenningerk** [comment]
As anticipated no issues with CTS...

**Pull request merged**
