### PR TITLE
[WIP] Prepare XSL template for 2-to-3 schema upgrade

### PR DESCRIPTION
**Pull request by jnpkrn**
A change a commit.

Commit message extensions may arrive later, it's probable I'll need
to backtrack in changes if any conflict arises, anyway.

### CODE REVIEW

**Comment by jnpkrn** [comment]
Still in progress, not even very suitable for part-wise merge.

Immediate TODO:
- rename `extra` flag in the internal transform table to `apply-only` and
  drop initial and trailing `|` from the syntax (formerly meant to syntactically
  denote one type of projected `extra`)
- ensure using multiple definitions in internal transform table differing
  on `apply-only` are possible
- use the above points to implement infinity-to-one-otherwise-drop
  for `default-resource-failure-stickiness`, possibly requiring some
  more internal refactoring
  . i.e. `apply_only="INFINITY" with="1"` vs. plain `with=""` (for drop)

**Comment by jnpkrn** [comment]
`s/apply-only/in-case-of/`
and
```diff
-apply_only="INFINITY" with="1"
+in-case-of="-INFINITY" redefined-as="1"
```

So, first (and hopefully most painful amongst upcoming ones) batch
of the changes is somewhat ready.

**Comment by kgaillot** [comment]
PE regression tests are failing due to transform output. Try rebasing on latest 2.0 branch; if there's still output, it'll need a closer look

**Comment by jnpkrn** [comment]
On 13/02/18 16:09 -0800, Ken Gaillot wrote:
> PE regression tests are failing due to transform output. Try
> rebasing on latest 2.0 branch; if there's still output, it'll need
> a closer look

The plan was to look at that once the transformation is completed.
One of the ideas is to apply on all those pengine/test10 CIBs at
once since testing the conversion is orthogonal to testing Policy
Engine.

-- 
Jan (Poki)

**Comment by jnpkrn** [comment]
On 14/02/18 10:06 +0100, Jan Pokorný wrote:
> On 13/02/18 16:09 -0800, Ken Gaillot wrote:
>> PE regression tests are failing due to transform output. Try
>> rebasing on latest 2.0 branch; if there's still output, it'll need
>> a closer look
> 
> The plan was to look at that once the transformation is completed.
> One of the ideas is to apply on all those pengine/test10 CIBs at
> once since testing the conversion is orthogonal to testing Policy
> Engine.

Alternatively, there would be a way to suppress those messages, with
the benefit lying in verification that the conversion will have no
effect on the actual resource manager responses.

-- 
Jan (Poki)

**Comment by jnpkrn** [comment]
Looks like a function-like macro to compare (recursively?) the rules
would be handy.

**Comment by kgaillot** [comment]
The transform seems to have false positives; from the first failed PE test:

  Test container-is-remote-node: Place resource within container when container is remote-node
      * ERROR:   Output was written to stderr
Cluster properties: dropping cluster-infrastructure for matching heartbeat|openais|classic openais|classic openais (with plugin)|cman
Cluster properties: ... corosync (2+) infrastructure can be used instead, though the value is not of significance
      * FAILED:  summary changed

That test does have corosync:

        <nvpair id="cib-bootstrap-options-cluster-infrastructure" name="cluster-infrastructure" value="corosync"/>

**Comment by kgaillot** [comment]
I haven't had a chance to make any changes to stonith-action, so let's keep that out for now. If I get to it before final release, we can add it back.

**Comment by jnpkrn** [comment]
On 15/02/18 14:47 +0000, Ken Gaillot wrote:
> The transform seems to have false positives; from the first failed PE test:
> 
>   Test container-is-remote-node: Place resource within container when container is remote-node
>       * ERROR:   Output was written to stderr
> Cluster properties: dropping cluster-infrastructure for matching heartbeat|openais|classic openais|classic openais (with plugin)|cman
> Cluster properties: ... corosync (2+) infrastructure can be used instead, though the value is not of significance
>       * FAILED:  summary changed
> 
> That test does have corosync:
> 
>         <nvpair id="cib-bootstrap-options-cluster-infrastructure" name="cluster-infrastructure" value="corosync"/>

Ah, thanks for spotting.  I need to harden the variable Replacement
evaluation so that only 0..1 match is contained, no more, which is
the cause here and I partly expected there may be still residing such
holes that I've been fighting with at other places already (actually
those places may be possibly simplified again after this Replacement
sanitizing).

What will partially help with that is that I now model the internal
replacement tables themselves with RelaxNG schema, which provides
the way to enforce some kind of internal normalization, as
unboundedness pledges for significant complexity creep otherwise
(as if it's not complex enough already).

Also, apparently I need more coverage with targeted tests.

On 15/02/18 17:42 +0000, Ken Gaillot wrote:
> I haven't had a chance to make any changes to stonith-action, so
> let's keep that out for now. If I get to it before final release, we
> can add it back.

Ok.  Secretly hope that the strict binary decision for stonith-action
will win :)

-- 
Jan (Poki)

**Comment by kgaillot** [comment]
Thanks, this will get us to rc1. Finishing the rest will give us a good point at which to do rc2.

**Comment by jnpkrn** [comment]
Ok, will repick some iterative changes also made in `regression.sh`
and will rebase non-merged + to-be-added commits as a separate PR.

**Comment by jnpkrn** [comment]
Overlooked that no changes made to former commits were missing,
thanks for serving it as fresh as you could for `-rc1`!
Continuing with #1422.

**Pull request merged**
