### PR TITLE
Fix: stonith-ng: make fencing-device reappear properly after reenabling

### PR DESCRIPTION
**Pull request by wenningerk**

### CODE REVIEW

**Comment by yuusuke** [comment]
With this fix, in Pacemaker - 1.1.18 or later, stonith - ng updates STONITH device information based on CIB 's change of lrm_resources.
I thought that the change of lrm_resources has nothing to do with updating STONITH device information, but is that a mistake?
If so, please tell me in what cases will you need to update the STONITH device information?

**Comment by wenningerk** [comment]
I'm not 100% sure if I get your question right ...
Of course the fencing infra-structure is configured via the CIB.
It is possible to enable/disable fencing devices being used (on a certain node) using location-constraints and target-role.
What doesn't work is usage of complex location-constraints dependent on e.g. attributes so that their result for a node can change over time without the constraint being altered. That is because stonithd (fenced) uses the pengine (schedulerd) code just once to evaluate the rules and afterwards it listens just for certain changes in the CIB and it doesn't periodically reevaluate rules (cluster-recheck-interval) or listen on attributes being altered.
What might be a little confusing is that the state of a fencing-resource doesn't have to account as started for it to be used, although - as a consequence of the statement above - it is necessary that starting isn't prevented by location-rules or target-role.

**Comment by wenningerk** [comment]
For the case that this was your point ...
The check in stonithd is using the first one.
include/crm/msg_xml.h:#  define XML_CIB_TAG_RESOURCES		"resources"
include/crm/msg_xml.h:#  define XML_LRM_TAG_RESOURCES     	"lrm_resources"

**Comment by yuusuke** [comment]
Thank you for answering
I understood that this fix is necessary for recalculating placement constraints.
I have one concern.
I think that change of lrm_resources occurs frequently.
When the scale of the cluster grows, is fenced able to withstand the load?
Now I can not try it because there is no environment, but in the verification of the large configuration I performed in the past often fenced died.

**Comment by wenningerk** [comment]
Sorry - took me a little bit to get your very valid point.
We should definitely have a look at that  and use a better search pattern.

**Pull request merged**
