### PR TITLE
Build: Install /etc/pacemaker directory for storing authkey file

### PR DESCRIPTION
**Pull request by gao-yan**

### CODE REVIEW

**Comment by jnpkrn** [comment]
Is there a bigger picture envisioned especially wrt. authkey location?
Asking, since the commit adds new variable/entropy without alignment
with the existing access methods and their defaults.

**Comment by gao-yan** [comment]
Could you be precise about "without alignment the existing access methods and their defaults"?

**Comment by jnpkrn** [comment]
E.g. how it combines with existing `DEFAULT_REMOTE_KEY_LOCATION`.

**Comment by gao-yan** [comment]
Makes sense. Will amend it with following-up changes.

**Comment by gao-yan** [comment]
Done.

**Comment by kgaillot** [comment]
Thanks! It's been on my to-do list for a while to consider something like this.

It's a bit of question which package should own it, but -cli seems as good a choice as any.

**Comment by jnpkrn** [comment]
Yep, thanks.

**Comment by jnpkrn** [comment]
Regarding RPM packaging (which is not strictly an upstream problem,
but it's sharing is highly pragmatic), I'd lean towards `-core` subpackage
approach (currently, I have 31 packages like that on the system vs. 18
occurrences of `-base`;  `rpm -qa --qf '%{NAME}\n' | grep `\-...$'`).

**Comment by kgaillot** [comment]
> Regarding RPM packaging (which is not strictly an upstream problem,
> but it's sharing is highly pragmatic), I'd lean towards -core subpackage
> approach (currently, I have 31 packages like that on the system vs. 18
> occurrences of -base; rpm -qa --qf '%{NAME}\n' | grep-...$'`).

-common is also very popular, especially when it can be noarch

**Comment by jnpkrn** [comment]
You are right, it wins by one in this unofficial popularity context (32x).

**Pull request merged**
