### PR TITLE
fix Chinese garbled

### PR DESCRIPTION
**Pull request by daaitudian**
fix Chinese garbled

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi,

I merged the other NLS pull request, so this would have to be redone for the new code (in the add_desc() function).

I don't quite understand the cause of the problem, though. With this PR, the XML-escaped string must be translated (with XML escapes in the translation). I would expect that translating the original string in natural language, and then XML-escaping the translation, would be more effective. Maybe this was only needed with the previous code because the translated string wasn't XML-escaped? Does the problem still occur with the new code, which does escape the translation?

**Comment by daaitudian** [comment]
Yes, the newly merged NLS also has this problem. 
Chinese through crm xml_escape method may be the cause of garbled characters. So  I would like to ask if this method is also necessary in Chinese?

**Comment by kgaillot** [comment]
ok to test

**Comment by kgaillot** [comment]
Thanks! I like this approach. I'm not sure it handles all possible character sets but it's a good start for what we need now.

**Comment by daaitudian** [comment]
Thanks.

**Pull request merged**
