### PR TITLE
Fix generation of books in PDF format

### PR DESCRIPTION
**Pull request by kgaillot**
... with a few minor corrections to the books themselves

### CODE REVIEW

**Comment by kgaillot** [comment]
Even with these changes, older versions of some of the relevant software (e.g. the versions in RHEL 7) will have some issues building PDFs (though you can hit enter 'R' when prompted to continue past them). The python3-sphinx version is likely the most relevant, but some of the LaTeX package versions may be relevant as well.

@clumens , can you review this when you get a chance?

**Comment by clumens** [comment]
This all looks good to me.

**Comment by wenningerk** [comment]
Could we add a podman/docker based build-target for the documentation?

**Comment by kgaillot** [comment]
> Could we add a podman/docker based build-target for the documentation?

In what sense? Running the sphinx-build command in a container?

**Comment by wenningerk** [comment]
> 
> In what sense? Running the sphinx-build command in a container?

Yes - pulling base-images + packages from well defined sources

**Comment by kgaillot** [comment]
> > In what sense? Running the sphinx-build command in a container?
> 
> Yes - pulling base-images + packages from well defined sources

That's an interesting idea since there are so many crazy dependencies for PDFs in particular, but containers have their own dependency mess. It could be worthwhile to post the commands on the wiki though as an example.

**Comment by wenningerk** [comment]
> That's an interesting idea since there are so many crazy dependencies for PDFs in particular, but containers have their own dependency mess. It could be worthwhile to post the commands on the wiki though as an example.

I have quite positive experience with building rpms with mock inside docker-containers. These just had nasty requirement for privileged containers which led to issues with non x86_64 architectures on travis as these machines are actually containers already. But building docs should be less demanding regarding bind-mounts and stuff I guess.

**Pull request merged**
