### PR TITLE
Mid: fenced: Change query timeout calculation.

### PR DESCRIPTION
**Pull request by HideoYamauchi**
Hi All,

This PR is a revised version of the next PR discussion.
 - https://github.com/ClusterLabs/pacemaker/pull/2508
 - https://github.com/ClusterLabs/pacemaker/pull/2515

Best Regards,
Hideo Yamauchi.

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi Hideo,

This looks good. There is one small conflict to be resolved due to a comment moving in a recently merged PR.

You don't have to do a new PR for such a small change; feel free to force-push the updated commit (git push origin +_commit-id_:_branch_)

**Comment by HideoYamauchi** [comment]
Hi Ken,

I tried it.
I'm not familiar with git, but did it work?

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
> Hi Ken,
> 
> I tried it.
> I'm not familiar with git, but did it work?
> 
> Sorry...It seems that it failed because the modified file is strange.
> I will issue PR again.
> 
> Best Regards,
> Hideo Yamauchi.

Hi Hideo,

It cleared the old commit but didn't upload the new one. From the command line, it should be like

    git push origin +_new-commit-id_:change_query5

replacing _new-commit-id_ with the ID of the updated commit as shown by "git log".

**Comment by HideoYamauchi** [comment]
Hi Ken,

> It cleared the old commit but didn't upload the new one. From the command line, it should be like
> 
> ```
> git push origin +new-commit-id:change_query5
> ```
> 
> replacing _new-commit-id_ with the ID of the updated commit as shown by "git log".

Sorry...
I passed each other. I sent a new PR.

I am also grateful for the commands I was taught.
I will study git commands a little more.

Many thanks,
Hideo Yamauchi.

**Pull request closed without merging**
