### PR TITLE
Add version control to resources and simple constraints

### PR DESCRIPTION
**Pull request by igor-tsiglyar**
These features are focused on reducing time that cluster spends in idle state when update of resource agents takes place.
Crmsh interface is also extended to support new functionality.
Please, review and leave comments.

### CODE REVIEW

**Comment by kgaillot** [comment]
The resource agent meta-data already provides the version, for example:

   <resource-agent name="Dummy" version="1.0">
   <version>1.0</version>

Looking at the example in the OCF specification (https://github.com/ClusterLabs/OCF-spec/blob/master/ra/ra-metadata-example.xml), the version tag was intended for the OCF standard version that the RA was written for, rather than the RA version itself, which was intended to go in the resource-agent tag's version attribute. Unfortunately, RA writers appear to have been confused by this, and existing RAs sometimes put the RA version in either or both locations. (This includes the Pacemaker-provided RAs, which I'll make a note to fix ...) Also, the spec implies that the version can be free-form, rather than strictly numeric.

Despite the confusion, it would be better to grab the version from the metadata, rather than add a new action. This will reduce duplication, take advantage of existing resource agents that do define it correctly, and handle non-OCF resource agents (legacy heartbeat, nagios, LSB, systemd) because they already have XML templates that define a version (usually "0.1").

The ideal would be to find an existing place where the cluster reads the metadata, and save the version then, so a separate process doesn't need to be spawned just to get the version.

For this new feature, we can look strictly at the resource-agent tag's version attribute, and only consider it if it has the expected format. For RAs that don't provide a version, or provide an invalid one, we can default to "0.1" rather than give an error, for backward compatibility with existing agents.

Can you give examples of problems that this new capability solves? Is the main goal to improve rolling upgrades, when some nodes might have one version of an RA and other nodes might have another version?

**Comment by igor-tsiglyar** [comment]
Thanks for useful suggestion! I've updated commits.
Yes, you got it right about the main goal. Also versions themselves could help preventing inconsistent resource/configuration pairs from starting.

**Comment by kgaillot** [comment]
This feature is promising, but I think that the start action is not the right place to check the version.

If someone sets a version constraint, they will expect that the cluster will avoid placing the resource on nodes without the correct version. If we check at the start action, what will instead happen is that the start may be attempted on the wrong node, but will fail and then be tried somewhere else. This leaves a failed action in the cluster status that must be manually cleared, and could result in unnecessarily imbalanced placement.

I think it would be better to check the version when recording the probe result. Before starting a resource, Pacemaker first probes it on all nodes. A probe is simply a monitor action with an interval of 0. Probes are done mainly to ensure that the service is not already running somewhere, but also to check if a resource cannot be placed on the node (because the software is not installed, for example). When the lrmd gets a probe result, if the probe result is OK, it could then check the RA version and return the new error code if it doesn't match. When the policy engine evaluates the probe result, if it is the new error code, it could set a location constraint banning the resource from that node.

By doing it that way, we can avoid trying to start the resource on a node with an inappropriate version, and we can avoid a failure showing up in the cluster status. It is tempting to use PCMK_OCF_NOT_INSTALLED instead of a new code, because the policy engine will already handle that case appropriately, and it logically fits, but that would still show up as a failed action in the cluster status.

**Comment by bubble75** [comment]
Alternative/additional usage of this feature could be to allow to use RA version in resource rules (and probably location rules) as a "light-weight" per-node attribute.
This would give a *huge* flexibility during rolling cluster updates.

**Comment by kgaillot** [comment]
I misunderstood the original design; I see now that you are providing two separate mechanisms for restricting by version. The user specifies rsc_version in the resource configuration; the lrmd compares that with the actual RA version when trying to start the resource, but when using constraints, the PE only checks the configured rsc_version against the constraint version, and does not use the actual RA version.

I think my previous point still applies, that it is better to get the node's RA version when doing the probe, rather than the start. But also, I think we should get rid of rsc_version altogether. Restrictions on resources are always handled by constraints, not by modifying the resource configuration itself. The constraint interface is better, and  we can do away with rsc_version, if we can get the PE to compare against the actual RA version on the node.

A probe, like any other RA action, is executed like this: the PE creates a probe action in the transition graph that it sends to the crmd; the crmd asks the lrmd to execute the action; the lrmd calls the resource agent; the resource agent executes the action; the lrmd returns the result to the crmd; if the result is successful, the crmd proceeds with the next step in the transition graph, otherwise it aborts the transition and asks the PE to create a new one.

So, version constraints could go like this:

1. When the PE creates a probe action, it can pass along any version restriction that applies. All communication between components is via XML messages, so this just involves adding some new XML fields to the message. There is no documented schema for this XML between components; it's considered internal to Pacemaker, so the source code is the only reference.

2. When the lrmd gets a successful probe result, if the original request included version restrictions, the lrmd can get the metadata, compare the version, and return the new error code if it doesn't match. (If the probe failed, we're going to return that failure already, so there's no need to check the version.)

3. The crmd will abort the transition due to the new error code, and ask the PE for a new transition graph. The PE can see the new error code for the probe in the resource operation history, and add a location constraint banning the resource from that node.

I may not have thought through all the implications, so feel free to comment and discuss.

**Comment by igor-tsiglyar** [comment]
bubble75,
Yes, you can add resource-agent version attribute to each node like this
```
      <node id="2" uname="node2">
        <instance_attributes id="nodes-2">
          <nvpair id="nodes-2-Dummy-version" name="Dummy-version" value="1.0"/>
        </instance_attributes>
      </node>
```
and then configure corresponding location rule:
```
      <rsc_location id="loc" rsc="A">
        <rule score="INFINITY" id="loc-rule">
          <expression attribute="Dummy-version" operation="eq" value="1.0" type="version" id="loc-rule-expression"/>
        </rule>
      </rsc_location>
```
But this will be advisory constraint, that is, if no matching node found, resource still starts on some node.
Our resource versions are mandatory: resource can only starts on the node with proper resource agent version, otherwise it's an error.

Concerning our expansion of location constraints: constraints contradicting configured resources won't be created.
For example, if we have resource A with version 1.0, such constraint:
```
    <rsc_location id="loc" rsc="A" rsc-op="gt" rsc-version="1.1" score="INFINITY" node="node1"/>
```
will have not effect.
So it's just a way to keep resources and their constraints synchronized.

**Comment by igor-tsiglyar** [comment]
Ken,
I like your point about checking versions with probe. I have updated this part. Please share you opinion about places I have chosen to compare versions and add version restrictions to message. I have also saved wrong version return code because I would like to have it shown in crm_mon, so user can easily find out where the problem lies.

When it comes to configuring resource versions, am I right, that you suggest to add new constraints like
```
    <rsc_version id="A-ver" rsc="A" value="1.0" />
```
?

**Comment by kgaillot** [comment]
Regarding using an attribute rule instead of this new feature, you could make the rule mandatory by inverting the sense: set -INFINITY wherever the version does not match. Updating your example:

    <rsc_location id="loc" rsc="A">
        <rule score="-INFINITY" id="loc-rule">
          <expression attribute="Dummy-version" operation="ne" value="1.0" type="version" id="loc-rule-expression"/>
        </rule>
    </rsc_location>

The real drawback with this approach is that it relies on someone setting the node attribute correctly, instead of getting it directly from the RA, which is obviously more reliable.

Before discussing the recent code changes, let's discuss whether it would be sufficient to add a new CLI tool (or maybe an option to crm_attribute or crm_resource) that would check the resource agent metadata and set the node attribute automatically. Someone could call the script after doing an upgrade, before taking the node out of standby or maintenance mode.

The current approach would be more flexible, but I see a number of difficulties that still have to be addressed. The attribute approach would be more limited, but very simple.

**Comment by igor-tsiglyar** [comment]
I've noticed that I haven't told much about problems we want to address with the new feature. I think it would be useful to cover this topic more deeply for the sake of our discussion.

So, the nodes are being updated consequently (from user's perspective, under nodes we assume resources, their code etc).

What issues do we have:
- Resource Agents with old version are starting with new configuration on nodes that haven’t been upgraded yet (as result, the timeouts are wrong, the dependencies are wrong etc)
- Resource Agents with new version are starting with old configuration on the upgraded nodes, before we had a chance to update the configuration (same as before result implies)
-  Dependencies that were correct for old versions are not for new and vise versa

That's why we need:
- To have Resource Agent version VS configuration version – this allows to have correct parameters when starting the resource (check that RA version corresponds with configuration version during probe)
- Include configuration version into the colocation/order rules to handle dependencies

The reason we don't want to use location rules instead of automation version checking is that it seems overcomplicated from the configuration standpoint: user needs to update the location rule manually along with updating the configuration, which makes user change 2 pieces of CIB.
That's why we prefer to have the resource version as part of configuration, so the resource can start right away on the right node.

You correctly pointed out the drawback of attribute approach. And even having special tool that updates node attributes won't help if user forgets to use it.

What else difficulties do you see?

**Comment by kgaillot** [comment]
If I follow correctly, the expected use would be something like this:

1. Assume a cluster with nodes node1 and node2. Both nodes have RA version 1.0, which accepts the option "opt1".

2. Create a resource with version="1.0" opt1="value1". At this point, it may run on either node.

3. Upgrade the RA on node1 to version 2.0, which has the additional option "opt2". Now, the resource configuration forces it to run on node2 only.

4. Reconfigure the resource with version="2.0" opt1="value1" opt2="value2". Now, the resource configuration forces it to run on node1 only.

5. Upgrade node2. Now the resource can run on either node again.

Is that correct? Or do you envision having multiple versioned resource configurations in place at the same time for the same resource?

How do you envision the cluster detecting the upgrade? Whether it checks the version at probe or start, it won't learn that the installed version changed, if the resource is already running somewhere.

**Comment by bubble75** [comment]
I was thinking about something like (in crmsh syntax):
`primitive resource ocf:provider:agent \
    params 3: rule #ra_version gte "1.0" param1="value1" \
    params 2: rule #ra_version lt "1.0" param2="value2" \
    params 1: param3="value3" param4="value4" ...
`
This would require detecting RA version (and saving it to some kind of node attribute - with some special handling in crmd) in lrmd (to be compatible with pacemaker_remote) though.

**Comment by kgaillot** [comment]
@bubble75: Yes, that makes a lot more sense to me! With the rules in your example, the cluster could start the resource on any node, but would choose different parameters based on the installed RA version.

To restrict a resource to certain versions, we could use location constraints with the same attribute. For example, to require resource A run on nodes with an RA version > 1.0 (framed as a ban on other nodes, which makes it mandatory even if no available nodes have the desired version):

    <rsc_location id="loc" rsc="A">
        <rule score="-INFINITY" id="loc-rule">
          <expression attribute="#ra-version" operation="le" value="1.0" type="version" id="loc-rule-expression"/>
        </rule>
    </rsc_location>

Versioned colocation and ordering constraints would be unnecessary. For those cases, each resource could have its own versioned location constraint, and then a normal colocation/ordering constraint would have the desired effect.

Implementing versioned resource parameters would be straightforward, and wouldn't require setting node attributes or any state. The PE would ignore the rules itself, and simply pass them to the lrmd with the start action; when such rules are present, the lrmd would make a metadata call to get the version, then call start with the appropriate parameters. (There would be a race condition if an upgrade happened between the metadata and start calls, but since the upgrade *should* happen with the node in standby or in maintenance mode, and the window will be tiny, I think we can ignore that. Other than that, this approach has the beauty of always being perfectly up-to-date.)

Implementing versioned location constraints would be much more difficult. The PE can't know the nodes' RA versions until after the probes are done, so the resources can't be placed in a single transition. That means the RA versions would need to be cached somewhere, which brings up complications with keeping that information up-to-date. And while probes are the natural place to get the installed version, that does pose more complications, which I will go into later if we need to.

@igor-tsiglyar, does the rule-based interface make sense to you? Rules are an already supported construct in pacemaker that users are familiar with, and they're quite flexible. Pacemaker already has a precedent for a node pseudo-attribute: it expands "#uname" in rules to the node's name. Would versioned resource parameters solve most of your issues? It would be much simpler to implement only that and leave versioned constraints for another time.

**Comment by bubble75** [comment]
@kgaillot, crmd caches RA metadata anyways (by calling all RAs with 'meta-data' parameter), probably that could be delegated to lrmd/remoted.
That way lrmd may add/update version attributes for RAs in attrd (locally or via ipc proxy) with some _to_be_defined_ names (probably your private attributes may be used?).
#ra-version needs to be mapped to values of that attributes before actual calls.

**Comment by bubble75** [comment]
@kgaillot 
not only #uname, but also #kind (cluster, remote, container).

**Comment by kgaillot** [comment]
@bubble75, I had completely forgotten about the crmd metadata cache.

@igor-tsiglyar, see crmd/lrm.c:get_rsc_metadata(). It is called by build_operation_update() in order to support reloads. That gets called several places, including do_lrm_query() which is used to send information to the DC when joining the cluster, and send_direct_ack() and do_update_resource() which reply to CRM ops. We should be able to reuse this metadata call and not need an additional one. We can feed the version from the local crmd to the DC, and the DC can supply it to the PE. It should be fairly straightforward from there.

**Comment by kgaillot** [comment]
@bubble75, I see your point about Pacemaker Remote nodes -- crmd won't grab any metadata from them, because get_rsc_metadata() always uses the local LRM connection to get the metadata. Theoretically, it could be modified to use the remote connection when appropriate. I don't think it would be necessary to involve attrd or do the caching in lrmd (which sounds like a lot of overhead for reporting crmd op results), but the local crmd might need to maintain separate metadata caches for any remote connections hosted through it. I'm also not sure what the proper response would be if the remote connection is failed or stopped when we need the metadata.

**Comment by kgaillot** [comment]
One complication with remote/guest nodes is that we can't get their version info (or supply it to the DC or PE) until after they're successfully up. So the PE couldn't place versioned resources on remote/guest nodes until they are online (currently, it can start the remote connection and place resources on the remote in the same transition).

**Comment by bubble75** [comment]
@kgaillot. Just a bit of loud-thinking: Keep in mind that with "resource-discovery=never rule -inf #kind ne remote" crmd will never get that metadata if RA is installed only on remote nodes - perfectly valid case. And, permissions issues are also theoretically possible, because crmd is run under hacluster user. IMHO lrmd is a best place to do any RA calls from all points. Yes, that would add some complications (actually protocol extension) to a LRM protocol. But, from my point that is the only architecturally correct solution.

**Comment by kgaillot** [comment]
@bubble75, the actual metadata call is already done via the lrmd -- see crmd/lrm_state.c:lrm_state_get_metadata(). It's just the caching that's done by the crmd.

I don't think the rule you mentioned would be an issue if build_operation_update()->get_rsc_metadata() used the remote lrm connection when reporting remote results (with a separate metadata cache for each remote).

However, resource discovery in general is the main complication I was alluding to regarding getting the resource version via probes. In addition to resource-discovery=never as you mentioned, there's also enable-startup-probes=FALSE, and guest nodes are never probed currently. If there's no probe on the allowed nodes for a resource, we won't have the version available when placing the resource. Maybe we could introduce a "version probe" to be scheduled when a full probe isn't.

My suggestion would be to ignore this for the first implementation, and say that versioned resources are only supported for cluster nodes with probes enabled, then address those limitations later. I'm thinking it may be useful to break the project into more manageable pieces: (1) implement versioned resource parameters for probed cluster nodes (using the existing metadata cache); (2) add support for when nodes are not probed; (3) add support for remote/guest nodes; (4) add support for versioned location constraints.

**Comment by bubble75** [comment]
@kgaillot 
> the actual metadata call is already done via the lrmd -- see
> crmd/lrm_state.c:lrm_state_get_metadata(). It's just the caching that's done by the crmd.

Hmm... May be you are aware when/by what commit that was done? I recall, when I was implementing a strict selinux policy for pacemaker (several years ago, before the "official" one was released), I was surprised that crmd needs permission to call RAs. I traced that to metadata calls.

**Comment by kgaillot** [comment]
My mistake, it goes through the lrmd client API, but it's actually implemented as a local call. You're right, that should be an lrmd op.

**Comment by kgaillot** [comment]
There has been a lot of discussion here, so let me summarize how I see things:

I think we should focus on versioned parameters for the first pull request.

The interface would use a new pseudo-node-attribute '#ra-version' with rules as described in http://clusterlabs.org/doc/en-US/Pacemaker/1.1-pcs/html-single/Pacemaker_Explained/index.html#_using_rules_to_control_resource_options

For example, to create a resource A using parameters "widget=1 really-old-param=5" when version <= 1.0, and "widget=1 super-new-param=10" when version > 1.0:

    <primitive id="A" class="ocf" type="myRA" provider="me">
        <instance_attributes id="ia01" score="3">
            <rule id="ia01-r01" score="INFINITY" >
                 <expression id="ia01-r01-e01" type=version attribute="#ra-version"
                     operation="gt" value="1.0"/>
            </rule>
            <nvpair id="ia01-nv02" name="super-new-param" value="10"/>
        </instance_attributes>
        <instance_attributes id="ia02" score="2">
            <rule id="ia02-r01" score="INFINITY" >
                 <expression id="ia02-r01-e01" type=version attribute="#ra-version"
                     operation="lte" value="1.0"/>
            </rule>
            <nvpair id="ia02-nv02" name="really-old-param" value="5"/>
        </instance_attributes>
        <instance_attributes id="ia03" score="1">
            <nvpair id="ia02-nv01" name="widget" value="1"/>
        </instance_attributes>
    </primitive>

Functionally, this would not constrain where pacemaker could place the resource, only what parameters it would send when starting the resource.

For implementation, I think it will be simplest if we ignore the existing crmd metadata cache for now, and make an extra metadata call when executing the start action. That way, we bypass all the issues with probing, remote/guest nodes, and cache staleness.

The lrmd would have to do the metadata call (so it's done on the correct node even if it's remote), so I'm thinking the PE will need to skip its usual rules processing when '#ra-version' is used, and instead pass the version tests to the lrmd with the start operation. The lrmd will then make the metadata call to get the version, choose which parameters to use based on the version, and call start.

Expressions may be combined, so '#ra-version' might be mixed with other comparisons. The PE will still need to evaluate the non-#ra-version rules, ending up with a list of version expressions and their associated parameters, which it can then pass to lrmd. So for example, if someone had rules for (#ra-version > 1.0 and flavor == vanilla) and (#ra-version > 1.0 and flavor == chocolate), the PE would do its usual processing for the 'flavor' node attribute, and end up passing (#ra-version > 1.0) with the appropriate set of parameters for that case to lrmd (and so on for whatever other version tests were configured). Essentially: if this expression does not use #ra-version, evaluate it, else add the version comparison and associated paramaters to the list I will pass to lrmd.

This would be the least complicated place to start, and I think it would provide most of the desired capability.

**Comment by bubble75** [comment]
+1
One note: mixed rule expressions may require passing several rules with identical #ra-version conditions but with different parameter sets (that is imho better than collapsing them in the PE). lrmd should be ready to process them. Also, it should handle complex enough rules like '#ra-version ge 1.0 and #ra-version lt 2.0 param=value1' and '#ra-version lt 1.5 or #ra-version gt 2.0 param=value2'. And that may be tricky when parameter lists intersect having different values for the same param. Btw, how PE handles that for other attributes now with version 1.4 in the example above?

**Comment by kgaillot** [comment]
If there are multiple matches, the one with the highest score wins.

**Comment by igor-tsiglyar** [comment]
Sorry for my long silence.

The design you have come up with suits our needs. I will create a pull request in 1.1 branch as soon as the work is done.

We should probably keep this pull request for the further discussion.

**Comment by kgaillot** [comment]
Great, thanks. Master branch is appropriate -- we're too late in the release cycle for 1.1 branch.

**Comment by kgaillot** [comment]
Closing in favor of implementation in #1063

**Pull request closed without merging**
