### PR TITLE
Fix a regression in crm_attribute output

### PR DESCRIPTION
**Pull request by clumens**

### CODE REVIEW

**Comment by kgaillot** [comment]
looks like something changed on freebsd, which is odd ...

**Comment by clumens** [comment]
Looks like error messages are different between FreeBSD and Linux here.  We already had a sed line in cts/cts-cli.in to take care of this in one spot, so I'll just add another.

**Comment by kgaillot** [comment]
Thanks!

**Comment by kgaillot** [comment]
Ah ... this should be against main branch, 2.1.4 release is already out

**Pull request closed without merging**
