### PR TITLE
Mid: attrd: Support of the change of the delay(dampen).

### PR DESCRIPTION
**Pull request by HideoYamauchi**

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi Hideo,

Just to confirm my understanding, it looks like this is desired because currently attrd_updater with -d/--delay works when creating new attributes, but is ignored for existing attributes. Is that correct?

**Comment by HideoYamauchi** [comment]
Hi Ken,

I think so.
I think that it is a problem not to be able to change a value of dampen in ping resource agents.

When a dampen level cannot switch from the outside, it is maintained until attrd reboots.

Is there any point to be worried about?

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,

I understood the meaning of your question.
Do you say that you cannot change only dampen by attrd_upder command?

In the next command-line, the user cannot change the dampen level.

[root@coro1 ~]# attrd_updater -n TEST -d 200

In the next command-line, the user can change the dampen level.
It is necessary to appoint a value in a command-line now to change dampen.

[root@coro1 ~]# attrd_updater -n TEST -v 200 -d 200

I think that I should be able to change the dampen level by attrd_updeter command.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,

When there is d option, I think that it is necessary to work by update processing.
However, this change may influence it because the present conditions become the query processing.
I feel like adding an option of attrd_updater to change dampen.

Best Regards,
Hideo Yamauchi.

**Comment by beekhof** [comment]
> Just to confirm my understanding, it looks like this is desired because currently attrd_updater with -d/--delay works when creating new attributes, but is ignored for existing attributes.

It was sort of kind of on purpose like that.  Imagine two attrd_updater calls for the same attribute but with different -d values.  That would get really messy really quickly.

**Comment by HideoYamauchi** [comment]
Hi Ken,
Hi Andrew,

There is an insufficient function to my patch.
My patch does not have a function to invalidate dampen. (function to set zero in dampen)

I intend to send the function with a patch again.

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
I see Andrew's point about overlapping calls on different nodes (they can potentially be applied in the wrong order), but it seems useful to provide a mechanism like this one for changing or removing the delay.

I think it's reasonable to say that any user who changes the delay needs to manage that risk themselves, but it would be nice to warn them somehow. Maybe we can just add something to the man page.

**Comment by HideoYamauchi** [comment]
Hi Ken,
Hi Andrew,

What do you think of the patch which I revised?

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
After discussing this with Andrew more, I see that the potential problem arises from resetting the timer when the delay changes. If attributes keep coming in with different delays, it's possible they will never be written out (or written out much later than desired).

The likely solution will be to do an immediate write-out whenever the delay is changed.

The one issue not yet settled is whether the approach here (changing the delay with the attribute) is sufficient, or whether we should instead create a new command for changing the delay.

**Comment by HideoYamauchi** [comment]
Hi Ken,

At present, I do not feel the need of the change of the delay by the command.
At present, I think that it is enough if I can switch from a specific node by crm command and pcs command.
However, I think that the request of the change of the delay by the command is more likely to come out in the future.

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

I think a solution can be done along these lines:
* Add a new ATTRD_OP to attrd, to change the dampen value of an attribute (and do an immediate write-out of the attribute).
* Add a new command-line option to attrd_updater, to send the new ATTRD_OP to attrd.
* Make the ocf:pacemaker:ping resource agent call the new attrd_updater command in its "start" action. This will work because reconfiguring the resource (including dampen) causes it to be stopped and started.

The benefit of this approach is that scripts that repeatedly call "attrd_updater -n ... -d ..." with different dampen values won't cause either repeated write-outs or missed write-outs.

I'll plan for that in the future. Feel free to open a BZ to track it, or to work on it yourself, if desired.

**Comment by HideoYamauchi** [comment]
Hi Kena,

Okay!
I agree to your plan.
I help with the work of the change in you.

Best Regards,
Hideo Yamauch.

**Comment by HideoYamauchi** [comment]
Hi Ken,

I make the patch of the correction along your policy if you are busy.
This patch which I sent once withdraws it, and should I exchange it in different pullrequest?
# I think that the one that I made different pullrequest is good.

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

Either way is fine -- you can amend this pull request, or create a new one.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Okay!
I make new pullrequest.

Many thanks!
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
I intend to send a new patch early next week in different pullrequest.
The patch includes both corrections of attrd_updater and attrd.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
I make new pullrequest, this is closed.
I describe the link to this pullrequest in new pullrequest.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Sorry...
pullrequest of the new patch is going to be delayed a little more.

Best Regards,
Hideo Yamauchi.

**Pull request closed without merging**
