### PR TITLE
Update CTS for recent external software changes

### PR DESCRIPTION
**Pull request by kgaillot**
(with a few trivial unrelated fixes)

### CODE REVIEW

**Comment by kgaillot** [comment]
@clumens , can you review this? The issues related to the first few commits are making testing builds a pain ...

**Comment by kgaillot** [comment]
@wenningerk , I forgot clumens is unavailable today, can you review this?

**Comment by wenningerk** [comment]
having a look ...

**Comment by wenningerk** [comment]
> > Isn't all that usage of reply in a big 'if (reply != NULL)" block?
> 
> That's what I thought ;)
> 
> The problem is it was like
> 
> ```
> if protocol violation 1
>     reply = NULL
> if protocol violation 2
>     reply = NULL
> if protocol violation 3
>     reply = NULL
> if (reply != NULL)
>     do stuff
> ```
> 
> so if one of the earlier violations hit, the later ones (which tested attributes in reply) would trigger the assert before getting to the (reply != NULL) part

My mind somehow projected an else in there that doesn't exist :-)
And I had copied that thing to the ipc_pacemakerd ...
Apart from that extra/cluster-clean will probably leave over the directories under /dev/shm while removing all the files I didn't find anything.

**Comment by kgaillot** [comment]
> My mind somehow projected an else in there that doesn't exist :-)

Me too, that's why this happened ;)

> And I had copied that thing to the ipc_pacemakerd ...
> Apart from that extra/cluster-clean will probably leave over the directories under /dev/shm while removing all the files I didn't find anything.

Good point, I'll fix that separately from this PR

**Pull request merged**
