### PR TITLE
More careful handling wrt. procps-ng (and psmisc)

### PR DESCRIPTION
**Pull request by jnpkrn**
Non-exhaustive list:

* -cli:
  - ps: cibsecret, report.collector, SystemHealth & ClusterMon resources

* -cts:
  - after-test handling in CTStests.py in case of something unexpected

In case of pacemaker and -remote related initscripts/upstart jobs:
  - pidof

### CODE REVIEW

**Comment by jnpkrn** [comment]
Related: https://oss.clusterlabs.org/pipermail/developers/2018-May/001237.html

**Comment by jnpkrn** [comment]
`killall` actually comes from `psmisc` that was likewise missing.

**Comment by jnpkrn** [comment]
Also as a partial response to linked analysis, I hardened `crm_report`
a bit -- there should be no reason to look for whatever processes in
the system (also, there may be containerized ones!).
There are some considerations required when running CTS, so that's
left out of scope.

In turn, I introduced new dependency on `glibc-common` for `getent`,
but didn't add it explicitly since current Fedora packaging guidelines
on user managemenet don't deem it's necessary either (as opposed
to `shadow-utils`):
https://fedoraproject.org/wiki/Packaging:UsersAndGroups#Dynamic_allocation

**Comment by jnpkrn** [comment]
Asked at Fedora's packaging list to avoid guessing:
https://lists.fedoraproject.org/archives/list/packaging@lists.fedoraproject.org/thread/SP3A3ZHGDSKSZJRY3HXQSBEO22TEVZS2/

**Comment by jnpkrn** [comment]
I'd consider my approach valid per the lists's exchange.

Would also note that `killall` has a deficiency that group-based affiliation
is not a supported selector for `killall` (as opposed to `pkill`, both equally
non-POSIX commands).

**Comment by kgaillot** [comment]
There are numerous basic system utilities (ls, cat, ps, etc.) that we can assume are present without cluttering the spec. Is there any rpm-based distro or spin without psmisc and procps-ng? I would think it's far more likely that those package names would change or be different across distros than a distro wouldn't have ps.

**Comment by jnpkrn** [comment]
On 06/06/18 15:30 -0700, Ken Gaillot wrote:
> There are numerous basic system utilities (ls, cat, ps, etc.) that
> we can assume are present without cluttering the spec. Is there any
> rpm-based distro or spin without psmisc and procps-ng?

Looking at my Fedora installation, psmisc is only required by pcs[1] :-)
It also gets installed with a minimal install but I could prevent that
in kickstart easily.  So psmisc is a no-brainer.

Procps-ng depends on initscripts and dracut, both of which I could
drop in a container lightheartedly...

> I would think it's far more likely that those package names would
> change or be different across distros than a distro wouldn't have
> ps.

Distro != actual deployment (viz containers).


[1] https://bugzilla.redhat.com/show_bug.cgi?id=1231987

-- 
Jan (Poki)

**Comment by kgaillot** [comment]
I believe the SUSE package name is just "procps", so we'd have to update GNUmakefile as well.

**Comment by jnpkrn** [comment]
True:
https://build.opensuse.org/package/view_file/Base:System/procps/procps.spec
https://build.opensuse.org/package/view_file/openSUSE:Factory/procps/procps.spec

Let me amend the commit.

**Pull request merged**
