### PR TITLE
Add support for fencing "phases"

### PR DESCRIPTION
**Pull request by kgaillot**
This is the first bit of plumbing for being able to remap sequential topology reboots to all-off-then-all-on. It introduces the concept of fencing operaton "phases", where most (i.e. non-remapped) operations will have a single phase (0), but remapped reboots will go from phase 0 (reboot request) to 1 (remap to off) to 2 (remap to on).

The various action-specific properties (required status, timeout, etc.) need to be tracked separately by phase, so these revisions modify the structure members for those from scalar to array[3].

No remapping is done yet, so phase is always 0, and actual cluster behavior is unchanged.

### CODE REVIEW

**Comment by kgaillot** [comment]
These revisions plus later ones not yet submitted passed the fencing regression tests plus a 100-random-test CTS run.

**Comment by davidvossel** [comment]
I understand what you're doing. it should work. My only comment so far is with regards to the phasing scheme. Rather than reference the arrays using 0, 1, or 2. It would be more readable and easy to understand the code if we had some context within the code as to what 0,1,2 mean.

maybe something like

enum st_remap_phase {
st_phase_default = 0,
st_phase_off = 1,
st_phase_on = 2,
};

then use those values when accessing the phase arrays.

**Comment by kgaillot** [comment]
Good idea, amended commits.

**Comment by beekhof** [comment]
Probably want add st_phase_max = 3 to that enum instead of hard-coding 3 everywhere too.

**Pull request merged**
