### PR TITLE
Best practices for libpacemaker simulation functions

### PR DESCRIPTION
**Pull request by kgaillot**
This continues the best practices project for libpacemaker, focusing on simulation and injection functions (basically finishing what's in pcmk_simulate.c).

### CODE REVIEW

**Comment by kgaillot** [comment]
@clumens , here's another low-priority review

**Comment by clumens** [comment]
This all looks good to me.

**Comment by kgaillot** [comment]
retest this please

**Comment by kgaillot** [comment]
retest this please

**Pull request merged**
