### PR TITLE
Stop using deprecated type aliases

### PR DESCRIPTION
**Pull request by clumens**
Note: It occurs to me that I might not have caught all of these.  I worked on it by moving a deprecated alias behind PCMK__NO_COMPAT, trying to build, and fixing each file that failed.  It's possible other uses are hiding behind ifdefs that were not set in my build.  I'll try to track down more uses later.

### CODE REVIEW

**Comment by kgaillot** [comment]
Tiny request ... use "Refactor:" instead of "Fix:". Fixes get automatically pulled into the changelog for the next release, and users don't need to know about refactors

**Comment by clumens** [comment]
I found and fixed a couple more deprecated usages, all in tools/crm_mon_print.c.  I wonder if that file is somehow not getting the PCMK__NO_COMPAT define set.

**Comment by kgaillot** [comment]
> I found and fixed a couple more deprecated usages, all in tools/crm_mon_print.c. I wonder if that file is somehow not getting the PCMK__NO_COMPAT define set.

I'm sure there are a lot of files like that. It's defined in crm_internal.h. We should make all internal files include that for this purpose but I haven't done that.

**Comment by kgaillot** [comment]
Thanks! BTW the reason this is significant is because we have e.g. both crm_node_t in libcrmcluster and pe_node_t in libpe_status, and the old "node_t" was easily confusing on that count (and made searching more difficult).

**Pull request merged**
