### PR TITLE
Fix: HealthSmart: Check the parameter values of check_temperature to …

### PR DESCRIPTION
**Pull request by bixiaoyan1**
…avoid error output

### CODE REVIEW

**Comment by wenningerk** [comment]
looking as if the patch has some inconsistent indentation.

**Comment by wenningerk** [comment]
Failure seems to be a CI internal thing - should be Ok once the CI rebuild is done.

**Comment by kgaillot** [comment]
> looking as if the patch has some inconsistent indentation.

Where are you seeing that? The existing code is shifted right and nested inside a new if.

**Review by kgaillot — APPROVED** [review]

**Comment by wenningerk** [comment]
> > looking as if the patch has some inconsistent indentation.
> 
> Where are you seeing that? The existing code is shifted right and nested inside a new if.

I may be misinterpretating the highlighting. Haven't actually pulled the files to have a closer look. Just thought it would do that if there are mixed tabs & spaces.

**Pull request merged**
