### PR TITLE
low: Allow to set base score for node health

### PR DESCRIPTION
**Pull request by bubble75**
This allows to start clone/slave instances even if node has some "yellow" health attributes and strategy is set to progressive. Also, if all nodes has some "yellow" attributes, this prevents stop of all resources - node with the highest score of (base - sum(yellow)) will be chosen.

### CODE REVIEW

**Comment by kgaillot** [comment]
Does this have a compelling advantage over setting a permanent node attribute '#health-base' on all nodes?

**Comment by bubble75** [comment]
Technically that is the same. But proposed one controls that setting for all cluster nodes at once, and it is it the same place as all other health-related settings. Although, using #-attributes in CIB configuration is probably not what they are initially meant for.

**Comment by kgaillot** [comment]
I guess one advantage is that new nodes will automatically get the adjustment when they join, rather than need to have an attribute set after they are already up.

I'd recommend one minor efficiency tweak: let's parse node-health-base only when progressive, and then we can unconditionally initialize the node health to the base in the loop, because it will be 0 for anything other than progressive.

**Comment by bubble75** [comment]
ok. Should that be rebased against 1.1?

**Comment by kgaillot** [comment]
Master is appropriate for new features, only fixes are going into 1.1 right now

**Comment by bubble75** [comment]
Commit is updated to reflect comments.

**Pull request merged**
