### PR TITLE
Don't ack same controller request twice (CLBZ#5420)

### PR DESCRIPTION
**Pull request by kgaillot**

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi @HideoYamauchi ,

I believe this fixes the problem. Can you test it with your cluster?

Thanks!

**Comment by HideoYamauchi** [comment]
Hi Ken,

>I believe this fixes the problem. Can you test it with your cluster?
Yes.

I will report the test results later.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Great!

I've confirmed that the problem can be improved with your fix.

Many thanks,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

Thanks for testing!

**Pull request merged**
