### PR TITLE
Review follow-up

### PR DESCRIPTION
**Pull request by kgaillot**
This is a follow-up to #2729 per that review

### CODE REVIEW

**Comment by kgaillot** [comment]
@clumens , here's the follow-up to the refactoring PR

**Comment by mnikhil-git** [comment]
Unsubscribe

**Comment by clumens** [comment]
Looks like lib/common/tests/procfs/pcmk__procfs_has_pids_false and lib/common/tests/procfs/pcmk__procfs_has_pids_true got added by mistake.

**Comment by kgaillot** [comment]
Whoops! Forgot to add "_test" at the end ...

**Comment by kgaillot** [comment]
updated commit

**Comment by clumens** [comment]
This all looks good to me.

**Comment by kgaillot** [comment]
retest this please

**Pull request merged**
