### PR TITLE
Allow consideration of nodes with finite negative scores

### PR DESCRIPTION
**Pull request by kgaillot**
Previously, the scheduler refused to assign resources to nodes with finite negative scores, or consider colocation dependent preferences if they resulted in nodes with finite negative scores. However, finite scores should be a preference, not mandatory.

### CODE REVIEW

**Comment by kgaillot** [comment]
@nrwahl2 , can you review this fix? I am nowhere near 100% confident in it, due to the complexity of how `pcmk__node_available()` is used, but it seems to make sense.

**Comment by nrwahl2** [comment]
I always assumed this was (odd) intended behavior: if the score ends up being negative when all is said and done, exclude the node; if a constraint specifies negative INFINITY, basically short-circuit and exclude the node no matter what.

That's basically what the Pacemaker Explained doc says:
> Scores are calculated per resource and node. Any node with a negative score for a resource can’t run that resource. The cluster places a resource on the node with the highest score for it.

It sounds like with this fix, there's no longer a meaningful difference between a finite negative score and a finite positive score. They're all just numbers on a number line -- with more positive numbers imparting a stronger preference, more negative numbers imparting a weaker preference, and zero being the default.

**Comment by nrwahl2** [comment]
The existing documented behavior (infinite negative -> automatic "do not assign", finite negative -> "do not assign if the **final** score is negative, if I understand it correctly) might be useful and we may also have users relying on it. Thoughts?

**Comment by kgaillot** [comment]
> The existing documented behavior (infinite negative -> automatic "do not assign", finite negative -> "do not assign if the **final** score is negative," if I understand it correctly) might be useful and we may also have users relying on it. Thoughts?

For the most part, I think not ... if someone uses a finite negative score in a location constraint or colocation constraint, those are already documented as being preferences instead of requirements, and are expected as such.

OTOH there's node health scores. Those are usually specified as red/yellow/green but users can specify specific values, and node-health-base exists specifically to allow node with some finite negative health values to be used.

I don't there's any other way for users to affect node scores numerically.

I think the behavior here makes more sense. If a node has a finite negative score due to constraints or health, but there's no better node, I would expect resources to be able to run there as a last resort. But that does break longstanding (and documented) practice.

Constraints get around the issue by "rolling back" the scores if all nodes would be negative. A less intrusive approach would be to apply the migration threshold ban before applying the anti-colocation, which should automatically roll back in that case. I'll look into whether that's feasible.

**Comment by nrwahl2** [comment]
> if someone uses a finite negative score in a location constraint or colocation constraint, those are already documented as being preferences instead of requirements, and are expected as such.

The individual constraint is a negative preference that subtracts from the total score. Then if the total score is negative, it becomes a requirement. It all seems consistent, although I 100% grant that it's not all intuitive and some of the details are undocumented (for example, assuming two constraints, "-1000 + 500 == can't run" but "-500 + 1000 == can run").

> I think the behavior here makes more sense. If a node has a finite negative score due to constraints or health, but there's no better node, I would expect resources to be able to run there as a last resort. But that does break longstanding (and documented) practice.

I have no preference here in principle (ignoring the history/current practice). My only note is that as mentioned, finite negative is no different from finite positive, and only the raw differences matter -- "-2000 vs. -500", "-1000 vs. 500", and "500 vs. 2000" are all basically the same when it comes to the final scores. You seem to be okay with that and perhaps prefer it, so it works for me.

**Comment by kgaillot** [comment]
> > if someone uses a finite negative score in a location constraint or colocation constraint, those are already documented as being preferences instead of requirements, and are expected as such.
> 
> The individual constraint is a negative preference that subtracts from the total score. Then if the total score is negative, it becomes a requirement. It all seems consistent, although I 100% grant that it's not all intuitive and some of the details are undocumented (for example, assuming two constraints, "-1000 + 500 == can't run" but "-500 + 1000 == can run").

You're correct for location constraints, but if an anti-colocation would make no nodes available, it's just ignored. I just confirmed that "-1000 location preference + 500 location preference = can't run" but "-1000 anti-colocation + 500 location preference = can run". Just in case any user thinks they understand Pacemaker.

> > I think the behavior here makes more sense. If a node has a finite negative score due to constraints or health, but there's no better node, I would expect resources to be able to run there as a last resort. But that does break longstanding (and documented) practice.
> 
> I have no preference here in principle (ignoring the history/current practice). My only note is that as mentioned, finite negative becomes no different from finite positive, and only the raw differences matter -- "-2000 vs. -500", "-1000 vs. 500", and "500 vs. 2000" are all basically the same when it comes to the final scores. You seem to be okay with that and perhaps prefer it, so it works for me. Again, if we break from existing practice.

I like the consistency of it. Finite = preference, infinite = requirement. But such a significant change in behavior should probably be done at a series bump.

> (me:) Constraints get around the issue by "rolling back" the scores if all nodes would be negative. A less intrusive approach would be to apply the migration threshold ban before applying the anti-colocation, which should automatically roll back in that case. I'll look into whether that's feasible.

Migration threshold is already checked before colocation. Unfortunately when it's the dependent resource that reaches its threshold, the effect is only in its own allowed nodes table at that stage. When the primary considers the dependent's preferences, the colocation score has already been applied to the primary's allowed nodes. Maybe I can look into rolling back not just the dependent's preferences, but the original anti-colocation.

**Pull request closed without merging**
