### PR TITLE
Fixes: libstonithd: handling parameters of RHCS-style fence-agents

### PR DESCRIPTION
**Pull request by gao-yan**
-  Add `plug` parameter besides `port` for RHCS-style fence-agents

According to:
https://github.com/ClusterLabs/fence-agents/commit/de490e059

, `port` parameter is massively deprecated in favor of `plug`:
```
<parameter name="plug" ... obsoletes="port">...
<parameter name="port" ... deprecated="1">...
```

The relatively new agent:

https://github.com/ClusterLabs/fence-agents/blob/master/agents/gce/fence_gce.py

doesn't even correctly handle `port`.

With the commit, `plug` parameter is added besides `port` with the same value.

- The `action` and `plug` parameters of RHCS-style fence-agents are shown as non-required in the metadata

The parameter `action` of RHCS-style fence-agents shouldn't usually be
specified in fencing resource configuration, although it'd be properly
remapped anyways with 9c0c3d6.

With the commits, the `action` and `plug`  parameters  of RHCS-style fence-agents are
fudged to be shown as `required="0"` in the metadata output by
`stonith_admin --metadata` or `crm_resource --show-metadata`. So that
users know they don't have to configure them. Pacemaker handles and passes
the parameters to the agent when executing it.

### CODE REVIEW

**Comment by kgaillot** [comment]
This would be good to get into 2.0.4. We've already pulled master for rc1 ( #2034 ), so I'll wait until rc1 is out, and then this can be resubmitted against the 2.0 branch.

**Comment by kgaillot** [comment]
We're going to do one more pull from master for rc1

**Comment by wenningerk** [comment]
Unfortunately we had to take back unconditional addition of `plug` for 2.0.4-rc1 because it turned out that there is at least one fence-agent out there that doesn't like it. (known for now `fence_xvm`)
Can imagine to additionally check meta-data for presence of `plug` and just add it then.

**Comment by kgaillot** [comment]
> Alright. I kind of went through the ones from fence-agents but didn't check this separate one. OTOH `fence_xvm` and any others should probably also recognize `plug` option anyway if it's the new standard?

Definitely, but we still need to stay backward compatible with any agents already out there. Unfortunately fence_xvm immediately returns an error for invalid parameter, so it prevents fencing from working.

See the st_device_supports_ stuff in fenced_commands.c. I'm hoping it will be sufficient to handle it in stonith_device_execute() before calling stonith_action_create(). The only problem I see is the stonith_action_create() call stonith__rhcs_validate(); I'm not sure how to get around that, other than requiring the user to pass pcmk_host_argument if plug is required.

**Comment by gao-yan** [comment]
> See the st_device_supports_ stuff in fenced_commands.c. I'm hoping it will be sufficient to handle it in stonith_device_execute() before calling stonith_action_create(). The only problem I see is the stonith_action_create() call stonith__rhcs_validate(); I'm not sure how to get around that, other than requiring the user to pass pcmk_host_argument if plug is required.

It'd probably make sense for stonith__rhcs_validate() to retrieve and check the metadata?

**Pull request merged**
