### PR TITLE
Mid: controld: Adding default value for node-pending-timeout.

### PR DESCRIPTION
**Pull request by HideoYamauchi**

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi @HideoYamauchi , we now have a regression test for daemon metadata output. Could you add a commit after running cts/cts-cli --update? Thanks!

**Comment by kgaillot** [comment]
@HideoYamauchi ,

Actually, since you are touching this code, would you mind adding another commit to change the default to 0? I want to do that for 2.1.7-rc2 since it is possible that people are still using ping nodes. It will need to be changed in `doc/sphinx/Pacemaker_Explained/options.rst` too.

**Comment by HideoYamauchi** [comment]
> Hi @HideoYamauchi , we now have a regression test for daemon metadata output. Could you add a commit after running cts/cts-cli --update? Thanks!

Hi Ken,

It seems that cts/cts-cli --update cannot be used.
Is something wrong?

```
[root@rh88-dev01 pacemaker]# git branch
  main
* node-pending-2.1
[root@rh88-dev01 pacemaker]# cts/cts-cli --update
error: unknown option --update

Usage: cts-cli [<options>]
Options:
 --help          Display this text, then exit
 -V, --verbose   Display any differences from expected output
 -t 'TEST [...]' Run only specified tests
                 (default: 'daemons dates error_codes tools crm_mon acls
                            validity upgrade rules feature_set').
                 Other tests: agents (must be run in an installed environment).
 -p DIR          Look for executables in DIR (may be specified multiple times)
 -v, --valgrind  Run all commands under valgrind
 -s              Save actual output as expected output
```

**Comment by HideoYamauchi** [comment]
> @HideoYamauchi ,
> 
> Actually, since you are touching this code, would you mind adding another commit to change the default to 0? I want to do that for 2.1.7-rc2 since it is possible that people are still using ping nodes. It will need to be changed in `doc/sphinx/Pacemaker_Explained/options.rst` too.

Hi Ken,

Okay.
After this PR is included, we will issue a another PR to set the default of node-pending-timeout to 0.
In that PR, also change the node-pending-timeout in lib/pengine/common.c that pengine has to 0.

Many thanks,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
> > Hi @HideoYamauchi , we now have a regression test for daemon metadata output. Could you add a commit after running cts/cts-cli --update? Thanks!
> 
> Hi Ken,
> 
> It seems that cts/cts-cli --update cannot be used. Is something wrong?

Oops, sorry, I was thinking of cts-scheduler. For cts-cli, it's `-s`

**Comment by kgaillot** [comment]
> > @HideoYamauchi ,
> > Actually, since you are touching this code, would you mind adding another commit to change the default to 0? I want to do that for 2.1.7-rc2 since it is possible that people are still using ping nodes. It will need to be changed in `doc/sphinx/Pacemaker_Explained/options.rst` too.
> 
> Hi Ken,
> 
> Okay. After this PR is included, we will issue a another PR to set the default of node-pending-timeout to 0. In that PR, also change the node-pending-timeout in lib/pengine/common.c that pengine has to 0.
> 
> Many thanks, Hideo Yamauchi.

Thanks!

**Comment by HideoYamauchi** [comment]
@kgaillot 

What about the following changes?

```
doc/sphinx/Pacemaker_Explained/options.rst 
(snip)
   * - .. _node_pending_timeout:
(snip)
     - 0
     - Fence nodes that do not join the controller process group within this
       much time after joining the cluster, to allow the cluster to continue
       managing resources. A value of 0 means never fence pending nodes. Setting the value to 2h means fence nodes after 2 hours. 
       *(since 2.1.7)*
(snip)
```

And 

```
 lib/pengine/common.c  and daemons/controld/controld_control.c 

(snip)
    {        XML_CONFIG_ATTR_NODE_PENDING_TIMEOUT, NULL, "time", NULL,        "0", pcmk__valid_interval_spec,        N_("How long to wait for a node that has joined the cluster to join "           "the controller process group"),        N_("Fence nodes that do not join the controller process group within "           "this much time after joining the cluster, to allow the cluster "           "to continue managing resources. A value of 0 means never fence " 
           "pending nodes. Setting the value to 2h means fence nodes after "
           "2 hours.")
    },
(snip)
```

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
> @kgaillot
> 
> Hi Ken,
> 
> What about the following changes?
> 
> ```
> doc/sphinx/Pacemaker_Explained/options.rst 
> (snip)
>    * - .. _node_pending_timeout:
> (snip)
>      - 0
>      - Fence nodes that do not join the controller process group within this
>        much time after joining the cluster, to allow the cluster to continue
>        managing resources. A value of 0 means never fence pending nodes. Setting the value to 2h means fence nodes after 2 hours. 
>        *(since 2.1.7)*
> (snip)
> ```
> 
> And
> 
> ```
>  lib/pengine/common.c  and daemons/controld/controld_control.c 
> 
> (snip)
>     {        XML_CONFIG_ATTR_NODE_PENDING_TIMEOUT, NULL, "time", NULL,        "0", pcmk__valid_interval_spec,        N_("How long to wait for a node that has joined the cluster to join "           "the controller process group"),        N_("Fence nodes that do not join the controller process group within "           "this much time after joining the cluster, to allow the cluster "           "to continue managing resources. A value of 0 means never fence " 
>            "pending nodes. Setting the value to 2h means fence nodes after "
>            "2 hours.")
>     },
> (snip)
> ```
> 
> Best Regards, Hideo Yamauchi.

Hi @HideoYamauchi ,

Yes, that looks good. Thanks!

**Review by kgaillot — APPROVED** [review]

**Comment by HideoYamauchi** [comment]
Hi Ken,

All right!
thanks,

Hideo Yamauchi.

**Pull request merged**
