### PR TITLE
fenced: Don't ignore CIB updates if stonith-enabled=false

### PR DESCRIPTION
**Pull request by chrissie-c**
Fixes: T378

### CODE REVIEW

**Comment by wenningerk** [comment]
hmm ... aren't we then doing unnecessary updates of topology and devices?
Let me think over it once more. But atm I guess I like my approach of having a shadow
cib copy we apply the diff to in the background while updating the devices and
switch after devices are updated. Then we need a refresh of devices & topology
in the end probably as well but just once and not triggered with every diff and we
can skip requesting a full cib.

**Comment by kgaillot** [comment]
> hmm ... aren't we then doing unnecessary updates of topology and devices?

The issue that led to this is that manual fencing (stonith_admin) isn't affected by stonith-enabled. So if stonith-enabled=false and we're not processing cib updates, manual fencing can use outdated configs.

> Let me think over it once more. But atm I guess I like my approach of having a shadow cib copy we apply the diff to in the background while updating the devices and switch after devices are updated. Then we need a refresh of devices & topology in the end probably as well but just once and not triggered with every diff and we can skip requesting a full cib.

That would be best but I think this is a step forward

**Comment by wenningerk** [comment]
> > hmm ... aren't we then doing unnecessary updates of topology and devices?
> 
> The issue that led to this is that manual fencing (stonith_admin) isn't affected by stonith-enabled. So if stonith-enabled=false and we're not processing cib updates, manual fencing can use outdated configs.

Nothing against ignoring if stonith-enabled is set or not here.
What I meant was that if we trigger a new full cib-update with each diff coming in during
us updating the devices we are just creating a lot of full updates.
That isn't a new problem and seems to lead to very slow startup of fenced under certain
conditions. Up to fenced being in something like a live-lock.
> 
> > Let me think over it once more. But atm I guess I like my approach of having a shadow cib copy we apply the diff to in the background while updating the devices and switch after devices are updated. Then we need a refresh of devices & topology in the end probably as well but just once and not triggered with every diff and we can skip requesting a full cib.
> 
> That would be best but I think this is a step forward

Thought that if we are touching the logic her (again ;-) ) triggering a lot of thinking and
testing we might just try to make it look clean up to everything we are aware of atm.
And just tossing diffs with some subsequent non-matching diff then triggering
a full update doesn't really feel clean. What does actually happen if we are unhappy
and that diff doesn't come for a longer time after we've finished the device-setup?

If we are updating the devices if stonith-enabled isn't set we should probably as well
update stonith_watchdog_timeout_ms. That on the other hand might give us
watchdog-device while while stonith-enabled isn't set. Presence of other fencing
devices I guess doesn't do any harm. Need to check if that is true for the
watchdog-device as well.

**Comment by kgaillot** [comment]
> > > hmm ... aren't we then doing unnecessary updates of topology and devices?
> > 
> > 
> > The issue that led to this is that manual fencing (stonith_admin) isn't affected by stonith-enabled. So if stonith-enabled=false and we're not processing cib updates, manual fencing can use outdated configs.
> 
> Nothing against ignoring if stonith-enabled is set or not here. What I meant was that if we trigger a new full cib-update with each diff coming in during us updating the devices we are just creating a lot of full updates. That isn't a new problem and seems to lead to very slow startup of fenced under certain conditions. Up to fenced being in something like a live-lock.
>
> > > Let me think over it once more. But atm I guess I like my approach of having a shadow cib copy we apply the diff to in the background while updating the devices and switch after devices are updated. Then we need a refresh of devices & topology in the end probably as well but just once and not triggered with every diff and we can skip requesting a full cib.
> > 
> > 
> > That would be best but I think this is a step forward
> 
> Thought that if we are touching the logic her (again ;-) ) triggering a lot of thinking and testing we might just try to make it look clean up to everything we are aware of atm. And just tossing diffs with some subsequent non-matching diff then triggering a full update doesn't really feel clean. What does actually happen if we are unhappy and that diff doesn't come for a longer time after we've finished the device-setup?

I'll add a task for a bigger overhaul. This PR should be fine though since it only makes a difference when stonith-enabled=false, which should only be during maintenance windows or what not. (And users who leave it disabled will be no worse off than users who leave it enabled.)

> If we are updating the devices if stonith-enabled isn't set we should probably as well update stonith_watchdog_timeout_ms. That on the other hand might give us watchdog-device while while stonith-enabled isn't set. Presence of other fencing devices I guess doesn't do any harm. Need to check if that is true for the watchdog-device as well.

Hmm, yeah I would think we wouldn't want to mess with the SBD settings if fencing is disabled, since the fencer doesn't actually execute it (fence_sbd excluded, which should work fine with the CIB configuration).

**Comment by kgaillot** [comment]
@wenningerk , looking at the code again, we already keep a local CIB copy and apply diffs to it -- the full CIB is requested only if it's the first time or a diff fails to apply. We do need to fix it so it's atomic, i.e. ensuring device queries still work while updates are being processed, so maybe that's what you were talking about?

update_stonith_watchdog_timeout_ms() was already called even if stonith-enabled is false, so I guess that's not a problem. What wasn't done before was updating the list of watchdog targets and registering the internal device if necessary, which is more questionable, but I would think we would at least want to keep the target list up to date even when stonith-enabled=false.

**Comment by wenningerk** [comment]
> @wenningerk , looking at the code again, we already keep a local CIB copy and apply diffs to it -- the full CIB is requested only if it's the first time or a diff fails to apply. We do need to fix it so it's atomic, i.e. ensuring device queries still work while updates are being processed, so maybe that's what you were talking about?
> 
> update_stonith_watchdog_timeout_ms() was already called even if stonith-enabled is false, so I guess that's not a problem. What wasn't done before was updating the list of watchdog targets and registering the internal device if necessary, which is more questionable, but I would think we would at least want to keep the target list up to date even when stonith-enabled=false.

Of course we have a local copy. But if you toss a single diff the local copy is doomed and the next diff coming in will fail and trigger getting a full cib. At least that is how I see it atm but I might have some false memory and should look at it once again.

update_stonith_watchdog_timeout_ms is called but it doesn't update anything while stonith-enabled is false - right?
What I'm a bit scared of is that we are just not updating stonith_watchdog_timeout_ms not disabling it while sotnith-enabled is false. That behavior is a bit unexpected for the user I guess. Up to now it was a bit more consistent as we didn't update the whole fencing-setup - incl. watchdog-devices.
If we are afraid of an active watchdog-device we should probably rather disable stonith_watchdog_timeout_ms if stonith-enabled is false instead of leaving it at the old value.
With stonith_watchdog_timeout_ms disabled potentially configure watchdog-devices (the visible version used for limiting watchdog-fencing to certain nodes) are handles as if they were disabled and the implicit device is removed.

**Comment by kgaillot** [comment]
> Of course we have a local copy. But if you toss a single diff the local copy is doomed and the next diff coming in will fail and trigger getting a full cib. At least that is how I see it atm but I might have some false memory and should look at it once again.
>

I don't think we toss updates but I could be overlooking something.

> What I had been playing with was that while we would rather not touch our cib-copy (while we are updating the devices) I would create a copy of the local cib if a diff is coming in and apply the diff to that. When it is fine again to alter the primary local copy and a 2nd copy would be around (just there if there were diffs coming in in between) we would switch and update on that new one. But yes that is making it atomic with some lock-free-RCU-like approach.

That sounds good. I think we also need a second copy of the devices/topologies themselves, so we can serve queries from that while building new lists from a fresh CIB update (or, delay answering queries if an update is being parsed).

> 
> update_stonith_watchdog_timeout_ms is called but it doesn't update anything while stonith-enabled is false - right?

Whoops, speaking of overlooking things :)

I assumed it was unconditional because the CIB callback also checks stonith-enabled before calling it.

> What I'm a bit scared of is that we are just not updating stonith_watchdog_timeout_ms not disabling it while sotnith-enabled is false. That behavior is a bit unexpected for the user I guess. Up to now it was a bit more consistent as we didn't update the whole fencing-setup - incl. watchdog-devices. If we are afraid of an active watchdog-device we should probably rather disable stonith_watchdog_timeout_ms if stonith-enabled is false instead of leaving it at the old value. With stonith_watchdog_timeout_ms disabled potentially configure watchdog-devices (the visible version used for limiting watchdog-fencing to certain nodes) are handles as if they were disabled and the implicit device is removed.

Hmm, maybe we should track everything regardless of stonith-enabled. If stonith-enabled is false, the scheduler won't schedule fencing, so it should only matter for manual fencing.

That makes me wonder, how does manual fencing utilize the watchdog currently (e.g. stonith_admin --reboot for a host on the watchdog targets list with no other fencing configured)? If it just waits, that's a problem; if it fails, that's better, and I guess there's nothing more we could do without shared disk.

**Comment by wenningerk** [comment]
> I don't think we toss updates but I could be overlooking something.

Good question if our code currently ever gets there but till we don't have the initial device-list we just exit before integrating the diff if I'm getting that right.
Prior to this fix here I think we did as well if stonith-enabled was false.

> That makes me wonder, how does manual fencing utilize the watchdog currently

Remember having played with it and it did something that seemed to make sense.
Don't remember the details - will try again.

With the approach of leaving the list, flag everything for deletion and just actually
delete devices that are still flagged as a last step queries during updates might
not be that critical. Worst thing might be a superset from before and after update.
Unless of course there is a chance it catches the list with inconsistent linking.

**Comment by kgaillot** [comment]
> > I don't think we toss updates but I could be overlooking something.
> 
> Good question if our code currently ever gets there but till we don't have the initial device-list we just exit before integrating the diff if I'm getting that right. Prior to this fix here I think we did as well if stonith-enabled was false.

That's only for the very first CIB query after connecting. Any diffs that arrive between when we initially connect+query the CIB and get the result will be discarded because we don't have anything to apply them to. Whether that causes problems would depend on whether the eventual result already includes those diffs.

Full CIB requests after the first are sync, so there should be no issue there.

That's an interesting problem for pacemaker-based, ensuring that a client who queries the full CIB gets a result that definitely includes all diffs that have already been notified. I'm not sure whether that's the case currently.

**Comment by kgaillot** [comment]
@wenningerk , is it reasonable to say that for this PR, it should be sufficient to additionally take out the stonith-enabled check in update_stonith_watchdog_timeout_ms(), and everything else can be saved for later?

**Comment by wenningerk** [comment]
> @wenningerk , is it reasonable to say that for this PR, it should be sufficient to additionally take out the stonith-enabled check in update_stonith_watchdog_timeout_ms(), and everything else can be saved for later?

Guess that should be fine as everything else we discussed in here seems to be quite orthogonal to the changes.

**Comment by kgaillot** [comment]
@chrissie-c , see previous comment, this just needs one small change

**Pull request merged**
