### PR TITLE
Build changes for 2.1.0

### PR DESCRIPTION
**Pull request by kgaillot**
This is the last big set of build-related changes for the 2.1.0 release.

Most significantly, there is a new configure option --with-resource-stickiness-default that tells Pacemaker to add a rsc_defaults section to empty CIBs with a resource-stickiness default. This is because new users often expect sticky behavior by default, and are surprised when resources move around a lot. We want to stay backward-compatible, so no stickiness is still the "default default", but distros/builders can set a default stickiness if they want.

It's a configure option rather than leaving it to higher-level tools, so it can take effect regardless of how a cluster is created or started, and because higher-level tools can't set resource defaults at cluster creation time (since the cluster may not be started immediately).

We set an explicit rsc_defaults entry in new CIBs rather than change the implicit default, so that existing clusters are unaffected, rolling upgrades aren't a nightmare, users have a way of querying the resource default, scheduler regression tests aren't affected, and users can remove it if they want the implicit default behavior.

### CODE REVIEW

**Comment by kgaillot** [comment]
@clumens , can you review this when you get a chance? Thanks.

@wenningerk @yan-gao @HideoYamauchi , you might be interested in the new resource-stickiness option. Let me know if you think it's a bad idea.

**Comment by wenningerk** [comment]
> @wenningerk @yan-gao @HideoYamauchi , you might be interested in the new resource-stickiness option. Let me know if you think it's a bad idea.

Sounds like a good approach to me - unless there are scenarios I'm not aware of of course ...

**Comment by clumens** [comment]
This all looks good to me.  The build process and code cleanliness is really coming along.  It's nice to see.

**Comment by HideoYamauchi** [comment]
> @clumens , can you review this when you get a chance? Thanks.
> 
> @wenningerk @yan-gao @HideoYamauchi , you might be interested in the new resource-stickiness option. Let me know if you think it's a bad idea.

I have no particular objection.

**Pull request merged**
