### PR TITLE
fix: alert-helpers: some fixes in pcmk_smtp_helper.sh

### PR DESCRIPTION
**Pull request by wenningerk**

### CODE REVIEW

**Comment by wenningerk** [comment]
#1044

**Comment by kgaillot** [comment]
The command options and headers are good, but I think we should still use CRM_alert_recipient.

**Comment by wenningerk** [comment]
If you define CRM_alert_recipient it is anyway used.
Using the modified version (if there is no "@") makes testing easy because you don't have to have a fully setup smtp-server-environment. It is enough to be able to deliver to local-root.

**Comment by kgaillot** [comment]
Of course, I missed the first change somehow. Looks good.

**Pull request merged**
