### PR TITLE
DC expands to Designated Controller in most places - make consistent

### PR DESCRIPTION
**Pull request by wenningerk**

### CODE REVIEW

**Comment by kgaillot** [comment]
I hadn't actually noticed doc/crm.txt before. It's a historical document giving the genesis of Pacemaker rather than current documentation, so it's not worth editing. It's probably appropriate to remove it from the repository at this point though.

doc/executioner.txt is also archaic, and we have doc/crm_fencing.txt and fencing/README.md which are more useful, so it could be removed too. doc/security.txt is of questionable benefit but can be left alone for now, because it might be worthwhile to overhaul it one day.

In general, Clusters From Scratch, Pacemaker Explained and Pacemaker Remote are the primary current documentation. The other files are hit and miss as to whether they've been kept up to date.

**Comment by wenningerk** [comment]
Didn't have a deeper look at the files changed just stumbled over the name change working through
Pacemaker Explained. Then I checked if the old name I had in mind was still used anywhere...
And thus I thought this commit would be an easy way to check if my local
pacemaker-git, my pacemaker-git on github and the upstream git on github work together as
expected to be ready and set for something more useful ;-)

**Comment by kgaillot** [comment]
That's a good idea :)

Amend this commit to not modify doc/crm.txt (or remove it), and it'll be good to go.

Not sure how comfortable you are with git, but you can amend the HEAD of the current branch with "git commit --amend". Trying to push it normally to your github origin will complain, but you can force it with "git push origin +HEAD:doc_proposal". Of course that's a good idea only for personal repos that aren't used by anybody else, as it invalidates any other checkouts.

**Comment by wenningerk** [comment]
doc/crm.txt is gone...
We don't want to give the wrong impression that an archaic file was maintained by editing it - fully agreed.
As travis immediately jumped on the change I guess there is no new pull request needed ...

**Comment by kgaillot** [comment]
Correct, if you push to a github branch, any pull requests for it automatically get updated.

Everything looks good. As an aside, looking at the various doc/*.txt files, I think we maybe could benefit from a "Pacemaker Development" document that incorporates most of them (thoroughly updated) as chapters. I might start that at some point and incorporate the few parts of the late crm.txt that are still relevant.

**Pull request merged**
