### PR TITLE
Add pacemaker(pacemaker-based) resource translatefile

### PR DESCRIPTION
**Pull request by daaitudian**
Hi,

This revision is about the promoting the internationalization of the Pacemaker , it can show the descriptions of different languages for system language, and currently provide support for some Chinese.

Looking forward to your reply!

### CODE REVIEW

**Comment by daaitudian** [comment]
OK to test

**Comment by wenningerk** [comment]
test this please

**Comment by kgaillot** [comment]
Thanks!

CI caught an issue I overlooked: gettext.h needs to be listed in noinst_HEADERS in include/Makefile.am in order for "make dist" and "make distcheck" to work.

**Comment by kgaillot** [comment]
P.S. you can squash all the commits with "git rebase -i e309d31~1", then change the first word to "s" for every commit but the first in the editor that pops up. You can then overwrite the commits here with "git push origin +HEAD:master" (assuming "origin" is the label for your personal fork).

**Comment by daaitudian** [comment]
Thanks for your reminder,  I squash all my previous commits based on the latest commit and I have already modified the problem in gettext.h.

**Comment by daaitudian** [comment]
Hi,
@kgaillot , I would like to ask about the new development of this pr.  Is there anything that needs to be changed?

**Comment by kgaillot** [comment]
> Hi, @kgaillot , I would like to ask about the new development of this pr. Is there anything that needs to be changed?

Hi,

No, I emailed the users@clusterlabs.org list earlier this month to start a discussion, but there hasn't been any feedback yet. With so many people taking time off due to the holidays, I figure I will bring it up again at the start of January.

**Comment by daaitudian** [comment]
Thanks ：）

**Comment by daaitudian** [comment]
Thanks：）

**Comment by kgaillot** [comment]
Hi,

Another PR was recently merged that changed options.c, so this will need to be rebased on the current main branch. Also, the master branch was recently renamed to main, so you will need to update your fork and checkout per:

https://wiki.clusterlabs.org/wiki/How_to_rename_git_default_branch

Sadly, it seems that there is not enough interest from the larger community to maintain translations. What I would like to do is merge this, then I'll make some changes so that the translations are disabled by default and marked as experimental, rather than enabled by default. That way, you can enable the feature in custom builds, and other users can play around with the feature. If it gains momentum over time, we could enable it by default again.

**Comment by kgaillot** [comment]
superseded by #2610

**Pull request closed without merging**
