### PR TITLE
Test: cts: simulate failure of pacemaker_remoted by freezing it with SIGSTOP

### PR DESCRIPTION
**Pull request by gao-yan**
Backport for 1.1 branch.

### CODE REVIEW

**Comment by kgaillot** [comment]
Thanks :)

**Comment by kgaillot** [comment]
With pacemaker-remoted stopped, recurring monitors on the remote node won't run, so (in a non-sbd environment) the cluster has to rely on the remote RA monitor itself. CTS configures a 60-second monitor interval and 90-second timeout (via op_defaults). That means it will be 90 - 150 seconds before the failure will be detected, but CTS's fail_connection() is currently using a 120-second timeout, so it doesn't always detect it in time.

I'm going to drop the monitor interval to 20s and add an explicit timeout of 45s, but this does highlight something I find interesting -- someone may configure a low monitor interval on a resource running behind a remote, but they might not realize the remote monitor's settings will be what matters in this failure scenario. Thinking offhand, I wonder if we should dynamically adjust a remote connection's monitor interval, i.e. use the connection's configured monitor interval as an upper bound, but otherwise set it to the minimum monitor interval of whatever's running behind it.

Also, CTS is now showing "BadNews" for the monitors of the resources running on the frozen remote node failing. I can't for the life of me figure out why those monitors weren't failing before -- fail_all_monitor_cmds() has always been called when the connection is lost. I can't see why freezing vs killing would make a difference for that. I need to investigate that more, but I'm inclined to just add these to the ignore_pats for the RemoteStonithd test.

**Comment by gao-yan** [comment]
On 12/10/18 7:54 PM, Ken Gaillot wrote:
> With pacemaker-remoted stopped, recurring monitors on the remote node 
> won't run, so (in a non-sbd environment) the cluster has to rely on the 
> remote RA monitor itself. CTS configures a 60-second monitor interval 
> and 90-second timeout (via op_defaults). That means it will be 90 - 150 
> seconds before the failure will be detected, but CTS's fail_connection() 
> is currently using a 120-second timeout, so it doesn't always detect it 
> in time.
Ah, indeed.

> 
> I'm going to drop the monitor interval to 20s and add an explicit 
> timeout of 45s, but this does highlight something I find interesting -- 
> someone may configure a low monitor interval on a resource running 
> behind a remote, but they might not realize the remote monitor's 
> settings will be what matters in this failure scenario. Thinking 
> offhand, I wonder if we should dynamically adjust a remote connection's 
> monitor interval, i.e. use the connection's configured monitor interval 
> as an upper bound, but otherwise set it to the minimum monitor interval 
> of whatever's running behind it.
I'm not sure we should take the resources running on the remote node 
into account.

Similarly to a cluster node, the configured token + consensus timeouts 
in corosync determines how soon we should confirm a loss of a node. 
Until then and the node gets fenced,  the resources running on the node 
remain "Unclean" no matter how often they are supposed to be monitored, 
right?

> 
> Also, CTS is now showing "BadNews" for the monitors of the resources 
> running on the frozen remote node failing. 
Hmm, for some reason, I've never seen this.

> I can't for the life of me 
> figure out why those monitors weren't failing before -- 
> fail_all_monitor_cmds() has always been called when the connection is 
> lost. I can't see why freezing vs killing would make a difference for 
> that. 
Probably because previously TCP connection got dropped immediately but 
now it preserves for a while?

**Comment by kgaillot** [comment]
> I'm not sure we should take the resources running on the remote node into account. Similarly to a cluster node, the configured token + consensus timeouts in corosync determine how soon we should confirm a loss of a node. Until then and the node gets fenced, the resources running on the node remain "Unclean" no matter how often they are supposed to be monitored, right?

Yes, but corosync timeouts are typically in single-digit seconds, whereas recurring monitor intervals are usually in the tens of seconds. If someone configures a 10s interval on some resource and a 60s interval on the connection resource, they probably don't know about this issue. I suppose we could log a warning instead, when the monitor is initially scheduled.

> Also, CTS is now showing "BadNews" for the monitors of the resources running on the frozen remote node failing.
> Hmm, for some reason, I've never seen this.
> I can't for the life of me figure out why those monitors weren't failing before -- fail_all_monitor_cmds() has always been called when the connection is lost. I can't see why freezing vs killing would make a difference for that.
> Probably because previously TCP connection got dropped immediately but now it preserves for a while?

I figured it out, connection poke timeout and connection drop exercise two different code paths:

https://github.com/ClusterLabs/pacemaker/pull/1642/commits/161684ee4acaac791a99fe8d5db8d0e814e20aab

**Pull request merged**
