### PR TITLE
Log: Fix the problem that environment variable is not set when using default value of log file

### PR DESCRIPTION
**Pull request by yuusuke**
Hi!
I tried to make a fix for the problem I raised below.
https://lists.clusterlabs.org/pipermail/users/2019-May/02252.3.html

### CODE REVIEW

**Comment by jnpkrn** [comment]
While Ken was ~4 minutes later (apparent race condition), I think
it behaves more cautiously (will set the environment variable in
less percent of the overall use cases -- still those that are
desirable, I believe):

https://github.com/ClusterLabs/pacemaker/pull/1793/commits

**Comment by kgaillot** [comment]
Yep, since this was a regression in 2.0.0, and the change is small, I decided to go ahead and do it for 2.0.2-rc3 (which will go out today if testing is good).

The only real difference with my patch is that (similar to what pacemaker 1 did) the environment variable is set only if crm_add_logfile() returns TRUE (indicating successfully opening the log).

**Comment by yuusuke** [comment]
Hi, Ken
I have confirmed the correction you made!
It works as expected.
Thank you for fixing it just before release!

**Comment by kgaillot** [comment]
Hi @yuusuke , thanks for the confirmation!

**Pull request closed without merging**
