### PR TITLE
mainly Fix CLBZ#5253: stonithd: Do not intermingle stdout & stderr coming from ...

### PR DESCRIPTION
**Pull request by wenningerk**

### CODE REVIEW

**Comment by wenningerk** [comment]
as somebody just having a look at the cib wouldn't see the textual description of the parameter
I would suggest to use a name that already points out that dynamic is not to be seen as really
dynamic here like e.g. dynamic_host_list_testing. Just not so nice and short as the other 
parameters anymore ;-)

**Comment by kgaillot** [comment]
On 11/25/2015 11:51 AM, wenningerk wrote:
> as somebody just having a look at the cib wouldn't see the textual description of the parameter
> I would suggest to use a name that already points out that dynamic is not to be seen as really
> dynamic here like e.g. dynamic_host_list_testing. Just not so nice and short as the other 
> parameters anymore ;-)

Sure :) dynamic_list_output? mock_dynamic_hosts?

**Comment by wenningerk** [comment]
If we just want to have contiguous logging for both stderr and stdout directly followed by each other (stderr could be warning and stdout could be trace) we can have that - though not a very nice implementation - in read_output as well as it is anyway just called once when the child terminates to read out what is buffered in the pipes. So we wouldn't have to expand any interfaces to pass around a 2nd buffer. 
Btw. there was no contiguous printout of the intermingled stuff till now - just in the case there were troubles parsing - otherwise just the chunky trace.
Probably it would as well make sense to parse both outputs for lineends and log the lines separately not to compromise any size limits of the logging facitlity instead of the previous "%.200s..." limitation which might loose interesting data.

**Comment by kgaillot** [comment]
Line-by-line logging would be ideal, especially for the stderr output. There might be code elsewhere in pacemaker that does something similar already. I'm not too worried about stdout since the user never needs to see it.

**Comment by beekhof** [comment]
logging in the lib is fine. just dont do it inside read_ouput()

**Comment by beekhof** [comment]
oh, and there is a crm_log_output() for logging the string returned from stderr/out

**Comment by wenningerk** [comment]
yep, sorry meant for metadata (output = NULL). What about removing the trace output from read_output and having that as trace here for metadata in a contiguous manner (maybe line separated and with a prefix)? Then we don't have it duplicated in trace for the other cases
where it anyway is logged as NOTICE/ERR. For sync case we should have the logging
somewhere as well probably. Probably would be nicer to have the stderr log here as well but
without interface-change can't easily pass it up here. Anyway in the lib should be OK as well. 
Was going for read_output as this is common for sync & async case but of course we can do it higher and wrap it in a function to be called in both cases.

**Comment by wenningerk** [comment]
Amended the "Fix CLBZ#5253" commit a little.
Reverted read_output to original state. One just doesn't enable trace-logging there if not liked.
Also didn't change that operation-logging doesn't log metadata.
Instead lib is line by line logging the contiguous stdout (LOG_TRACE) & stderr (LOG_WARNING) in log_action (for having better control of trace-logging one might think of a better name).
Renamed the new parameter in fence_dummy.

**Comment by kgaillot** [comment]
Excellent, looks great. I would recommend two small changes: use -H instead of -N for --mock_dynamic_hosts shortcut (a bit more memorable), and drop the crm_trace() in read_output(), since log_action() handles it better (I think @beekhof will agree).

**Comment by wenningerk** [comment]
both done!
"-N" was for Names ;-)

**Comment by kgaillot** [comment]
Great, done. Since the code changed since the last testing, please re-run your tests, and comment with results.

**Comment by wenningerk** [comment]
CTS is still passed:

Dec 04 09:29:53 node1 ****************
Dec 04 09:29:53 node1 Overall Results:{'failure': 0, 'skipped': 0, 'success': 50, 'BadNews': 4}
Dec 04 09:29:53 node1 ****************
Dec 04 09:29:53 node1 Test Summary
Dec 04 09:29:53 node1 Test Flip:                {'auditfail': 0, 'failure': 0, 'skipped': 0, 'calls': 2}
Dec 04 09:29:53 node1 Test Restart:             {'auditfail': 0, 'failure': 0, 'skipped': 0, 'calls': 3}
Dec 04 09:29:53 node1 Test Stonithd:            {'auditfail': 0, 'failure': 0, 'skipped': 0, 'calls': 3}
Dec 04 09:29:53 node1 Test StartOnebyOne:       {'auditfail': 0, 'failure': 0, 'skipped': 0, 'calls': 3}
Dec 04 09:29:53 node1 Test SimulStart:          {'auditfail': 0, 'failure': 0, 'skipped': 0, 'calls': 0}
Dec 04 09:29:53 node1 Test SimulStop:           {'auditfail': 0, 'failure': 0, 'skipped': 0, 'calls': 2}
Dec 04 09:29:53 node1 Test StopOnebyOne:        {'auditfail': 0, 'failure': 0, 'skipped': 0, 'calls': 6}
Dec 04 09:29:53 node1 Test RestartOnebyOne:     {'auditfail': 0, 'failure': 0, 'skipped': 0, 'calls': 3}
Dec 04 09:29:53 node1 Test PartialStart:        {'auditfail': 0, 'failure': 0, 'skipped': 0, 'calls': 3}
Dec 04 09:29:53 node1 Test Standby:             {'auditfail': 0, 'failure': 0, 'skipped': 0, 'calls': 2}
Dec 04 09:29:53 node1 Test MaintenanceMode:     {'auditfail': 0, 'failure': 0, 'skipped': 0, 'calls': 4}
Dec 04 09:29:53 node1 Test ResourceRecover:     {'auditfail': 0, 'failure': 0, 'skipped': 0, 'calls': 3}
Dec 04 09:29:53 node1 Test ComponentFail:       {'auditfail': 0, 'failure': 0, 'skipped': 0, 'calls': 3}
Dec 04 09:29:53 node1 Test Reattach:            {'auditfail': 0, 'failure': 0, 'skipped': 0, 'calls': 1}
Dec 04 09:29:53 node1 Test SpecialTest1:        {'auditfail': 0, 'failure': 0, 'skipped': 0, 'calls': 4}
Dec 04 09:29:53 node1 Test NearQuorumPoint:     {'auditfail': 0, 'failure': 0, 'skipped': 1, 'calls': 8}

**Comment by wenningerk** [comment]
instead of being mixed with stdout stderr is now logged separately and doesn't desturb parsing of stdout data anymore:

Dec 04 09:18:30 [29402] node2 stonith-ng:  warning: log_action: fence_dummy[29416] stderr: [ asked for fence_dummy metadata ]

**Pull request merged**
