### PR TITLE
Minor XML cleanups

### PR DESCRIPTION
**Pull request by nrwahl2**
Commits from #3200 that apply easily to main without compatibility issues

### CODE REVIEW

**Comment by kgaillot** [comment]
retest this please

**Comment by nrwahl2** [comment]
> retest this please

There was a const bug due to something missing that was in the other PR. Should be fixed now.

**Review by kgaillot — APPROVED** [review]
Nice :)

**Comment by nrwahl2** [comment]
retest this please

**Comment by nrwahl2** [comment]
...now what...

**Pull request merged**
