### PR TITLE
Update scheduler recheck time for node-pending-timeout

### PR DESCRIPTION
**Pull request by kgaillot**
See CLBZ#5531 / T724

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi @HideoYamauchi , I haven't had time to test this, but this is what I have in mind. Let me know what you think.

**Comment by HideoYamauchi** [comment]
> Hi @HideoYamauchi , I haven't had time to test this yet, but this is what I have in mind. Let me know what you think.

Hi @kgaillot 

Okay!
I will check the PR and let you know the results.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi @kgaillot 

I checked your PR and confirmed it works.

Your PR will work fine.
The update of pe__update_recheck_time() updates a small value, so even if there are multiple pending nodes at this point, the shortest recheck timer will be activated.

Many thanks,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Thanks, @HideoYamauchi ! I've added a commit on top for the log change.

**Pull request merged**
