### PR TITLE
Test: cts-scheduler: test "year-2038" only runs for 64bit systems

### PR DESCRIPTION
**Pull request by gao-yan**
This probably belongs to 2.0 branch. If everything is fine, feel free to change the target branch of this pull request after  #1914 is merged.

### CODE REVIEW

**Comment by kgaillot** [comment]
Thanks! I thought you were talking about the CLI tests; there's a 2038 test in there, too.

I had to update #1914 anyway, so I cherry-picked this into that one, and I'll pull that back into master.

**Comment by gao-yan** [comment]
Thanks. The CLI tests are alright for 32bit. It doesn't seem that `time_t`/`epoch` is used there.

**Comment by kgaillot** [comment]
> Thanks. The CLI tests are alright for 32bit. It doesn't seem that `time_t`/`epoch` is used there.

Hmm, that's odd. There's a 2038 test that does:

    # iso8601 -d '2038-01-01 00:00:00Z' -D P3M -E '2038-04-01 00:00:00Z'
    Date: 2038-01-01 00:00:00Z
    Duration:  3 months 
    Duration ends at: 2038-04-01 00:00:00Z

and also the "W01" week tests are run for 2040. I'd expect both to fail on 32-bit.

**Comment by gao-yan** [comment]
I think `crm_time_*()` functions do all the magic (conversions/calculations) with `crm_time_t` without relying on `time_t` or any system functions that reply on `time_t`  in here. And `long long` is 8 bytes on 32bit too.

**Comment by kgaillot** [comment]
Ah, nice. :)

**Pull request closed without merging**
