### PR TITLE
Call sync() before calling sysrq_trigger(b) in panic_local()

### PR DESCRIPTION
**Pull request by inouekazu**
If a pacemaker sub-process terminates unexpectedly in an environment where fail_fast=yes is set, no message will be left in pacemaker.log indicating the cause.
(We do not use fail_fast=no because there is a problem [1] that the attributes will remain missing if controld or attrd unexpectedly terminates.)
I am aware of the risk [2], but sbd executed via panic_sbd() calls sync() [3] before sysrq_trigger('b').

[1] https://github.com/ClusterLabs/pacemaker/pull/1699
[2] https://github.com/ClusterLabs/pacemaker/pull/874#issuecomment-171069747
[3] https://github.com/ClusterLabs/sbd/blob/v1.4.2/src/sbd-common.c#L958

### CODE REVIEW

**Comment by wenningerk** [comment]
Well with sbd the sync() is configurable so that the user can choose what is more important - reliable & immediate panic or data persistency.
And on top with sbd it is always highly recommended to use a hardware-watchdog (or at least softdog) that would kick in if sync() doesn't return in time.

**Comment by kgaillot** [comment]
Especially since disk controller issues could be a reason to panic, I wouldn't want to do this unconditionally or by default. But I'm fine with giving the user the option -- maybe PCMK_panic_action could get a new "sync-reboot" option.

**Comment by inouekazu** [comment]
> And on top with sbd it is always highly recommended to use a hardware-watchdog (or at least softdog) that would kick in if sync() doesn't return in time.

Thanks for the info, I'd forgotten about watchdog.

**Comment by kgaillot** [comment]
Thanks!

BTW the powerpc CI host is down which is why CI failed

**Pull request merged**
