### PR TITLE
Mid: extra: Change pcmk_snmp_helper.sh (2).

### PR DESCRIPTION
**Pull request by HideoYamauchi**
Hi All,

I send the script for the SNMP trap
I branch off the transmission in a parameter.

We want to put this script as the script which is available to users immediately.

We want to include this script in Pacemaker1.1.15 with order of traps control.

This patch reconstituted next pullrequest.
 - https://github.com/ClusterLabs/pacemaker/pull/1006
 - https://github.com/ClusterLabs/pacemaker/pull/1009

Best Regards,
Hideo Yamauchi.

### CODE REVIEW

**Comment by kgaillot** [comment]
Hi Hideo,

Thanks, this looks good!

I do have one concern. Since the alert script will be run as root, and the environment variables are supplied via the CIB, this creates a potential security issue if someone has permissions to edit the CIB, but not full root access (for example, via ACLs or puppet modules).

For example, someone could configure trap_version="2c; /usr/bin/touch /gotcha; /bin/echo '

In most cases, it is sufficient to simply put the variable in quotes, for example:

    -v "${trap_version}"

The only one that can't be handled that way is trap_options. I think it would probably be better to just drop that, unless you require it, in which case maybe we should add a comment so people are aware of the issue. For example:

    # This sample script assumes that only users who already have root access can edit the CIB.
    # Otherwise, a malicious user could run commands as root by inserting shell code into the
    # the trap_options variable. If that is not the case in your environment, you should edit this
    # script to remove or validate trap_options.

Klaus, we'll need to mention this risk when we document alerts, and we should update pcmk_alert_sample.sh similarly.

**Comment by HideoYamauchi** [comment]
Hi Ken,

All right!

As a reverse thought. . .

I think that you should invalidate by default trap_options.
When a user uses trap_options, I think that a user should change a script.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,
Hi Klaus,

We want to include queue function of alert in Pacemaker1.1.15.
However, the patch of queue takes time a little more.
It is necessary for us to give a careful test.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,

The pullrequest became different, but sent the patch which I added comment to.
 * https://github.com/ClusterLabs/pacemaker/pull/1023

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,
Hi Klaus,

I confirm some movement of the script now.
In the resource of Master/Slave, I transmit a lot of traps of "notify".

```
May 26 15:40:25 snmp-manager snmptrapd[1279]: 2016-05-26 15:40:25 pgsr01 [UDP: [192.168.100.176]:49294->[192.168.100.189]:162]:
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (674563) 1:52:25.63    SNMPv2-MIB::snmpTrapOID.0 = OID: PACEMAKER-MIB::pacemakerNotificationTrap       PACEMAKER-MIB::pacemakerNotificationNode = STRING: "pgsr01"     PACEMAKER-MIB::pacemakerNotificationResource = STRING: "prmApPostgreSQLDB"      PACEMAKER-MIB::pacemakerNotificationOperation = STRING: "notify"        PACEMAKER-MIB::pacemakerNotificationDescription = STRING: "ok"  PACEMAKER-MIB::pacemakerNotificationStatus = INTEGER: 0 PACEMAKER-MIB::pacemakerNotificationReturnCode = INTEGER: 0     PACEMAKER-MIB::pacemakerNotificationTargetReturnCode = INTEGER: 0
May 26 15:40:25 snmp-manager snmptrapd[1279]: 2016-05-26 15:40:25 pgsr01 [UDP: [192.168.100.176]:48016->[192.168.100.189]:162]:
```

I think that this trap should be able to choose the output.


What do you think?

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hideo, what do you think of this:

Instead of trap_resource=true/false, we could have trap_resource_tasks_default=all, with the option of specifying specific actions to trap instead, for example: trap_resource_tasks="start,stop".

We could even do the same for trap_fencing_tasks.

Let's keep one pull request open for all changes, and close the other.

**Comment by HideoYamauchi** [comment]
Hi Ken,

I agree to the opinion that you showed.
If there is not an opinion elsewhere, I intend to send the last patch.

Next pullrequest is closed once.

Many thanks!
Hideo Yamauchi.

**Comment by wenningerk** [comment]
Guess this is becaus snmptrap wasn't called as root...
You could have a look at https://sourceforge.net/p/net-snmp/bugs/1706/.
Could try setting SNMP_PERSISTENT_DIR to a directory where hacluster...

But maybe we have touched a general point here we should think over:
With ClusterMon the scripts were called as root - inherited from lrmd.
Now - not changed since the built-in notifications-feature - they are called 
with whatever user the daemon is running that issues the alert.

**Comment by HideoYamauchi** [comment]
Hi Klaus,

Thank you for comment.
I try it.

Many thanks!
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,
Hi Klaus,

I classified a correction into my repository.
What do you think?

Best Regards,
Hideo Yamauchi.

**Comment by wenningerk** [comment]
Regarding security considerations:
At the moment alert-scripts are executed as user hacluster.
So if I have access to the cib and want to run something as root I'd rather
setup a resource. So I don't have to fiddle around with writing commands
into variables and my code is executed as root...

**Comment by wenningerk** [comment]
Regarding filtering:

How far are we still away from defining some kind of filter-language where we are now?
Would be able to get rid of the extra handling of failed monitors.
Talking of something like "all !resource-monitor-failed !resource-notify !node-member".
Would then do a longest-match for positive and one for negative.
Trap is done when (longest-match-positive > 0) && (longest-match-positive > longest-match-negative).
That said it would probably be of generic interest to have such a filtering and thus bringing
it into pacemaker might be something to think of. (Arguments: parsing done once when
read from cib; spare creation of a child-process and a shell instance if unmatched; 
globally available for all alert-scripts; ...)

Implementation-wise the current functionality might be implemented without loop and less or 
none (bash-4) external executables.

**Comment by kgaillot** [comment]
Re: security -- good point, I forgot that.

Re: filtering -- I don't think we can or should implement filtering in pacemaker itself in the 1.1.15 timeframe. For now, we should continue to filter in the script (with simple variables, not a complex filter specification). Depending on how people use alerts, we may want to add complex server-side filtering in a future version.

**Comment by kgaillot** [comment]
Re: the log messages about /var/lib/net-snmp/snmpapp.conf -- this is a known issue that has been fixed by the upstream snmp project: https://sourceforge.net/p/net-snmp/code/ci/53ee5f1d240ac90adae935538bdc2ca13a8caa32/

From the description of the fix there, it should be safe to ignore the messages. Unfortunately, if we redirect 2>/dev/null, we might lose real errors. We could set SNMP_PERSISTENT_DIR as mentioned by Klaus as a workaround.

**Comment by HideoYamauchi** [comment]
Hi Ken,
Hi Klaus,

Thank you for merging a patch.

Best Regards,
Hideo Yamauchi.

**Pull request merged**
