### PR TITLE
Initial podman support

### PR DESCRIPTION
**Pull request by mbaldessari**
In the same vein as 202be7dee6db "PE: Bundles: add support for rkt bundle type"
we add support for another container type for bundles: podman.

Tested with the following container:
 podman container set: test_bundle [docker.io/sdelrio/docker-minimal-nginx]
   test_bundle-podman-0 (ocf::heartbeat:podman):        Started nodea
   test_bundle-podman-1 (ocf::heartbeat:podman):        Started nodeb
   test_bundle-podman-2 (ocf::heartbeat:podman):        Started nodec

Tested a couple of stop/start cycles successfully.
I will play with more complex scenarios as all the pieces start coming
together.

### CODE REVIEW

**Comment by jnpkrn** [comment]
Thanks for the effort to support podman.

We do not functionally modify existing schema versions once they
were featured in the stable release (which was the case with
`pacemaker-3.1.rng`).  Please follow:

  https://github.com/ClusterLabs/pacemaker/tree/master/xml#simple-additions

i.e., copy your new `resources-3.1.rng` instance into `resources-3.2.rng`
to be added into the PR and reset+checkout `resources-3.1.rng` so it's not
touched at all.

**Comment by jnpkrn** [comment]
Thanks for pointing that discrepancy out, `tools/regression.sh`
got moved as `cts/cts-cli`, I've added a commit to #1550
(`Doc: xml: reflect move of CLI tools regression runner + changed logic`)
to rectify that.

**Comment by jnpkrn** [comment]
Do we anticipate that `podman` bundle configuration support will grow beyond
what's currently offered for `docker`?  If not (or not imminently) and drop-in
replacement is the goal, I'd be in favour of factoring out the common subgrammar
for both `docker` and `podman` into a separate definition (named e.g.
`element-bundle.common-interface.docker`) and use it as a macro target of
its respective `<ref/>` applications under both elements for such assumed
compatible bundle kinds.

**Comment by kgaillot** [comment]
> Do we anticipate that podman bundle configuration support will grow beyond
> what's currently offered for docker? If not (or not imminently) and drop-in
> replacement is the goal, I'd be in favour of factoring out the common subgrammar
> for both docker and podman into a separate definition (named e.g.
> element-bundle.common-interface.docker) and use it as a macro target of
> its respective <ref/> applications under both elements for such assumed
> compatible bundle kinds (to remove redundancy, ease the maintainance,
> and avoid accidental divergence).

It's unsettled at this point. The podman and docker commands are nearly but not quite equivalent at the current time; in the near future, podman is expected to gain some compatible functionality that is currently missing, so they will become even more equivalent; but in the longer term, they are expected to diverge.

On the HA side, it's likely the RAs will remain equivalent for the foreseeable future, though there are no guarantees for the long term. The pacemaker interface follows the RA.

I'm inclined to leave it as it is, until we see more where things are headed. We don't know whether changes that will affect pacemaker are more likely to bring them closer together or further apart.

**Comment by jnpkrn** [comment]
> I'm inclined to leave it as it is, until we see more where things
> are headed. We don't know whether changes that will affect pacemaker
> are more likely to bring them closer together or further apart.

I am then suggesting that we keep that unified in the common block
of the grammar, so the divergence will be very explicit and easy to
see when/if that happens.

-- 
Nazdar,
Jan (Poki)

**Comment by mbaldessari** [comment]
> I'm inclined to leave it as it is, until we see more where things are headed. We don't know whether 
> changes that will affect pacemaker are more likely to bring them closer together or further apart.

I think that makes sense. It's two different upstreams, things will change over time and in directions we cannot predict now.

**Comment by jnpkrn** [comment]
Problem is that it's then rather non-trivial to grok the differences like that
(step towards "anti-observability"). Even then, the common base can be
shared and only the divergencies (again, which there are none now) can
be tracked individually.  Unjustified redundancy is just an additional burden
to cope with (unless it's a one-liner like is the case in a parallel PR where
a similar argument has been raised _in favour of compaction_ so I don't
follow this opinion inconsistency), nothing more.

**Comment by jnpkrn** [comment]
I mean I can bring such change after this PR, wanted to settle on
where we want to get regarding maintainability.

**Comment by kgaillot** [comment]
Thanks!

**Comment by kgaillot** [comment]
> I mean I can bring such change after this PR, wanted to settle on
> where we want to get regarding maintainability.

Agreed that the code and schema will need a redesign, but there are higher priorities right now, and it will be more effective to deal with it after the dust settles in the container shake-out.

**Pull request merged**
