### PR TITLE
Mid : Control of the transmission order of the SNMP trap.

### PR DESCRIPTION
**Pull request by HideoYamauchi**
The notification is sent in async.

Therefore, it may be transmitted without order being followed.
For example, in the case of a script executing the snmptrap command that crmd set in notification-agent, order is sometimes disturbed.

This patch protects the order of notifications.

When Pacemaker stops, the order of notifications may not be followed.

 * We want to include this correction in release of Pacemaker1.1.14.

Best Regards,
Hideo Yamauchi.

### CODE REVIEW

**Comment by kgaillot** [comment]
FYI, the notifications feature will not make it into 1.1.14. We expect the interface to change significantly, so for now, we are going to keep it in the master branch only.

**Comment by HideoYamauchi** [comment]
Hi Ken,

We discuss that a notice function is not released in 1.1.14.

Will my patch merge it into master?
Or do I remake a patch again after the mechanism of the new notice was done?
In this case of course I understand the structure of the new notice and remake a patch.

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi,

I think we should wait for now. With the US holidays coming up and 1.1.14 about to be released, it probably will be a good idea to wait until we can dedicate more time to thinking through the new notifications design, and how that might affect this.

There has been some discussion of the proposed changes on the developers@clusterlabs.org mailing list (which you are welcome to join); see the "multiple notification scripts" thread at http://clusterlabs.org/pipermail/developers/2015-December/thread.html

**Comment by HideoYamauchi** [comment]
Hi Ken,

I confirm the contents of the discussion from now on.
And I comment on a discussion if there is an opinion.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,

The demand to an SNMP function is very high in Japanese community and user.
In addition, the user demands a new SNMP function because the SNMP function does not work well in Pacemaker1.1.13.
Including a new SNMP function, is it difficult to release Pacemaker1.1.14?

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

Pacemaker 1.1.14 will ship with notifications disabled by default, so we don't have to guarantee backward compatibility when the interface is redesigned.

However, notifications can be enabled when compiling 1.1.14 by defining RHEL7_COMPAT, and they are enabled by default in the master branch, which will include everything that's in 1.1.14. (RHEL7_COMPAT has that name because the feature was already released in RHEL 7; it does not require running RHEL.)

Anyone who enables it should understand that their configuration and notification scripts may need changes when the new interface is finalized.

I am aiming for about 6 months between releases, so the wait should not be as long as in the past.

**Comment by HideoYamauchi** [comment]
Hi Ken,

Thank you for comment.
It seems to cause confusion later in a user to use the SNMP forcibly in Pacemaker1.1.14.
We will argue about these contents again next week.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,

We discussed it today.
We seem to wait for the release of the new SNMP function of Pacemaker1.1.15 without using the incomplete SNMP function of Pacemaker1.1.14.

Best Regards,
Hideo Yamauchi.

**Comment by kgaillot** [comment]
Hi Hideo,

I'm sorry we don't have a better solution at this point. It is obvious the notifications feature will be very popular, so we want to make sure we get the syntax right, before it's so widely used that major changes are difficult.

**Comment by HideoYamauchi** [comment]
Hi Ken,

No problem.
If a better thing is implemented by Pacemaker, we wait for new SNMP.

Many thanks!
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Ken,

I close this pullrequest.

Many thanks!
Hideo Yamauch.

**Comment by wenningerk** [comment]
Hi Hideo,

I had a look at at the queueing-approach in your commit.
This is good for preserving the sequence the notifications are handled in on a per node basis
(notifications from different nodes would of course still be out of order) but it delays the time
between occurrence of a notification and the actual handling in the script - especially in cases
where there are a lot of notifications within a short period of time.

The situation would even get worse with the reworked notify mechanism that now should enable multiple notification-scripts (at least as long as we stick with one queue).

As an alternative we offer 2 environment-variables:
- 1st having in the timestamp when the notification had been triggered
   (defaulting to seconds after the Epoch but configurable by a per notify-script-property
   holding a time-format string as e.g. used with strftime)
- 2nd is a per node sequence number which is strictly counting up
  (with a possible wrap after 32 or 64bit)

The accurate time-stamp offers the possibility to reorder based on the timestamps in a
collection-tool that usually would see notifications from all nodes.
If - for whatever reason - needed, the sequence offers the opportunity to reorder within
the notification-script on a per-node-basis.

Regards,
Klaus

**Comment by wenningerk** [comment]
One clarification for the timestamp: strftime would just gives you seconds but in addition it is planned to have %N for nanoseconds as being used in 'date'.

**Comment by HideoYamauchi** [comment]
Hi Klaus,

Thank you for comment.

I pay attention to your new patch.
 * https://github.com/ClusterLabs/pacemaker/pull/950

I pray for your realizing the function of the better notice

Best Regards,
Hideo Yamauchi.

**Pull request closed without merging**
