### PR TITLE
Cleanup: crmd: drop superfluous includes

### PR DESCRIPTION
**Pull request by jnpkrn**
Piggyback a comment reformat within.

* * *

```
4 files changed, 28 insertions(+), 92 deletions(-)
```
Oh, well...

### CODE REVIEW

**Comment by kgaillot** [comment]
It's best not to rely on transitive includes (which can change over time) for symbols used directly in the file itself.

**Comment by jnpkrn** [comment]
That wasn't the sort of includes I was dropping, unlike the totally useless ones
and unless I overlooked something.  But when something was unclear or too
difficult to check in depth, I was rather sticking to err on the safe side.

**Comment by jnpkrn** [comment]
@kgaillot, for the record, if we prefer technological purity, I was
experimenting with https://include-what-you-use.org/ however there is
no mortal to review the changes exhaustively, and it could make the
includes more compex as sometimes the reuse-through-transitivity is
the unpronounced goal (with libqb, an example of catch-many include is
`os_base.h`, where this purpose is quite apparent).

If you want to see the results of that tool, I'll add it as an
experimental PR, but no guarantees on my side for the changes.

**Comment by kgaillot** [comment]
It's an interesting project, but I agree that we should probably stick to manual changes, at least for now.

**Pull request merged**
