### PR TITLE
Fix: libcrmservice: avoid async zombie children by resending ignored SIGCHLD

### PR DESCRIPTION
**Pull request by gao-yan**
Previously when executing a synchronous action, if there were existing asynchronous actions on-going, any SIGCHLD for those child processes would be redirected and ignored, so the processes would become zombies.

This commit fixes it by resending any ignored SIGCHLD after the synchronous action has completed and the previous SIGCHLD handler has been restored, so that the asynchronous children will be handled.

Issue exposed in 2.1.5 by bc852fe36. It introduced the asynchronous way of retrieving metadata in controller meanwhile retaining the synchronous way.

See discussion at:
https://github.com/ClusterLabs/pacemaker/pull/2873#discussion_r1472734082

### CODE REVIEW

**Comment by gao-yan** [comment]
It probably anyway makes sense to have something like this as an improvement for the subprocess model to deal with any possible cases mixed with sync and async children, so that it's also a remedy for controller retrieving metadata in the mixed ways given the current code base. 

Let's take a look if it makes sense. I'll see how to test it and also ask the user to try it.

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
@gao-yan apologies for the noise, we are experiencing issues with CI and we are working to fix it.

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Review by kgaillot — APPROVED** [review]
awesome, thanks

**Pull request merged**
