### PR TITLE
Build: spec: Move package files

### PR DESCRIPTION
**Pull request by gao-yan**

### CODE REVIEW

**Comment by beekhof** [comment]
ack on everything else

**Comment by gao-yan** [comment]
Makes sense. Amended.

**Comment by gao-yan** [comment]
Not yet. But I guess most of them currently install also pacemaker package on remote nodes. They will complain once they realize pacemaker is actually not necessary on remote nodes. As Ken brought up,  users would not like to pull in all of pacemaker just because they need to use one of the agents.

Indeed, it makes sense to keep controld and o2cb in pacemaker.  Dummy and Stateful are very useful for testing also on remote nodes though ;-)  ClusterMon doesn't have special dependencies,  given that crm_mon and related stuff have been in pacemaker-cli. We don't have to prevent it from being used on remote nodes, right?

**Comment by gao-yan** [comment]
Amended again. And also moved logrotate configuration file which is useful for remote nodes too.

**Comment by beekhof** [comment]
Here's the problem, crm_attribute needs the -cluster-libs package.
So moving crm_attribute into the -cli package forces it to depend on -cluster-libs too.
Installing cluster-libs therefore requires corosync to be installed.

So now remote nodes are installing corosync for no reason :-(
All because crm_attribute looks up the local node name.

@kgaillot - We need to think about having the server supply the default node name (when it receives the request) instead of the client.

**Comment by beekhof** [comment]
> Dummy and Stateful are very useful for testing also on remote nodes though

Thats our problem though, users shouldn't be using them :)

> ClusterMon

Is dead :)
The new notification code doesn't need it.

**Comment by gao-yan** [comment]
Hmm, right. Then we should move crm_failcount and crm_standby from pacemaker-cli into pacemaker package for now. They require crm_attribute.

The built-in notification is a nice feature :-) But please let's keep ClusterMon at least for a while. I know there are users using it. It's ok to keep it in pacemaker package.

**Comment by gao-yan** [comment]
Amended

**Comment by kgaillot** [comment]
I like where this is going. Just to reinforce the point, a Red Hat support person recently ran into crm_mon errors on a remote node due to the schemas not being installed, and despite being well-versed in pacemaker troubleshooting, didn't see how to resolve that. I think anything usable on a remote node should not require the pacemaker package.

Let's leave crm_failcount and crm_standby in cli; hopefully, we'll get the chance to remove crm_attribute's dependency on the cluster layer before the next release cycle, and we'll be able to move it to cli instead.

If I'm following 53dad06 correctly, wouldn't it (wrongly) move the stonithd/pengine/crmd man pages to the cli package?

What criteria are you using to pick which agents to move? Am I missing something, or wouldn't all the agents be potentially usable on a remote node (with the obvious exception of remote itself)?

I could almost see it being worthwhile to create a new pacemaker-common package with the schemas, MIB and logrotate, and have pacemaker and cli depend on that, so people could install either one without the other if they really wanted to. And maybe even a pacemaker-agents package for the agents, so pacemaker and pacemaker-remote could depend on it without polluting a cli-only deployment. But I'd be reluctant mainly for backward compatibility with existing workflows/scripts.

**Comment by gao-yan** [comment]
Okay, I left crm_failcount and_crm_standy in cli.

You are right about the man pages. Thanks for pointing out.

Actually I'd prefer only keeping the resource agents that won't run on remote nodes in pacemaker package, which are controld, o2cb and remote. Andrew didn't seem to like some agents to be moved into cli. See the comments above. But we can probably rethink it and convince Andrew ;-)

Not sure about the pacemaker-common. I don't know if any people would want to run pacemaker without cli. Given that  there's already quite several sub-packages,  personally I'd not prefer to split off more unless it's very necessary.

**Pull request merged**
