### PR TITLE
Make some changes to crm_resource printing

### PR DESCRIPTION
**Pull request by clumens**
Note the comments on both, especially the first patch where I've changed the output format somewhat.

### CODE REVIEW

**Comment by kgaillot** [comment]
Looks good, thanks.  Let's spell out "value", to be more similar to how attrd_updater and crm_attribute show node attributes (though even those are not as consistent with each other as they should be).

**Comment by clumens** [comment]
Would you prefer a new PR with that change rolled in place, or a followup patch that just changes val to value?

**Comment by kgaillot** [comment]
rolled in, thx

**Comment by clumens** [comment]
Okay, I'm going to close this PR and open a new one with the updated first patch.  I don't really know of a better way to do that with github, sadly.

**Comment by kgaillot** [comment]
> Okay, I'm going to close this PR and open a new one with the updated first patch. I don't really know of a better way to do that with github, sadly.

I use:

git push origin +'commit':'branchname'

because it deletes everything in the github branch that's not in the local branch. 'commit' is usually HEAD but it's nice to have the option to use something earlier if I have some commits locally that I'm not ready to push.

**Pull request closed without merging**
